### ISSUE TITLE
Pipenv no longer considers dynamically-generated dependencies of local packages

### ISSUE THREAD

**Issue by yoavg** [pypa/pipenv#4631] opened 2021-02-22 20:00 UTC
### Issue description

Latest version of pipenv does not consider dependencies of local packages, if these dependencies are dynamically generated in setup.py. 
 
See a concrete example in the "steps to replicate" below. 

This did work in previous versions of pipenv. 

### Steps to replicate

`mkdir local_dep`
`mkdir module`

create `local_dep/setup.py` with the following content:
```
import setuptools

def reqs():
    return ["tqdm"]

setuptools.setup(
    name="name",
    version="0.0.1",
    python_requires="==3.7.*",
    install_requires=reqs()
)
```

now:
```
cd module
pipenv --python 3.7
pipenv install -e ../local_dep
```

*Result:* `tqdm` does not appear in `Pipfile.lock`.
*Expected results:* `tqdm` should appear in `Pipfile.lock`

Note: we do get tqdm in Pipfile.lock with the following `setup.py`:
```
import setuptools

setuptools.setup(
    name="name",
    version="0.0.1",
    python_requires="==3.7.*",
    install_requires=["tqdm"]
)
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@3.7/bin/python3.7'`

Python installations found:

  - `3.9.0`: `/usr/local/bin/python3`
  - `3.9.0`: `/usr/local/bin/python3.9`
  - `3.7.9`: `/usr/local/opt/python@3.7/bin/python3`
  - `3.7.9`: `/usr/local/opt/python@3.7/bin/python3.7m`
  - `3.7.9`: `/usr/local/opt/python@3.7/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT '
                     '2020; root:xnu-6153.141.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.9',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PWD`
  - `SHELL`
  - `SECURITYSESSIONID`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `DISPLAY`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `LaunchInstanceID`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `BROWSER`
  - `EDITOR`
  - `VISUAL`
  - `PAGER`
  - `LANG`
  - `LESS`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `LSCOLORS`
  - `LS_COLORS`
  - `GREP_COLOR`
  - `GREP_COLORS`
  - `PERL5LIB`
  - `PERL_LOCAL_LIB_ROOT`
  - `PERL_MB_OPT`
  - `PERL_MM_OPT`
  - `DYLD_LIBRARY_PATH`
  - `LDFLAGS`
  - `SDKMAN_DIR`
  - `SDKMAN_VERSION`
  - `SDKMAN_CANDIDATES_API`
  - `SDKMAN_PLATFORM`
  - `SDKMAN_CANDIDATES_DIR`
  - `SBT_HOME`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/yogo/.sdkman/candidates/sbt/current/bin:/usr/local/opt/python@3.7/bin:/Users/yogo/google-cloud-sdk/bin:/Users/yogo/miniconda3/bin:/Users/yogo/perl5/bin:/Users/yogo/bin:/Users/yogo/miniconda2/bin:/Users/yogo/Library/Python/3.7/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/yogo/.local/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/yogo/Vork/playwith/sp2/module`

---------------------------

Contents of `Pipfile` ('/Users/yogo/Vork/playwith/sp2/module/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
name = {editable = true, path = "./../local_dep"}

[dev-packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/yogo/Vork/playwith/sp2/module/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "b2f0607121c49681418a3728b58c597d876c8cde1f2b7cf8c12e3cd50c41438c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "name": {
            "editable": true,
            "path": "./../local_dep"
        }
    },
    "develop": {}
}

```
</details>

**Comment by yoavg** [comment] 2021-07-07 20:39
bump

**Comment by matteius** [comment] 2021-12-24 08:26
@yoavg I am testing all of the local installable issues and for yours, with the latest version `pipenv==2021.11.23` I find it doesn't have this particular issue.  There is still the issue that dynamic dependency setup.py have to be installed twice, once to generate the `reqlib-metadata` directory in the `local_dep` ... this run yields the `OSError: [Errno 26] Text file busy: 'name.egg-info'` error and subsequent try works.    My plan is to close this ticket since this issue is being tracked in many tickets and has evolved over the versions of pipenv released.

```
mdavis@matt-VirtualBox:~/shared-projects/pipenv-4631/module$ vim Pipfile 

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4631/module$ pipenv install -e ../local_dep

Creating a virtualenv for this project...

Pipfile: /home/mdavis/shared-projects/pipenv-4631/module/Pipfile

Using /home/mdavis/.pyenv/versions/3.7.12/bin/python3.7m (3.7.12) to create virtualenv...

⠧ Creating virtual environment...created virtual environment CPython3.7.12.final.0-64 in 371ms

  creator CPython3Posix(dest=/home/mdavis/.virtualenvs/module-eFP90uzM, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mdavis/.local/share/virtualenv)

    added seed packages: pip==21.3.1, setuptools==59.2.0, wheel==0.37.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator



✔ Successfully created virtual environment! 

Virtualenv location: /home/mdavis/.virtualenvs/module-eFP90uzM

Installing -e ../local_dep...

Adding name to Pipfile's [packages]...

✔ Installation Succeeded 

Pipfile.lock not found, creating...

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (41438c)!

Installing dependencies from Pipfile.lock (41438c)...

  🎅   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/home/mdavis/.local/lib/python3.9/site-packages/pipenv/vendor/vistir/path.py", line 433, in rmtree

    shutil.rmtree(directory, ignore_errors=ignore_errors, onerror=onerror)

  File "/usr/lib/python3.9/shutil.py", line 726, in rmtree

    _rmtree_safe_fd(fd, path, onerror)

  File "/usr/lib/python3.9/shutil.py", line 667, in _rmtree_safe_fd

    onerror(os.rmdir, fullname, sys.exc_info())

  File "/home/mdavis/.local/lib/python3.9/site-packages/pipenv/vendor/vistir/path.py", line 528, in handle_remove_readonly

    raise exc_exception

  File "/usr/lib/python3.9/shutil.py", line 665, in _rmtree_safe_fd

    os.rmdir(entry.name, dir_fd=topfd)

OSError: [Errno 26] Text file busy: 'name.egg-info'

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4631/module$ pipenv install -e ../local_dep

Installing -e ../local_dep...

Adding name to Pipfile's [packages]...

✔ Installation Succeeded 

Installing dependencies from Pipfile.lock (41438c)...

  🎅   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4631/module$ cat Pipfile.lock 

{

    "_meta": {

        "hash": {

            "sha256": "b2f0607121c49681418a3728b58c597d876c8cde1f2b7cf8c12e3cd50c41438c"

        },

        "pipfile-spec": 6,

        "requires": {

            "python_version": "3.7"

        },

        "sources": [

            {

                "name": "pypi",

                "url": "https://pypi.org/simple",

                "verify_ssl": true

            }

        ]

    },

    "default": {

        "name": {

            "editable": true,

            "path": "./../local_dep"

        },

        "tqdm": {

            "hashes": [

                "sha256:8dd278a422499cd6b727e6ae4061c40b48fce8b76d1ccbf5d34fca9b7f925b0c",

                "sha256:d359de7217506c9851b7869f3708d8ee53ed70a1b8edbba4dbcb47442592920d"

            ],

            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",

            "version": "==4.62.3"

        }

    },

    "develop": {}

}

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4631/module$ pipenv --version
pipenv, version 2021.11.23
```

**Comment by matteius** [comment] 2022-03-13 03:47
Sorry I re-opened this by mistake exploring the other linked ticket, but actually am unable to reproduce with the newer versions of pipenv.

**Closed by matteius** 2022-03-13 03:47 UTC
