### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by elfelround** [pypa/pipenv#3483] opened 2019-01-26 13:04 UTC
upon installing pipenv with pip3 both pipenv and pip3 fail to work as commands

if i can recall correctly it has to do with the default pip from the computer being upgraded, cant remember how i usually fix this, i think most the time a reboot works but then sometimes it happens, what u do about this?

example image https://scontent-mad1-1.xx.fbcdn.net/v/t1.0-9/51007051_2221884381409629_32650208240205824_o.jpg?_nc_cat=105&_nc_eui2=AeF6hYk3AdUp1i75U1g8H1r91cOQVzMxUEid_85aUO_yupk357jDN38nY4RALrpUYFlgATPkPFpXFUcw_BX2oeO5ojK7LXu4o8RUr8k7nGiKpQ&_nc_ht=scontent-mad1-1.xx&oh=7bf46bd760cd8d71d49118e9555bd1e1&oe=5CC22A16

similar to this post https://stackoverflow.com/questions/51225750/installation-of-pipenv-causes-pip3-unusable

ubuntu@ip-172-31-43-213:~$ git clone https://Mr-Programs@bitbucket.org/Mr-Programs/tfn.git
Cloning into 'tfn'...
Password for 'https://Mr-Programs@bitbucket.org': 
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (21/21), done.
ubuntu@ip-172-31-43-213:~$ cd tfn
ubuntu@ip-172-31-43-213:~/tfn$ pipenv shell
pipenv: command not found
ubuntu@ip-172-31-43-213:~/tfn$ pip3 install pipenv
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl (5.2MB)
    100% |████████████████████████████████| 5.2MB 255kB/s 
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/e3/d9/d9c56deb483c4d3289a00b12046e41428be64e8236fa210111a1f57cc42d/virtualenv_clone-0.5.1-py2.py3-none-any.whl
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/8f/f1/c0b069ca6cb44f9681715232e6d3d65c75866dd231c5e4a88e80a46634bb/virtualenv-16.3.0-py2.py3-none-any.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 722kB/s 
Collecting setuptools>=36.2.1 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl (573kB)
    100% |████████████████████████████████| 573kB 2.0MB/s 
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 7.6MB/s 
Collecting pip>=9.0.1 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.0MB/s 
Installing collected packages: virtualenv-clone, setuptools, virtualenv, certifi, pip, pipenv
Successfully installed certifi-2018.11.29 pip-19.0.1 pipenv-2018.11.26 setuptools-40.6.3 virtualenv-16.3.0 virtualenv-clone-0.5.1
ubuntu@ip-172-31-43-213:~/tfn$ pipenv shell
pipenv: command not found
ubuntu@ip-172-31-43-213:~/tfn$ sudo pip3 install pipenv
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
ubuntu@ip-172-31-43-213:~/tfn$ pip3 install pipenv
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
ubuntu@ip-172-31-43-213:~/tfn$ pip3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
ubuntu@ip-172-31-43-213:~/tfn$

**Comment by frostming** [comment] 2019-01-27 00:01
I have also come across it. It turned out that   pip19.0 was installed in user home and overridided the system library, while the pip3 executable was still 9.0


the fix is to first upgrade system's pip by sudo pip3 install --upgrade pip

**Comment by elfelround** [comment] 2019-01-28 13:36
> I have also come across it. It turned out that pip19.0 was installed in user home and took priority to the system library, while the pip3 executable was still 9.0
> 
> the fix is to first upgrade system's pip by `sudo pip3 install --upgrade pip`

interesting but as you can see from the linked image, pip3 is also broken

**Comment by frostming** [comment] 2019-01-28 13:50
@elfelround Yes I was talking about the pip breakage in my comment, wasn't I? I believe the solution should work.

**Comment by elfelround** [comment] 2019-01-28 15:52
@frostming I will try, but as i told you, since pip3 doesnt work sudo pip3 install shouldnt work either

**Comment by elfelround** [comment] 2019-01-31 13:02
eemmm no are you trying to break my system?

**Comment by frostming** [comment] 2019-02-01 01:00
@elfelround I can't see why removing pip can break your system. I provided a solution but you refused to take it. Well, it is time to close it since the issue is not even related to Pipenv.

**Closed by frostming** 2019-02-01 01:00 UTC
