### ISSUE TITLE
Regression in 2020.05.28 -- pipenv sync fails in Gitlab CI context

### ISSUE THREAD

**Issue by freekwiekmeijer** [pypa/pipenv#4272] opened 2020-05-28 10:14 UTC
The following package requirement is broken:

[packages]
my_package_name = {git = "https://gitlab+deploy-token-8:xxxYYYzzz@gitlab.my-domain.com/path/to/project.git",editable = true,ref = "0.0.1_dev"}

In the logging of the gitlab CI server we see that the deploy token is represented as:

gitlab deploy-token-8

(notice that the '+' sign turned into a space).

pipenv sync fails on this package.

We went back to version pipenv==2018.11.26 and the CI job succeeds again.

**Comment by GPHemsley** [comment] 2020-05-28 15:23
This appears to be a dupe of #4271.

**Comment by techalchemy** [comment] 2020-05-28 15:56
Thanks for the report! I agree it is a duplicate -- closing in favor of #4271

**Closed by techalchemy** 2020-05-28 15:56 UTC
Labels: Type: Duplicate, Type: Regression, Type: Vendored Dependencies
