### ISSUE TITLE
Local copy of python3 is not executable.

### ISSUE THREAD

**Issue by quistian** [pypa/pipenv#3473] opened 2019-01-23 15:22 UTC
### Issue description

I am trying to use pipenv on an OpenBSD system. The install works fine. When I try to create a project and install a module, the local version of python3 binary fails to execute.

I am wondering if there are some filesystem locks on the python binary being copied from /usr/local to /home

$ mount
/dev/sd0a on / type ffs (local)
/dev/sd0k on /home type ffs (local, nodev, nosuid)
/dev/sd0d on /tmp type ffs (local, nodev, nosuid)
/dev/sd0f on /usr type ffs (local, nodev)
/dev/sd0g on /usr/X11R6 type ffs (local, nodev)
/dev/sd0h on /usr/local type ffs (local, nodev, wxallowed)
/dev/sd0j on /usr/obj type ffs (local, nodev, nosuid)
/dev/sd0i on /usr/src type ffs (local, nodev, nosuid)
/dev/sd0e on /var type ffs (local, nodev, nosuid)

### Expected result

Creating a Pipfile for this project...
Creating a virtualenv for this project...
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'
New python executable in ~/.local/share/virtualenvs/tmp-agwWamBd/bin/python3.6
Also creating executable in ~/.local/share/virtualenvs/tmp-agwWamBd/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: ~/.local/share/virtualenvs/tmp-agwWamBd
Installing requests...
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, chardet, certifi, requests
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

Adding requests to Pipfile's [packages]...
P.S. You have excellent taste! ✨ 🍰 ✨

### Actual result

pipenv --verbose install requests
Creating a virtualenv for this project…
Pipfile: /home/russ/src/hello/Pipfile
Using /usr/local/bin/python3 (3.6.6) to create virtualenv…
⠙ Creating virtual environment...Already using interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
New python executable in /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python3
Not overwriting existing python script /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python (you must use /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python3)
ERROR: The executable /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python3 could not be run: [Errno 13] Permission denied: '/home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python3'

✘ Failed creating virtual environment
Traceback (most recent call last):
  File "/home/russ/.local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/home/russ/.local/lib/python3.6/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
    extra=[crayons.blue("{0}".format(c.err)),]
pipenv.exceptions.VirtualenvCreationException: Failed to create virtual environment.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

# mkdir hello
# cd hello
# pipenv install requests

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it!
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/russ/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python3'`

Python installations found:

  - `3.6.6`: `/usr/local/bin/python3`
  - `3.6.6`: `/usr/local/bin/python3.6m`
  - `2.7.15`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'amd64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.4',
 'platform_system': 'OpenBSD',
 'platform_version': 'GENERIC.MP#364',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'openbsd6'}
```

System environment variables:

  - `_`
  - `LOGNAME`
  - `PWD`
  - `HOME`
  - `OLDPWD`
  - `SSH_TTY`
  - `LANG`
  - `MAIL`
  - `SSH_CLIENT`
  - `PATH`
  - `TERM`
  - `SHELL`
  - `SSH_CONNECTION`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/russ/bin:/home/russ/.local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games:.`
  - `SHELL`: `/bin/ksh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/russ/src/hello`

---------------------------

Contents of `Pipfile` ('/home/russ/src/hello/Pipfile'):

```toml

```

</details>

**Comment by techalchemy** [comment] 2019-03-05 06:28
note that during your attempt to install the following message appeared:

```
Not overwriting existing python script /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python (you must use /home/russ/.local/share/virtualenvs/hello-ogF-LQCP/bin/python3)
```

This means the install _didn't_ write to this location, because there was already a virtualenv there.  The following `PermissionError` suggests that said virtualenv was created with superuser permissions.  Please remove the virtualenv with the appropriate permissions and try again -- but if you continue to have issues, it's likely a virtualenv issue as pipenv doesn't actually create the environment it just calls virtualenv to do so

Closing for now as it doesn't appear to have a pipenv-related cause

**Closed by techalchemy** 2019-03-05 06:28 UTC

**Comment by jeredav** [comment] 2019-03-06 18:21
The permission error is most likely caused by the fact that the partition containing '/home' was mounted with file execution permissions. 'wxallowed' should be added to the mount options for that partition in '/etc/fstab'.
