### ISSUE TITLE
CLI reference page is empty

### ISSUE THREAD

**Issue by gismoranas** [pypa/pipenv#4986] opened 2022-03-16 13:09 UTC
### Issue description

https://pipenv.pypa.io/en/latest/cli/ does not show any useful information. on https://pipenv-es.readthedocs.io/es/latest/ I can see the reference. checked on chrome with adblocker deactivated.

### Expected result

see the docs.

### Actual result

I only see the text column on the left.

### Steps to replicate

open the page in chrome.

**Comment by matteius** [comment] 2022-03-16 20:56
@gismoranas Thanks for your issue report, however I am noting it is a duplicate of:  https://github.com/pypa/pipenv/issues/4778

Going to close this one out, but feel free to open a PR against the other issue if you have time to fix it.

**Closed by matteius** 2022-03-16 20:56 UTC
