### ISSUE TITLE
pipenv install updates locked packages I would not have expected

### ISSUE THREAD

**Issue by kstrauser** [pypa/pipenv#1219] opened 2017-12-18 21:46 UTC
`pipenv install pkg` updates the versions of unrelated packages in Pipfile.lock. This runs counter to an expectation that the new package would be added to Pipfile and Pipfile.lock without touching other stuff.

##### Describe your environment

1. OS Type
1. Python version: `$ python -V`: Python 3.6.3
1. Pipenv version: `$ pipenv --version`: **pipenv**, version 9.0.1

##### Expected result

When I run `pipenv install foo`, everything but `foo` (and any _new_ dependencies it brings in) should be left as-is.

##### Actual result

Running `pipenv install foo` or `pipenv install --ignore-pipfile foo` adds `foo` _and_ upgrades everything else.

##### Steps to replicate

Let's say I'm upgrading an existing project that used requirements.txt:

```shell
$ cat requirements.txt
toposort==1.4
```

Yay pipenv! Let's make the switch:

```shell
$ pipenv --three
Creating a virtualenv for this project…
[...]
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did.
We recommend updating your Pipfile to specify the "*" version, instead.
```

Now we'll install the required package and see what's actually in Pipfile.lock:

```shell
$ pipenv install
Pipfile.lock not found, creating…
[...]

$ jq '.default.toposort.version' < Pipfile.lock
"==1.4"
```

That worked! But there was a warning about pinning the version with Pipfile.lock instead of Pipfile, so let's remove that pin:

```shell
$ sed -i'' -e 's/==1.4/*/' Pipfile
$ grep toposort Pipfile
toposort = "*"
```

Awesome - we're using the lockfile now. Hmm, we really need to install another package, though:

```shell
$ pipenv install yapf
[...]
```

That worked, so now Pipfile.lock has the new package _and_ pre-existing package at its old version, right?

```shell
$ jq '.default.toposort.version' < Pipfile.lock
"==1.5"
```

That... is not what I'd expected. I get the same results in the last couple of steps if I tell pipenv to ignore Pipfile:

```shell
# Repeat all the steps prior to pipenv install yapf, then:
$ pipenv install --ignore-pipfile yapf
$ jq '.default.toposort.version' < Pipfile.lock
"==1.5"
```

**Comment by taion** [comment] 2017-12-19 04:33
This is https://github.com/pypa/pipenv/issues/966, BTW.

**Comment by techalchemy** [comment] 2017-12-21 22:57
@kstrauser thanks for the report, but I'm not sure this is a bug...  When you unpin your Pipfile you are essentially giving the resolver free reign to figure out what version of any given package can fit within the constraints of the other packages in your environment.  That's why we recommend unpinning -- for multi-package environments, the resolver does the heavy-lifting of determining which packages require other packages to be specific versions.  If you unpin something, and then you re-resolve your dependencies (which is what locking does, and which happens whenever you install something because, well, dependencies will have to be resolved all over again), the resolver is going to re-evaluate your packages in the new context with the new install.

If the resolver finds that there is a package that can be upgraded (i.e. there is no other package in your environment holding it back, and you have unpinned it), it will go ahead and resolve it forward.  If you require specific versions of packages and you do not want the resolver to make that determination you will need to pin those.

As a sidenote, `--ignore-pipfile` is a meaningless option when you are installing a new package.  Anything that introduces something new to the environment can't ignore the pipfile, as it is writing to the pipfile.  The only way to avoid re-resolving the environment is to use `--skip-lock`, which also will not include the new package in the lockfile.  Similar to `--deploy`, `--ignore-pipfile` is meant when you are installing a pre-built lockfile into an environment (like a production environment for example) and you don't want any chance of the resolver taking the pipfile into consideration.

I hope that helps clear up what is going on in this case.  I'm going to go ahead and  close this as it is pretty much inherent to the nature of pipenv

**Closed by techalchemy** 2017-12-21 22:57 UTC

**Comment by taion** [comment] 2017-12-21 23:04
@techalchemy 

Again, I'd like to note that other locking package managers don't work this way. In fact, `pip-compile` in pip-tools doesn't work this way either – it doesn't update dependencies unnecessarily.

As a user, it's undesirable and unexpected for other dependencies to update when I interact with my Pipfile. Part of the point of the lockfile is to ensure reproducibility, and in practice part of what that means is that my dependencies don't change under me for reasons that feel unexpected.

Something like, say, Flake8 updating under me because I tried to upgrade some other package just feels bad as a user – especially because semver isn't really a thing in the Python ecosystem. It doesn't really match the "for humans" tag – the bulk of humans who have worked with package managers that operate in this manner do not expect this behavior.

**Comment by kstrauser** [comment] 2017-12-21 23:44
@techalchemy I have to agree with @taion. Say I have Django==1.11.9 in Pipfile.lock. I've heard good things about flake8 so I install it. I'd be very surprised to find that I'm now on Django 2.0 afterward! I do understand that there are weird cases like "you currently have a==1.2.3 installed, and are asking to install b which depends on a==2.4.6, so I must upgrade a now". But in the situation where I have a==1.2.3, and b depends on a>=1.0, I'd like to tell pipenv to leave a alone.

If `pipenv install --ignore-pipfile foo` ignores `--ignore-pipfile`, then I think using that flag in that context should return an error. Your point that you can't wholly ignore the pipfile is totally reasonable, but I had thought/hoped/wished that it might have meant "ignore the _versions_ in pipfile and rely on the versions given in the lockfile" in that invocation.

**Comment by kstrauser** [comment] 2017-12-21 23:50
@techalchemy I think this also diverges significantly from users' previous experiences with pip. Not that pipenv should exactly mirror pip, for then there'd be no reason to switch to it, surely! But still, with pip I could run:

```shell
$ virtualenv -p python3.6 foo
$ . foo/bin/activate
$ pip install toposort==1.4
$ pip install yapf
$ pip freeze
toposort==1.4
yapf==0.20.0
```

and have both packages at their expected version because I didn't explicitly upgrade the first one I installed.

**Comment by techalchemy** [comment] 2017-12-22 01:28
@kstrauser I don't think your request is unreasonable, but the implementation is somewhat difficult (the functionality may evolve someday)

As for better messaging, documentation, etc... that I can agree on, and we are always happy to accept contributions on those fronts.  Sometimes the behavior isn't what you hope it is, even if the explanation afterwards makes sense.  In those cases it would be nice to get the explanation to you beforehand :)

**Comment by mixxorz** [comment] 2018-01-26 05:50
Maybe Pipenv should do what npm does and make `pipenv install` pin to the major version instead of `'*'`.

**Comment by kylegibson** [comment] 2018-01-26 17:32
Continuing mixxorz' thought, or have an option to pin the version without having to explicitly specify up front what that version is. Doesn't necessarily have to be the default.
