### ISSUE TITLE
pipenv fail to install pyinstaller on python3.6

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#3626] opened 2019-03-19 10:54 UTC
Pipfile:
`pyinstaller = "*"`

Pipfile.lock:
```
        "pyinstaller": {
            "hashes": [
                "sha256:a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b"
            ],
            "index": "pypi",
            "version": "==3.4"
        },
```

I insall pyinstaller error, the console output message:

Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting pyinstaller==3.4 (from -r C:\\Users\\lei\\AppData\\Local\\Temp\\pipenv-t0f588_k-requirements\\pipenv-0m9w9lvo-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'error'", '  Complete output from command c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\scripts\\python.exe c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip install --ignore-installed --no-user --prefix C:\\Users\\lei\\AppData\\Local\\Temp\\pip-build-env-quethea4\\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel:', '  Traceback (most recent call last):', '    File "C:\\Python36\\Lib\\runpy.py", line 193, in _run_module_as_main', '      "__main__", mod_spec)', '    File "C:\\Python36\\Lib\\runpy.py", line 85, in _run_code', '      exec(code, run_globals)', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\__main__.py", line 16, in <module>', '      from pip._internal import main as _main  # isort:skip # noqa', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\__init__.py", line 40, in <module>', '      from pip._internal.cli.autocompletion import autocomplete', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\cli\\autocompletion.py", line 8, in <module>', '      from pip._internal.cli.main_parser import create_main_parser', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\cli\\main_parser.py", line 12, in <module>', '      from pip._internal.commands import (', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\commands\\__init__.py", line 6, in <module>', '      from pip._internal.commands.completion import CompletionCommand', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\commands\\completion.py", line 6, in <module>', '      from pip._internal.cli.base_command import Command', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py", line 25, in <module>', '      from pip._internal.index import PackageFinder', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\index.py", line 41, in <module>', '      from pip._internal.wheel import Wheel', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip\\_internal\\wheel.py", line 7, in <module>', '      import compileall', '    File "C:\\Python36\\Lib\\compileall.py", line 20, in <module>', '      from concurrent.futures import ProcessPoolExecutor', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\concurrent\\futures\\__init__.py", line 8, in <module>', '      from concurrent.futures._base import (FIRST_COMPLETED,', '    File "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\concurrent\\futures\\_base.py", line 381', '      raise exception_type, self._exception, self._traceback', '                          ^', '  SyntaxError: invalid syntax', '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Command "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\scripts\\python.exe c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip install --ignore-installed --no-user --prefix C:\\Users\\lei\\AppData\\Local\\Temp\\pip-build-env-quethea4\\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel" failed with error code 1 in None']
ERROR: ERROR: Package installation failed...
     ================================ 0/1 - 00:00:06

**Comment by frostming** [comment] 2019-03-19 12:29
It seams you installed a broken `future` module.

What Python versions are you using in venv and Pipenv?

**Comment by leileigong** [comment] 2019-03-20 02:33
i use Pipenv version is 2018.11.26, Python version in Pipenv is 3.6.6

**Comment by frostming** [comment] 2019-03-20 02:37
It seems `c:\users\lei\.virtualenvs\testtool_ux--hozrla0\lib\site-packages\concurrent\futures` is a package for Python 2.7, can you check why it exists?
And just remove the package and see if it works.

**Comment by leileigong** [comment] 2019-03-20 04:30
I got it.In my Pipfile exist `futures = "*"`. This will install **concurrent**.
Then I remove `futures = "*"`, but still fail.

Here is log:
`Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting pyinstaller==3.4 (from -r C:\\Users\\lei\\AppData\\Local\\Temp\\pipenv-pjze506v-requirements\\pipenv-r27sm_7i-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'error'", '  Complete output from command c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\scripts\\python.exe c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip install --ignore-installed --no-user --prefix C:\\Users\\lei\\AppData\\Local\\Temp\\pip-build-env-e_a4otb5\\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel:', '  pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.', '  Collecting setuptools', '    Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by \'SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)\': /simple/setuptools/', '    Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by \'SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)\': /simple/setuptools/', '    Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by \'SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)\': /simple/setuptools/', '    Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by \'SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)\': /simple/setuptools/', '    Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by \'SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)\': /simple/setuptools/', '    Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host=\'pypi.org\', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)) - skipping', '    Could not find a version that satisfies the requirement setuptools (from versions: )', '  No matching distribution found for setuptools', '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Command "c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\scripts\\python.exe c:\\users\\lei\\.virtualenvs\\testtool_ux--hozrla0\\lib\\site-packages\\pip install --ignore-installed --no-user --prefix C:\\Users\\lei\\AppData\\Local\\Temp\\pip-build-env-e_a4otb5\\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel" failed with error code 1 in None']
ERROR: ERROR: Package installation failed...
     ================================ 0/1 - 00:00:15`

**Comment by frostming** [comment] 2019-03-20 04:41
`Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host=\'pypi.org\', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",)) - skipping`
There was a SSL error with your python installation. Aslo, please don't track `setuptools` in your Pipfile.
And please provide the Pipfile if possible.

**Comment by leileigong** [comment] 2019-03-20 05:13
i guess only `PyInstaller ` track `setuptools` in my Pipfile.


Here is my Pipfile content:

`[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
py2exe_py2 = {version = "==0.6.9", markers = "python_version == '2.7' and sys_platform == 'win32'"}
colorama = "==0.3.7"
configparser = "==3.5.0"
constantly = "==15.1.0"
jsonschema = "==2.5.1"
matplotlib = "==2.1.2"
pickleshare = "==0.7.2"
py = "==1.4.33"
pyasn = "==1.5.0b7"
"pyasn1" = "==0.1.9"
"pyasn1-modules" = "==0.0.8"
selectors = "==0.0.14"
selenium = "==2.53.6"
service-identity = "==17.0.0"
terminaltables = "==3.1.0"
threadpool = "==1.3.2"
traitlets = "==4.2.2"
typing = "==3.6.2"
"urllib3" = "==1.22"
pyserial = "==3.4"
futures = {version = "*", markers = "python_version == '2.6' or python_version == '2.7'"}
pyscard-cp27-win32 = {path = "wheelhouse/pyscard-1.9.7-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
pyscard-cp36-win32 = {path = "wheelhouse/pyscard-1.9.7-cp36-cp36m-win_amd64.whl", markers = "python_version == '3.6'", sys_platform = "== 'win32'"}
pycrypto-cp27-win32 = {path = "wheelhouse/pycrypto-2.6.1-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
pycrypto-cp36-win32 = {path = "wheelhouse/pycrypto-2.6.1-cp36-cp36m-win_amd64.whl", markers = "python_version == '3.6'", sys_platform = "== 'win32'"}
crc16-cp27-win32 = {path = "wheelhouse/crc16-0.1.1-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
crc16-cp36-win32 = {path = "wheelhouse/crc16-0.1.1-cp36-cp36m-win_amd64.whl", markers = "python_version == '3.6'", sys_platform = "== 'win32'"}
pyasn-cp27-win32 = {path = "wheelhouse/pyasn-1.5.0b7-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
pyopengl-cp27-any = {path = "wheelhouse/PyOpenGL-3.1.0-cp27-none-any.whl", markers = "python_version == '2.7'",  sys_platform = "== 'win32'"}
pyopengl-accelerate-cp27-win32 = {path = "wheelhouse/PyOpenGL_accelerate-3.1.0-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
qrcode = "==5"
wxpython = "==4.0.3"
pypubsub = "==3.3.0"
utilityhelper = "==0.1.4"
pillow = "==5.4.1"
pyinstaller = "*"

[requires]
python_version = "3.6"
`

**Comment by frostming** [comment] 2019-07-16 13:23
No more update for this issue, close it now.

**Closed by frostming** 2019-07-16 13:23 UTC
