### ISSUE TITLE
pipenv --lock changes the hashes, without version change

### ISSUE THREAD

**Issue by gonvaled** [pypa/pipenv#2024] opened 2018-04-19 11:40 UTC
Describe the issue briefly here.

My `Pipenv.lock` is committed. I have just recreated it, and I see hash changes, but the pinned version is the same. For example:

```
             "hashes": [
+                "sha256:0c507b7f74b3d2dd4d1322ec8a94794927305ab4cebbe89cc47fe5e81541e6e8",
                 "sha256:16b20e970597e051997d90dc2cddc713a2876c47e3d92d59ee198700c5427736",
                 "sha256:3262c96a1ca437e7e4763e2843746588a965426550f3797a79fca9c6199c431f",
+                "sha256:326420cbb492172dec84b0f65c80942de6cedb5233c413dd824483989c000608",
+                "sha256:4474f8ea030b5127225b8894d626bb66c01cda098d47a2b0d3429b6700af9fd8",
                 "sha256:592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab",
                 "sha256:5ac82e411044fb129bae5cfbeb3ba626acb2af31a8d17d175004b70862a741a7",
+                "sha256:5f84523c076ad14ff5e6c037fe1c89a7f73a3e04cf0377cb4d017014976433f3",
                 "sha256:827dc04b8fa7d07c44de11fabbc888e627fa8293b695e0f99cb544fdfa1bf0d1",
+                "sha256:b4c423ab23291d3945ac61346feeb9a0dc4184999ede5e7c43e1ffb975130ae6",
                 "sha256:bc6bced57f826ca7cb5125a10b23fd0f2fff3b7c4701d64c439a300ce665fff8",
                 "sha256:c01b880ec30b5a6e6aa67b09a2fe3fb30473008c85cd6a67359a1b15ed6d83a4",
+                "sha256:ca233c64c6e40eaa6c66ef97058cdc80e8d0157a443655baa1b2966e812807ca",
                 "sha256:e863072cdf4c72eebf179342c94e6989c67185842d9997960b3e69290b2fa269"
             ],
             "version": "==3.12"
         },
```

Where you can see that new hashes have been added. And this:

```
         "django-cors-middleware": {
             "hashes": [
-                "sha256:25d7e3132e9533be83f62767fca9dc92d66ac9aee414559144ccbce2c2913d70"
+                "sha256:25d7e3132e9533be83f62767fca9dc92d66ac9aee414559144ccbce2c2913d70",
+                "sha256:d427700cdef157b3fe68a33dcce8759f534133a483f2a3b9c12494fe8c598e1c"
             ],
             "index": "pypi",
             "version": "==1.3.1"
         },
```

Where one hash has been deleted and two added. In both cases the package versions have not changed.

Please run `$ python -m pipenv.help`, and paste the results here.

```
» python -m pipenv.help
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv'`

Python location: `'/home/gonvaled/.pyenv/versions/2.7.14/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/home/gonvaled/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/home/gonvaled/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/home/gonvaled/.pyenv/shims/python2.7`
  - `2.7`: `/home/gonvaled/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
Traceback (most recent call last):
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 24, in main
    found = find_python_in_path(python_v)
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/core.py", line 355, in find_python_in_path
    version = python_version(p)
  File "/home/gonvaled/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/utils.py", line 218, in python_version
    return u'{major}.{minor}.{micro}'.format(**version)
TypeError: format() argument after ** must be a mapping, not NoneType
```

------------

##### Expected result

I expected to see only hash changes for packages with newer versions. Maybe I am misunderstanding something.

##### Actual result

The changes in the hashes as described above.

##### Steps to replicate

Re-run `pipenv lock` and see hash changes.

**Comment by uranusjr** [comment] 2018-04-19 12:01
Each hash represents a file on PyPI, and a version can have multiple files. As how the Python packaging infrastructure is implemented, it is totally fine for package maintainers to upload new files to a version after it is published, and if they do that, Pipenv would pick up new hashes. I’d not worry as long as there are no hashes being removed.

**Comment by uranusjr** [comment] 2018-04-19 12:03
(Also the error in the pipenv.help was caused by me. It is fixed in master and should be in the next release. Sorry about the inconvenience.)

**Closed** 2018-04-19 12:03 UTC

**Comment by uranusjr** [comment] 2018-04-20 11:57
It works sort like how you check you downloaded the right file from, say, python.org. You download a file [listed in the table](https://www.python.org/downloads/release/python-365/), and after you’re done, check if the file’s actual hash matches the one listed in the table. `pipenv lock` saves all the hashes in the table locally ahead of time, so it doesn’t need to check online every time you create a new environment (and in some circumstances it can’t), but the idea is the same. It ensures this current download matches the information it got when you lock.

**Comment by uranusjr** [comment] 2018-04-20 12:34
There are two caches, one for the package resolution (what package depends on what), and one for the packages themselves (this is actually cached by pip). The location depends on your operating system; for Linux it is `~/.cache` (or `~/.caches`, I can’t remember).

**Comment by gonvaled** [comment] 2018-04-24 07:15
@uranusjr thanks, understood.

Regarding the changes in the hashes, I am thinking about this:

1. Do not change `Pipenv`
2. Remove `Pipfile.lock`
3. Run `pipenv --lock`

Now I will eventually have changes in `Pipfile.lock` even though the package versions have not been changed since, as you said above "it is totally fine for package maintainers to upload new files to a version after it is published". If I check the changes in the (committed) `Pipfile.lock` I will eventually see hash changes. 

This makes `Pipfile.lock` poorly suited to ensure that my application is built from a reproducible set of packages.

Or said, differently, `pipenv --lock` is not an idempotent operation: the same input `Pipfile` can produce a different output, even with fully pinned versions for all packages, since the ultimate source (`PyPi` for example), can change.

I do not mean this in an academic sense: this is what I am seeing very often when doing `pipenv --lock`

**Comment by techalchemy** [comment] 2018-04-24 11:39
I mean, how often? Until you have more than one example of this happening it just sounds like you’re upset that we used the word idempotent when an element of the stack is out of our control. 

This is fine, but does your lockfile succeed if the situation you describe occurs? The answer is no. You have immediate feedback that your environment can’t be reproduced exactly at the moment. 

And no, locking is not idempotent and was never meant to be. Lockfiles themselves are.
