### ISSUE TITLE
pipenv fail to install pyscard

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#2881] opened 2018-09-23 04:12 UTC
install pyscard fail report that need swig, i wanna to install pyscard easy, not compiling C code.

`pipenv install pyscard`

Collecting pyscard==1.9.7 ----------- 1/2 - 00:00:00
  Using cached https://files.pythonhosted.org/packages/17/f3/e6e52e3dab39b26450d9fb6385c4a40f883180d6f1ee26ad4567dd243edc/pyscard-1.9.7.tar.gz
Building wheels for collected packages: pyscard
  Running setup.py bdist_wheel for pyscard: started
  Running setup.py bdist_wheel for pyscard: finished with status 'error'
  Complete output from command c:\users\lijiaoshi\.virtualenvs\productiontools-obnlhkr2\scripts\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\lijiao~1\\appdata\\local\\temp\\pip-install-wwxszf\\pyscard\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\lijiao~1\appdata\local\temp\pip-wheel-wxzncv --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'smartcard.scard._scard' extension
  swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
  swig.exe -python -outdir smartcard/scard -DWIN32 -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
  error: command 'swig.exe' failed: No such file or directory

  ----------------------------------------
  Running setup.py clean for pyscard
Failed to build pyscard
Installing collected packages: pyscard
  Running setup.py install for pyscard: started
    Running setup.py install for pyscard: finished with status 'error'
    Complete output from command c:\users\lijiaoshi\.virtualenvs\productiontools-obnlhkr2\scripts\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\lijiao~1\\appdata\\local\\temp\\pip-install-wwxszf\\pyscard\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\lijiao~1\appdata\local\temp\pip-record-xks5no\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\lijiaoshi\.virtualenvs\productiontools-obnlhkr2\include\site\python2.7\pyscard:
    running install
    running build
    running build_py
    running build_ext
    building 'smartcard.scard._scard' extension
    swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
    swig.exe -python -outdir smartcard/scard -DWIN32 -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
    error: command 'swig.exe' failed: No such file or directory

    ----------------------------------------

  Failed building wheel for pyscard
Command "c:\users\lijiaoshi\.virtualenvs\productiontools-obnlhkr2\scripts\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\lijiao~1\\appdata\\local\\temp\\pip-install-wwxszf\\pyscard\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\lijiao~1\appdata\local\temp\pip-record-xks5no\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\lijiaoshi\.virtualenvs\productiontools-obnlhkr2\include\site\python2.7\pyscard" failed with error code 1 in c:\users\lijiao~1\appdata\local\temp\pip-install-wwxszf\pyscard\

     ================================ 1/2 - 00:00:03

**Comment by stardust85** [comment] 2018-09-26 20:32
This is probably not a bug of pipenv. I guess you'll get the same error when installing by pip. Please ask authors of pyscard to publish a binary wheel or install swig. And if this works for you, please close this issue. I don't have permissions to close it

**Comment by techalchemy** [comment] 2018-10-07 08:34
(Note that we don't have any actual authority to have people build wheels or anything like that, but they might have an issue tracker you can ask them on)

**Closed by techalchemy** 2018-10-07 08:34 UTC
