### ISSUE TITLE
Traceback on Windows 10 involving _psutil_windows

### ISSUE THREAD

**Issue by brettcannon** [pypa/pipenv#1587] opened 2018-03-07 18:34 UTC
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type: Windows 10
1. Python version: `$ python -V`: 3.6.4
1. Pipenv version: `$ pipenv --version`: 11.1.2

##### Expected result

No traceback

##### Actual result

```
PS C:\Users\brcan\Desktop\pipenv-test> py -3 -m pipenv install
Creating a virtualenv for this project…
Traceback (most recent call last):
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\pew\__main__.py", line 1, in <module>
    import pew
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pew\__init__.py", line 3, in <module>
    from . import pew
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pew\pew.py", line 39, in <module>
    import psutil
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\psutil\__init__.py", line 126, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows'

Virtualenv location:
Creating a Pipfile for this project…
Creating a virtualenv for this project…
Traceback (most recent call last):
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\pew\__main__.py", line 1, in <module>
    import pew
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pew\__init__.py", line 3, in <module>
    from . import pew
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pew\pew.py", line 39, in <module>
    import psutil
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\psutil\__init__.py", line 126, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows'

Virtualenv location:
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (625834)!
Installing dependencies from Pipfile.lock (625834)…
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

##### Steps to replicate

Command in output above.

**Comment by brettcannon** [comment] 2018-03-07 18:35
I also got pipenv trying to use miniconda instead of the Python interpreter I used to launch pipenv when running `pipenv shell`, but I don't know if that's part of this issue or if it would be a separate one.

**Comment by joshcurago** [comment] 2018-03-07 18:41
Same on 11.1.3

**Comment by kennethreitz** [comment] 2018-03-07 20:35
this wasn't happening before?

**Comment by joshcurago** [comment] 2018-03-07 20:36
I reverted to 11.1.0 to resolve my issue temporarily.

**Comment by brettcannon** [comment] 2018-03-07 20:48
I have no idea if the issue was occurring previously because I was blocked on #1474 until now.

**Comment by kennethreitz** [comment] 2018-03-07 20:49
will get a fix out shortly

**Comment by kennethreitz** [comment] 2018-03-07 20:49
once i can reproduce

**Comment by randycoulman** [comment] 2018-03-07 23:28
I've been running into this issue today as well.  I reverted to pipenv 9.1.0 (since that version is working on another machine) and all is well.

On my systems, psutil gets installed directly in site-packages and has the `_psutil_windows.*.pyd` file.  But in `pipenv\vendor\psutil`, there is no such `*.pyd` file.  I haven't been able to verify this, but my current speculation is that, in 9.1.0, the site-packages version of psutil is being used, but in 11.1.3, the vendor version is being used and there is no `pyd` file to load.

**Comment by techalchemy** [comment] 2018-03-08 05:47
Assuming the PR I just submitted doesn't hit any stumbling blocks building against pypy or nix, I just introduced some changes to just remove psutil from the picture entirely

**Comment by uranusjr** [comment] 2018-03-08 06:08
And there you are submitting the “complicated otherwise” solution like it’s nothing… 🤯

**Comment by siddhi** [comment] 2018-03-08 07:53
I got this as well on pipenv 11.1.3. It seems like the vendor version of psutil doesnt have the file _psutil_windows.cp36-win_amd64.pyd which is present when I install psutil normally.

**Comment by etino** [comment] 2018-03-08 10:29
As @randycoulman I reverto to pipenv 10.1.0 and now all is working fine.

These are the packages version installed on my environment. (Windows 10 64bit)

```
certifi (2018.1.18)
chardet (3.0.4)
emoji (0.4.5)
future (0.16.0)
idna (2.6)
pew (1.1.2)
pip (9.0.1)
pipenv (10.1.0)
psutil (5.3.1)
python-telegram-bot (10.0.1)
requests (2.18.4)
setuptools (28.8.0)
urllib3 (1.22)
virtualenv (15.1.0)
virtualenv-clone (0.3.0)
```

**Comment by kennethreitz** [comment] 2018-03-08 12:50
fixed in master

**Comment by kennethreitz** [comment] 2018-03-08 13:03
released!

**Closed** 2018-03-08 13:04 UTC
Labels: bug, windows

**Comment by techalchemy** [comment] 2018-03-08 17:56
@brettcannon @uranusjr @siddhi @joshcurago we are now vendoring a patched version of pew with a native ctypes implementation of the things they were using `psutil` for, so we have dropped our dependence on psutil and unvendored it, I believe @kennethreitz will be cutting a release shortly

**Comment by kennethreitz** [comment] 2018-03-08 17:57
done!

**Comment by randycoulman** [comment] 2018-03-08 18:04
I can confirm that 11.1.5 now works for me.  Thanks for the quick turnaround!
