### ISSUE TITLE
new pipenv shell incompatibility in Android 8 (pexpect, tty.setraw)

### ISSUE THREAD

**Issue by y2kbugger** [pypa/pipenv#1863] opened 2018-03-28 12:23 UTC
Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv'`

Python location: `'/data/data/com.termux/files/usr/bin/python'`

Other Python installations in `PATH`:

  - `3.6`: `/data/data/com.termux/files/usr/bin/python3.6`
  - `3.6`: `/data/data/com.termux/files/usr/bin/python3.6`

  - `3.6.4`: `/data/data/com.termux/files/usr/bin/python`
  - `3.6.4`: `/data/data/com.termux/files/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'aarch64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.88-g93267b1254b1',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Wed Jan 17 18:37:52 UTC 2018',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```
System environment variables:

  - `LS_COLORS`
  - `LD_LIBRARY_PATH`
  - `LANG`
  - `HISTIGNORE`
  - `OLDPWD`
  - `EDITOR`
  - `SSH_AUTH_SOCK`
  - `PREFIX`
  - `PWD`
  - `HOME`
  - `SSH_AGENT_PID`
  - `HISTFILE`
  - `TMPDIR`
  - `PIP_REQUIRE_VIRTUALENV`
  - `VISUAL`
  - `TERM`
  - `SHLVL`
  - `ANDROID_ROOT`
  - `ANDROID_DATA`
  - `EXTERNAL_STORAGE`
  - `PATH`
  - `PS1`
  - `HISTSIZE`
  - `LD_PRELOAD`
  - `HISTFILESIZE`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/data/data/com.termux/files/home/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/data/data/com.termux/files/home/devel/HTooze`
</details>

I tried various combinations of setting SHELL and `--fancy` and `--anyway`

pipenv run works flawlessly.

Termux developers are aware, but it seems like this is a security "enhancement" https://github.com/termux/termux-packages/issues/1359 

##### Expected result

pipenv shell to not crash. 

##### Actual result

```
$ SHELL=/data/data/com.termux/files/usr/bin/bash pipenv shell
Spawning environment shell (/data/data/com.termux/files/usr/bin/bash). Use 'exit' to leave.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)               File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/cli.py", line 572, in shell
    three=three, python=python, fancy=fancy, shell_args=shell_args
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/core.py", line 2174, in do_shell
    c.interact(escape_character=None)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 745, in interact
    tty.setraw(self.STDIN_FILENO)
  File "/data/data/com.termux/files/usr/lib/python3.6/tty.py", line 28, in setraw
    tcsetattr(fd, when, mode)
termios.error: (13, 'Permission denied')
```

##### Steps to replicate

Install termux on Android
```
$ pkg install python
$ pip install  pipenv
$ cd ./project
$ pipenv install --dev
$ SHELL=/data/data/com.termux/files/usr/bin/bash pipenv shell
```
I guess there is another issue that the shell is not detected correctly because of the logon script that's used on termux but that can be fixed my setting the shell.

**Comment by techalchemy** [comment] 2018-03-28 12:44
At a glance this seems like it says you don’t have permissions to open a handle to stdin? How does that work? We don’t really support android and I personally know very little about the platform

**Comment by y2kbugger** [comment] 2018-03-28 13:05
I'm not really sure about the specifics but complex applications such as
Vim and tmux work perfectly even with the way they swap buffers and
completely take over the virtual terminal. Maybe there's a different way of
asking the system for the same thing.

Even `pip install jupyter` works, compiling numpy, matplotlib and pulling
all deps. Then you can run `jupyter notebook` and open http://localhost:8888
in chrome on your phone.

I regret that I don't have any deeper technical information on this
particular issue, but my gut is telling me that with everything else
working this seems like could be a fixed that's close to trivial.

**Comment by uranusjr** [comment] 2018-03-28 13:19
I’m not familiar with Android either, but results from a quick Google search seems to suggest that Python’s tty support is problematic on Android. Probably not much we can do here (without direct support from CPython core developers).

**Comment by y2kbugger** [comment] 2018-03-28 13:34
That's an idea, maybe I will check out 3.7 dev maybe something is been
changed already.

**Comment by techalchemy** [comment] 2018-03-29 04:41
@y2kbugger the core difference is we don’t ever actually use that script. We need `$SHELL` set because we spawn a subshell (thus `Pexpect.pty_spawn`) which would need extra ability to access stdin and such for those reasons. Perhaps those handles work differently on android?

**Comment by y2kbugger** [comment] 2018-03-29 05:11
Google just tightened security in 8 or 8.1

We can read and write to the fd, but setting the flags raw mode is causing
the issue.

I played with editing pexpect and the way pipenv invokes it, running shell
without raw mode but it does indeed break escape sequences, at least the
way I naively tried it.

I also tried a few different ways of running this subshell sourcing the
activation script.

The way I located that script was seeing the path it after running a pipenv
shell so it must be getting used at some point.

Why not something like:

```$SHELL --init-file "/blah/path/activate"```

For shells that support it?

**Comment by uranusjr** [comment] 2018-03-29 05:19
I’m thinking maybe we can just fall back to the Windows alternative (spawning a subprocess) . Is there a way to tell I’m on Android (e.g. `os.name == 'nt'` if I’m on Windows NT core, or `sys.platform`)?

Also what is the easiest way I can get an Android platform to test this?

**Comment by y2kbugger** [comment] 2018-03-29 11:36
```
[@y2k ~]$ pewtwo workon HTooze-xP_ZhbiF
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
[@y2k \W]$ ^[[C^[[C^[[C^[[B
```

It's ignoring some escape chars (arrows) but Ctrl-D still works. Passing cooked mode through pexpect in `do_shell()` both arrows and Ctrl-D were ignored and shown.

**Comment by cgmojoco** [comment] 2018-04-06 18:48
I use Termux/Django/Heroku and need to be able to use pipenv shell.

Apologies for adding clutter, but this effectively puts a block to my ability to develop on the move using my Samsung Note8 (Oreo).

Any expedite appreciated in advance!

**Comment by uranusjr** [comment] 2018-04-06 19:33
@cgmojoco Maybe it’s just me, but I’ve never personally used `pipenv shell` in practice. `pipenv run` is enough for virtually all for my Django development.

**Comment by techalchemy** [comment] 2018-04-10 23:48
`pipenv run` should be enough for what you guys want, I mean we really dont know what the issue is here as we are not android experts

if you guys want to help track this down feel free but I'm going to close this for now because 1) you have an alternative route to achieve the same functionality and 2) android subshell support isn't really on the roadmap (at least internally)

**Closed by techalchemy** 2018-04-10 23:48 UTC
