### ISSUE TITLE
Extras not locked for remote wheels

### ISSUE THREAD

**Issue by OrangeDog** [pypa/pipenv#4685] opened 2021-04-27 13:06 UTC
### Issue description
Dependencies defined with `{ file = "https://____/pkg.whl" extras = ["foo"] }` do not have their extra dependencies locked.

### Expected result
All of the matching extra's dependencies in the wheel's METADATA should be locked.
```
Provides-Extra: foo
Requires-Dist: requests-oauthlib (<2) ; extra == 'foo'
Requires-Dist: oauthlib ; extra == 'foo'
```

### Actual result
Extras are ignored.

### Steps to replicate
```
pipenv lock
```

-------------------------------------------------------------------------------

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/me/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

**Comment by OrangeDog** [comment] 2021-04-29 15:18
Realising that was a pretty old version, I tried again with 2020.11.15.

`pipenv lock` now includes `extras = ...` in the lock, but doesn't add the actual dependencies, and `pipenv sync` doesn't install them.

**Comment by jkukul** [comment] 2021-05-30 16:28
This looks like a duplicate of https://github.com/pypa/pipenv/issues/4407.

**Comment by matteius** [comment] 2021-12-22 10:23
Closing as duplicate of #4407

**Closed by matteius** 2021-12-22 10:23 UTC
