### ISSUE TITLE
Facing the issue with pipenv while resolving the dependencies from pipfile

### ISSUE THREAD

**Issue by pari544** [pypa/pipenv#5117] opened 2022-06-02 10:48 UTC
Hello all,

I am facing issue with pipenv, It is successfully creating the pip environment but while resolving the dependencies in the pipfile it is givng the below error:-

CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement autopep8 (from versions: none)
[ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 823, in _main
[ResolutionFailure]:       pre, clear, verbose, system, write, requirements_dir, packages, dev
[ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 778, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 759, in resolve

My Pipfile looks like as shown below:-

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pylint = "*"
autopep8 = "*"

[packages]
robotframework ="*"
robotframework-sshlibrary = "*"
robotframework-requests = "*"
robotframework-seleniumlibrary = "*"

Could anyone please help me with this issue?

**Comment by matteius** [comment] 2022-06-02 10:57
I think those markers are wrong -- you need like `robotframework ="*"`

**Comment by pari544** [comment] 2022-06-02 11:09
> I think those markers are wrong -- you need like `robotframework ="*"`

Sorry i didn't copy it properly please see the pipfile as shown below:-
There * in inverted commas

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pylint = "*"
autopep8 = "*"

[packages]
robotframework ="*"
robotframework-sshlibrary = "*"
robotframework-requests = "*"
robotframework-seleniumlibrary = "*"

**Comment by matteius** [comment] 2022-06-02 11:29
I see -- @pari544 Possibly because your python 3.10 is not in quotes it is being interpreted as a float value and so its trying to resolve to python 3.1 for which there is no supported version.

**Comment by pari544** [comment] 2022-06-02 12:22
> I see -- @pari544 Possibly because your python 3.10 is not in quotes it is being interpreted as a float value and so its trying to resolve to python 3.1 for which there is no supported version.

But here in this pipfile there is not python version at all. could you please locate me exactly which one you are talking about?

**Comment by matteius** [comment] 2022-06-02 12:29
I see the actual issue now is your stack trace is referencing python 3.6 which support was dropped from pipenv.  You don't state what version of pipenv you are on, but we no longer support 3.6 at all.

**Comment by matteius** [comment] 2022-06-02 12:30
My comment about 3.10 was intended for another thread that I had seen come in via Email. Disregard that.

**Comment by pari544** [comment] 2022-06-02 12:31
I am using the pipenv version  as 2022.4.8

**Comment by pari544** [comment] 2022-06-02 12:34
> I see the actual issue now is your stack trace is referencing python 3.6 which support was dropped from pipenv. You don't state what version of pipenv you are on, but we no longer support 3.6 at all.

Then I understood that i have to upgrade the python to 3.10 version

**Comment by pari544** [comment] 2022-06-02 12:36
> My comment about 3.10 was intended for another thread that I had seen come in via Email. Disregard that.

okay fine understood

**Comment by pari544** [comment] 2022-06-02 12:39
> > I see the actual issue now is your stack trace is referencing python 3.6 which support was dropped from pipenv. You don't state what version of pipenv you are on, but we no longer support 3.6 at all.
> 
> Then I understood that i have to upgrade the python to 3.10 version

Mainly in the error, it is showing that it is not able to locate the autopep and pylint packages to install.
Are these packages are part of pipenv only?

**Comment by matteius** [comment] 2022-06-02 12:39
3.6 support was still present in `2022.4.8`, I just don't have the means or time to support a 3.6 specific environment resolution issue -- likely one of the packages you are calling out requires something that is no longer 3.6 compatible.  Also you didn't give the exact command you ran to generate the error -- next time please follow the issue template.

**Comment by matteius** [comment] 2022-06-02 12:40
@no @pari544 Those packages are in pypi as you can see:
https://pypi.org/project/autopep8/
https://pypi.org/project/pylint/

**Comment by pari544** [comment] 2022-06-02 14:30
> 3.6 support was still present in `2022.4.8`, I just don't have the means or time to support a 3.6 specific environment resolution issue -- likely one of the packages you are calling out requires something that is no longer 3.6 compatible. Also you didn't give the exact command you ran to generate the error -- next time please follow the issue template.

okay.,, command we used is "pipenv install --python3 --dev"  which creates the virtual environment and then it tries to access the pipfile inorder to resolve dependecies which are mentioned in pipfile

**Comment by pari544** [comment] 2022-06-07 04:31
Hello all,

Please help me out with this issue
It would be greatful if you give some solution for this

Thanks

**Comment by matteius** [comment] 2022-06-07 04:52
Sorry @pari544, I am unable to reproduce this issue and you did not follow the issue template which only gives us partial information about your issue.   Are you able to access pypi at all?  The links I provided above are not to be supplied to pipenv, they are for visiting in your browser to check those packages do in fact exist in pypi.  Best regards,

**Comment by pari544** [comment] 2022-06-07 05:02
What is the template I have to follow.. please let me know the template format.. I will mention the issue in that format only.
Yes, I checked manually accessing the "https://pypi.org/simple" and able to access this link

**Comment by matteius** [comment] 2022-06-07 05:07
@pari544 This is the issue template -- https://github.com/pypa/pipenv/issues/new?assignees=&labels=&template=Bug_report.md

Why don't you just open a new bug report using that template and I'll close this one out and we can start over fresh.  There is a lot of conversation here that is not going to be helpful to keep reparsing.

**Closed by matteius** 2022-06-07 05:07 UTC
Labels: Type: Question :grey_question:

**Comment by pari544** [comment] 2022-06-07 05:39
Yes you can close this issue I am creating a new one
