### ISSUE TITLE
pipenv does not work with paths which contains non-latin symbols (for example russian words)

### ISSUE THREAD

**Issue by ivchizhov** [pypa/pipenv#3390] opened 2018-12-17 13:31 UTC
Hi,
pipenv does not work with paths which contains non-latin symbols (for example russian words), see PWD below (in output of pipenv --support).

```bash
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/core.py", line 489, in ensure_virtualenv
    if not project.virtualenv_exists:
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 272, in virtualenv_exists
    if self.pipfile_exists and os.path.exists(self.virtualenv_location):
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 437, in virtualenv_location
    self._virtualenv_location = self.get_location_for_virtualenv()
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 294, in get_location_for_virtualenv
    return str(get_workon_home().joinpath(self.virtualenv_name))
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 421, in virtualenv_name
    sanitized, encoded_hash = self._get_virtualenv_hash(self.name)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 390, in _get_virtualenv_hash
    clean_name, encoded_hash = get_name(name, self.pipfile_location)
  File "/home/surehand/.local/lib/python2.7/site-packages/pipenv/project.py", line 386, in get_name
    hash = hashlib.sha256(location.encode()).digest()[:6]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/surehand/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.5.3`: `/usr/bin/python3.5`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.13`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-8-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.130-2 (2018-10-27)',
 'python_full_version': '2.7.13',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `PYTHONIOENCODING`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GJS_DEBUG_OUTPUT`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `XDG_VTNR`
  - `HOME`
  - `DISPLAY`
  - `SSH_AGENT_PID`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `XAUTHORITY`
  - `JOURNAL_STREAM`
  - `SESSION_MANAGER`
  - `SHLVL`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `QT_QPA_PLATFORMTHEME`
  - `QT_ACCESSIBILITY`
  - `WINDOWPATH`
  - `EDITOR`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GPG_AGENT_INFO`
  - `USERNAME`
  - `XDG_SESSION_DESKTOP`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `XDG_RUNTIME_DIR`
  - `SSH_AUTH_SOCK`
  - `GDMSESSION`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `GTK_MODULES`
  - `GUAKE_TAB_UUID`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `GDM_LANG`
  - `XDG_DATA_DIRS`
  - `PWD`
  - `PIP_SHIMS_BASE_MODULE`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `GJS_DEBUG_TOPICS`
  - `XDG_SEAT`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/usr/bin/fish`
  - `EDITOR`: `/usr/bin/nano`
  - `LANG`: `ru_RU.UTF-8`
  - `PWD`: `/home/surehand/Документы/programs/latextm`

---------------------------

Contents of `Pipfile` ('/home/surehand/\xd0\x94\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd1\x8b/programs/latextm/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
ipython = "*"

[packages]
pyyaml = "*"
"jinja2" = "*"

[requires]
python_version = "3.5"

```

</details>

**Comment by frostming** [comment] 2018-12-17 13:35
yes, pipenv is not tested well with unicode support on python2.7, it is already noticed and we have plan to improve it.

**Comment by frostming** [comment] 2018-12-18 01:00
Duplicate of #2859

**Closed by frostming** 2018-12-18 01:00 UTC
Labels: duplicate
