### ISSUE TITLE
11.3.1, extra args deps gone away

### ISSUE THREAD

**Issue by item4** [pypa/pipenv#1656] opened 2018-03-10 16:41 UTC
##### Version of pipenv

```
$ pipenv --version
pipenv, version 11.3.1
```

##### Expected result

`$ pipenv install fuzzywuzzy[speedup]` make lock file with `fuzzywuzzy` and `python-levenshtein`.

##### Actual result

there is no `python-levenshtein` in `Pipfile.lock`.

```
$ pipenv lock --verbose
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  fuzzywuzzy[speedup]

Finding the best candidates:
  found candidate fuzzywuzzy[speedup]==0.16.0 (constraint was <any>)

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Warning: Error generating hash for fuzzywuzzy

Updated Pipfile.lock (1ff652)!
```

```
$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "d85f8ebbb6c1b4eaaada70f72c7c1741845fedda70856938e034e6a5d11ff652"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "fuzzywuzzy": {
            "hashes": [
                "sha256:d40c22d2744dff84885b30bbfc07fab7875f641d070374331777a4d1808b8d4e",
                "sha256:ecf490216fb4d76b558a03042ff8f45a8782f17326caca1384d834cbaa2c7e6f"
            ],
            "version": "==0.16.0"
        }
    },
    "develop": {}
}

```

##### Steps to replicate

`$ pipenv install fuzzywuzzy[speedup]`

**Comment by item4** [comment] 2018-03-10 16:52
wait, I will try to make more simple steps to replicate

**Comment by item4** [comment] 2018-03-10 16:56
issue body changed. more simple description

**Comment by techalchemy** [comment] 2018-03-10 17:06
Can't reproduce, please install the latest version (bugfix) of pipenv and retry with `pipenv lock --clear` and see if your lockfile is fixed

**Comment by item4** [comment] 2018-03-10 17:12
@techalchemy encounter another error

I paste full step

```
$ mktmpenv
Using base prefix '/Users/item4/.pyenv/versions/3.6.3'
New python executable in /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/python3.6
Also creating executable in /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/item4/.virtualenvs/tmp-330e80a17f01a4/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
$ pip install pipenv
Collecting pipenv
Requirement already satisfied: setuptools>=36.2.1 in ./lib/python3.6/site-packages (from pipenv)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Using cached virtualenv_clone-0.3.0-py2.py3-none-any.whl
Collecting virtualenv (from pipenv)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Installing collected packages: virtualenv-clone, virtualenv, pipenv
Successfully installed pipenv-11.3.2 virtualenv-15.1.0 virtualenv-clone-0.3.0
$ pipenv install fuzzywuzzy[speedup]
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Creating a Pipfile for this project…
Installing fuzzywuzzy[speedup]…
Collecting fuzzywuzzy[speedup]
  Using cached fuzzywuzzy-0.16.0-py2.py3-none-any.whl
Collecting python-levenshtein>=0.12; extra == "speedup" (from fuzzywuzzy[speedup])
Requirement already satisfied: setuptools in ./lib/python3.6/site-packages (from python-levenshtein>=0.12; extra == "speedup"->fuzzywuzzy[speedup])
Installing collected packages: python-levenshtein, fuzzywuzzy
Successfully installed fuzzywuzzy-0.16.0 python-levenshtein-0.12.0

Adding fuzzywuzzy[speedup] to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
_changed, best_matches = self._resolve_one_round()
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 284, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 206, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/pip/req/req_set.py", line 699, in _prepare_file
    self.requires_python = check_dist_requires_python(dist, absorb=False)
TypeError: check_dist_requires_python() got an unexpected keyword argument 'absorb'
$ ls Pip*
Pipfile
```

**Comment by item4** [comment] 2018-03-10 17:13
```
$ pipenv lock --verbose --clear
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  fuzzywuzzy[speedup]

Finding the best candidates:
  found candidate fuzzywuzzy[speedup]==0.16.0 (constraint was <any>)

Finding secondary dependencies:

INFO:pip.download:File was already downloaded /Users/item4/Library/Caches/pipenv/wheels/fuzzywuzzy-0.16.0-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 398, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 331, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 284, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 206, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/Users/item4/.virtualenvs/tmp-330e80a17f01a4/lib/python3.6/site-packages/pipenv/../pipenv/patched/pip/req/req_set.py", line 699, in _prepare_file
    self.requires_python = check_dist_requires_python(dist, absorb=False)
TypeError: check_dist_requires_python() got an unexpected keyword argument 'absorb'
```

**Comment by techalchemy** [comment] 2018-03-10 17:26
@item4 can you install from master? `pip install -e https://github.com/pypa/pipenv.git@master#egg=pipenv` -- this should be fixed already

**Comment by item4** [comment] 2018-03-10 17:31
@techalchemy Right. It fixed on master branch. Can you close this issue after release current master branch?

**Comment by techalchemy** [comment] 2018-03-10 17:35
@item4 :cake: :tada:

**Closed by techalchemy** 2018-03-10 17:35 UTC
