### ISSUE TITLE
AttributeError: module 'pipenv.vendor.cerberus' has no attribute 'Validator'

### ISSUE THREAD

**Issue by drsasa** [pypa/pipenv#5739] opened 2023-06-16 22:26 UTC
Getting error when update modules.

### Issue description

Python version 3.11.4
When doing pipenv update on linux os with pipenv version's >2023.5.19 getting error.
On windows os there is no error.

### Expected result

No error.

### Actual result

`Running $ pipenv lock then $ pipenv sync.
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/models/base.py", line 33, in validate
    v = VALIDATORS[key]
        ~~~~~~~~~~^^^^^
KeyError: 140086763436672

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/cli/command.py", line 579, in update
    do_update(
  File "/usr/local/lib/python3.11/site-packages/pipenv/routines/update.py", line 69, in do_update
    do_lock(
  File "/usr/local/lib/python3.11/site-packages/pipenv/routines/lock.py", line 122, in do_lock
    lockfile.update({"_meta": project.get_lockfile_meta()})
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 806, in get_lockfile_meta
    "hash": {"sha256": self.calculate_pipfile_hash()},
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 1099, in calculate_pipfile_hash
    p = plette.Pipfile.load(pf)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/pipfiles.py", line 65, in load
    return cls(data)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/models/base.py", line 49, in __init__
    self.validate(data)
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/pipfiles.py", line 44, in validate
    klass.validate(data[key])
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/models/base.py", line 149, in validate
    cls.item_class.validate(d)
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/models/base.py", line 81, in validate
    return validate(cls, data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/plette/models/base.py", line 35, in validate
    v = VALIDATORS[key] = cerberus.Validator(schema, allow_unknown=True)
                          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pipenv.vendor.cerberus' has no attribute 'Validator'`

### Steps to replicate

Under linux os, python version 3.11.4 and pipenv >2023.5.19
command: pipenv update

**Comment by matteius** [comment] 2023-06-17 16:32
This is a duplicate of: https://github.com/pypa/pipenv/issues/5734

Basically we removed cerberus but you still have an empty directory artifact floating around from a prior pipenv install.

**Closed** 2023-08-16 03:08 UTC
Labels: Type: Question :grey_question:
