### ISSUE TITLE
Can't use any pipenv command when there is an argument containing a dash/hyphen "-"

### ISSUE THREAD

**Issue by walterdolce** [pypa/pipenv#3633] opened 2019-03-20 18:56 UTC
Hi, I'm not sure what's happening behind the scenes in my case. The behaviour of pipenv is confusing me a little, though.

I have the following `Dockerfile`:
```
FROM alpine:3.9.2

ENV PIPENV_VERSION=2018.11.26

RUN apk add --update \
        build-base=0.5-r1 \
        curl=7.64.0-r1 \
        bash=4.4.19-r1 \
        python2=2.7.15-r3 \
        ruby=2.5.3-r1 \
        ruby-dev=2.5.3-r1 \
        git=2.20.1-r0 \
        openssh=7.9_p1-r4 \
        tar=1.32-r0 \
        gzip=1.10-r0 \
        ca-certificates=20190108-r0 \
        libressl=2.7.5-r0 \
        libressl-dev=2.7.5-r0 \
        libffi-dev=3.2.1-r6 \
        openssl-dev=1.1.1b-r1 \
        python2-dev=2.7.15-r3
RUN curl -SOL https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py \
    && rm get-pip.py
RUN pip install -Iv pipenv==${PIPENV_VERSION}
```

Then I have the following `Pipenv` file:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "2.7.15"

[packages]
ansible = "==2.7.6"
google-auth = "==1.6.2"
requests = "==2.21.0"
```

When I build the Docker image, then I run the image with:
```
# $PWD is where the Pipenv file is
docker run -v $PWD:/my-folder -ti {{the_image_id}} bash
```

And then, from within the Docker image, I do:
```
export PIPENV_VENV_IN_PROJECT=1
pipenv install
```

And then I do:
```
pipenv run which ansible
```

Then I correctly see:
```
/my-folder/.venv/bin/ansible
```

But when I do:
```
 pipenv run which ansible-playbook
```

Then I receive:
```
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try "pipenv -h" for help.

Error: Invalid value for "--version": 2018.11.26 is not a valid boolean
```

Why is that?

Is the `-` in `ansible-playbook` breaking pipenv?

Note that if I just issue `pipenv` I get the same. Whereby normally pipenv would come back with the general usage message showing all commands..

I'm not sure how I should go about debugging this. Any help would be much appreciated.
Thank you.

**Comment by walterdolce** [comment] 2019-03-20 18:57
I think the `-` when passed to `pipenv run` is *actually* breaking pipenv. See below.

```
# From within the container
bash-4.4# pipenv run echo hello
hello
bash-4.4# pipenv run echo hello-world
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try "pipenv -h" for help.

Error: Invalid value for "--version": 2018.11.26 is not a valid boolean
```

**Comment by walterdolce** [comment] 2019-03-21 13:49
Looks like this is the offending line: https://github.com/pypa/pipenv/blob/master/pipenv/cli/command.py#L57

Without it, the problem does not occur with the setup above.

**Comment by walterdolce** [comment] 2019-03-21 14:10
I have a fix ready if that line is safe to remove: https://github.com/pypa/pipenv/compare/master...walterdolce:feature/remove-version-option-breaking-on-alpine?expand=1

**Comment by frostming** [comment] 2019-03-22 01:23
It is weird that I can't replicate this. Version option is required that a custom prog name is provided.

**Comment by walterdolce** [comment] 2019-03-29 13:32
@frostming what more information do you need?

**Comment by frostming** [comment] 2019-03-30 13:06
@walterdolce No your example is quite complete and I can replicate with the Dockerfile.

Just can't figure out what is broken because even `pipenv --rm`/`pipenv --venv` can't work.

**Comment by walterdolce** [comment] 2019-03-30 14:23
@frostming oh I see. Let me know if I can be of any help!

FWIW, I the above was happening on both macOS (my laptop) and on CircleCI

**Comment by frostming** [comment] 2019-03-30 14:26
@walterdolce Oh, I got it! Just don't use `PIPENV_VERSION` as the env name, because it is respected by `click` as the option value. Change it to another name will do the trick.

This is not a bug, close it now. Thanks.

**Closed by frostming** 2019-03-30 14:26 UTC

**Comment by walterdolce** [comment] 2019-03-30 14:29
No way! Thanks for this!

**Comment by Scherlac** [comment] 2021-12-22 19:03
@frostming : It would nice to be informed like as follows:

> Error: Invalid value for '--version' or "env:PIPENV_VERSION': '2021.11.23' is not a valid boolean.
