### ISSUE TITLE
pipenv install --pypi-mirror suppress by -i and --extra-index-url

### ISSUE THREAD

**Issue by mlouielu** [pypa/pipenv#2637] opened 2018-07-24 05:52 UTC
##### Issue description

pipenv install `--pypi-mirror` suppress by `-i` and `--extra-index-url`

##### Expected result

Looking in indexes: https://foo, https://bar, https://pypi.python.org/simple

##### Actual result

```
➜  p pipenv install ppppp -i https://foo.com --extra-index-url https://bar.com --pypi-mirror https://pypi.python.org/simple 
Installing ppppp…
Looking in indexes: https://foo.com, https://bar.com
Collecting ppppp
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

```
$ pipenv install ppppp -i https://foo.com --extra-index-url https://bar.com --pypi-mirror https://pypi.python.org/simple 
```

**Comment by techalchemy** [comment] 2018-07-24 05:54
Closing as a duplicate of #2494

**Closed by techalchemy** 2018-07-24 05:54 UTC
