### ISSUE TITLE
Local package with Git dependency is not installed as Git dependency

### ISSUE THREAD

**Issue by vlotorev** [pypa/pipenv#3646] opened 2019-03-24 21:32 UTC
### Issue description

Installing local package that has requirement with PEP 508 Git URL fetches and locks that requirement to version from PyPI not from the specified URL.

### Expected result

`Pipfile.lock` would contain git SHA commit for `python-ivi` package.
Installing package via `pip install package-with-git-sha-dep` properly fetches specified Git commit.

### Actual result

`Pipfile.lock` doesn't contain git SHA, `python-ivi` package installed from PyPi.

### Steps to replicate

Clear pipenv environment if existed, `pipenv --rm; rm Pipfile*`.

Prepare local package `package-with-git-sha-dep`. Note it has `python-ivi` specified to Git repository with SHA:
```mkdir package-with-git-sha-dep && cd package-with-git-sha-dep
cat > setup.py << eof
import setuptools
setuptools.setup(
    name='package-with-git-sha-dep',
    version='0.0.2',
    python_requires='~=2.7',
    install_requires=[
        'python-ivi@git+https://github.com/python-ivi/python-ivi.git@cfa45ceade0758debe4bc24ba4c8195222cad1e2',
    ]
)
eof
cd -
```

Install created package via `pipenv install -e ./package-with-git-sha-dep` and look at generated `Pipfile.lock` - it doesn't contain information about Git commit SHA, but installed v0.14.9 from PyPi.

-------------------------------------------------------------------------------
`pip --version` -> `pip 19.0.3 from /home/vlotorev/.local/lib/python2.7/site-packages/pip (python 2.7)`
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/vlotorev/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.4.5`: `/usr/bin/python3.4`
  - `2.7.5`: `/usr/bin/python2.7`
  - `3.6.6`: `/usr/bin/python3.6`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `3.4.5`: `/usr/bin/python3.4m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-327.13.1.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Mar 31 16:04:38 UTC 2016',
 'python_full_version': '2.7.5',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `http_proxy`
  - `NCURSES_NO_UTF8_ACS`
  - `LESSOPEN`
  - `MODULESHOME`
  - `SSH_CLIENT`
  - `CVS_RSH`
  - `LOGNAME`
  - `USER`
  - `QTDIR`
  - `PATH`
  - `PS1`
  - `LOADEDMODULES`
  - `LANG`
  - `QTLIB`
  - `TERM`
  - `SHELL`
  - `QTINC`
  - `HISTSIZE`
  - `https_proxy`
  - `QT_PLUGIN_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `HOME`
  - `HISTFILESIZE`
  - `no_proxy`
  - `XDG_RUNTIME_DIR`
  - `INFOPATH`
  - `ftp_proxy`
  - `KRB5CCNAME`
  - `PYTHONDONTWRITEBYTECODE`
  - `BR2_PRIMARY_SITE`
  - `QT_GRAPHICSSYSTEM_CHECKED`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `_`
  - `MODULEPATH`
  - `KDEDIRS`
  - `LS_COLORS`
  - `SSH_TTY`
  - `OLDPWD`
  - `HOSTNAME`
  - `SSH_CONNECTION`
  - `CVSROOT`
  - `HISTCONTROL`
  - `SHLVL`
  - `PWD`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `MAIL`
  - `_LMFILES_`
  - `XDG_DATA_DIRS`
  - `BASH_FUNC_module()`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/vlotorev/bin:/home/vlotorev/.local/bin:/home/vlotorev/bin:/home/vlotorev/.local/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/vlotorev/projects/mylib`

---------------------------

Contents of `Pipfile` ('/home/vlotorev/projects/mylib/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
package-with-git-sha-dep = {path = "./package-with-git-sha-dep",editable = true}

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/home/vlotorev/projects/mylib/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "9bf37baf6ce16026b30c837ecd0d55c66145a756ab8a6660b0a2f66d4d24c492"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "package-with-git-sha-dep": {
            "editable": true,
            "path": "./package-with-git-sha-dep"
        },
        "python-ivi": {
            "hashes": [
                "sha256:358117dd2b1656a0c3aa222bd4346cde36e3d040da92635c899994e012d6f80f"
            ],
            "version": "==0.14.9"
        }
    },
    "develop": {}
}

```
</details>

**Comment by vlotorev** [comment] 2019-03-24 21:35
Probably this is a follow-up of #3058.

**Comment by ryancausey** [comment] 2019-04-28 23:24
I'm having this same issue. The work around I currently have is to do the following:
```
> pipenv shell
> pip uninstall vcs-pinned-package
> pip install -e /path/to/package-with-git-sha-or-branch-dep
```

**Comment by techalchemy** [comment] 2019-05-20 06:01
This is a duplicate of #3058 which is only recently actually fixed, I just merged that fix into master.  This is now fully operational in the next release -- sorry for the trouble!

**Closed by techalchemy** 2019-05-20 06:01 UTC
Labels: Type: Duplicate

**Comment by oteph** [comment] 2019-12-19 17:10
@techalchemy whats the plan for the next pipenv release? It's been more then a year now and it would be great to get a new version based on master with all the fixes and improvements like this one
