### ISSUE TITLE
pipenv lock does not respect dev constraints

### ISSUE THREAD

**Issue by insysion** [pypa/pipenv#3045] opened 2018-10-16 10:16 UTC
### Issue description

The same package (in this example, `pytest`) is specified with different constraints between default (`pytest==3.6.4`)  and dev packages (`pytest==3.8.2`).

### Expected result

Locking to fail due to the inability to resolve `pytest`

### Actual result

The lock succeeds with `pytest==3.8.2` in both the `default` and `dev` sections of the `Pipfile.lock`

```
$ pipenv lock --verbose
Locking [dev-packages] dependencies…
using sources: [{'name': 'pypi', 'url': 'https://pypi.org/simple', 'verify_ssl': True}]
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  pytest==3.6.4

Finding the best candidates:
  found candidate pytest==3.6.4 (constraint was ==3.6.4)

Finding secondary dependencies:
  pytest==3.6.4             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pluggy<0.8,>=0.5, py>=1.5.0, setuptools, six>=1.10.0

New dependencies found in this round:
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['pluggy', '<0.8,>=0.5', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['six', '>=1.10.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  atomicwrites>=1.0
  attrs>=17.4.0
  more-itertools>=4.0.0
  pluggy<0.8,>=0.5
  py>=1.5.0
  pytest==3.6.4
  six>=1.10.0

Finding the best candidates:
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate pluggy==0.7.1 (constraint was >=0.5,<0.8)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pytest==3.6.4 (constraint was ==3.6.4)
  found candidate six==1.11.0 (constraint was >=1.10.0)

Finding secondary dependencies:
  attrs==18.2.0             requires -
  py==1.7.0                 requires -
  pluggy==0.7.1             requires -
  atomicwrites==1.2.1       requires -
  pytest==3.6.4             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pluggy<0.8,>=0.5, py>=1.5.0, setuptools, six>=1.10.0
  more-itertools==4.3.0     requires six<2.0.0,>=1.0.0
  six==1.11.0               requires -

New dependencies found in this round:
  adding ['six', '<2.0.0,>=1.0.0,>=1.10.0', '[]']
Removed dependencies in this round:
  removing ['six', '>=1.10.0', '[]']
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  atomicwrites>=1.0
  attrs>=17.4.0
  more-itertools>=4.0.0
  pluggy<0.8,>=0.5
  py>=1.5.0
  pytest==3.6.4
  six<2.0.0,>=1.0.0,>=1.10.0

Finding the best candidates:
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate pluggy==0.7.1 (constraint was >=0.5,<0.8)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pytest==3.6.4 (constraint was ==3.6.4)
  found candidate six==1.11.0 (constraint was >=1.0.0,>=1.10.0,<2.0.0)

Finding secondary dependencies:
  attrs==18.2.0             requires -
  atomicwrites==1.2.1       requires -
  py==1.7.0                 requires -
  more-itertools==4.3.0     requires six<2.0.0,>=1.0.0
  pytest==3.6.4             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pluggy<0.8,>=0.5, py>=1.5.0, setuptools, six>=1.10.0
  pluggy==0.7.1             requires -
  six==1.11.0               requires -
------------------------------------------------------------
Result of round 3: stable, done

Locking [packages] dependencies…
using sources: [{'name': 'pypi', 'verify_ssl': True, 'url': 'https://pypi.org/simple'}]
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  pytest==3.8.2

Finding the best candidates:
  found candidate pytest==3.8.2 (constraint was ==3.8.2)

Finding secondary dependencies:
  pytest==3.8.2             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pathlib2>=2.2.0; python_version < "3.6", pluggy>=0.7, py>=1.5.0, setuptools, six>=1.10.0

New dependencies found in this round:
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['pathlib2', '>=2.2.0', '[]']
  adding ['pluggy', '>=0.7', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['six', '>=1.10.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  atomicwrites>=1.0
  attrs>=17.4.0
  more-itertools>=4.0.0
  pathlib2>=2.2.0
  pluggy>=0.7
  py>=1.5.0
  pytest==3.8.2
  six>=1.10.0

Finding the best candidates:
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate pathlib2==2.3.2 (constraint was >=2.2.0)
  found candidate pluggy==0.7.1 (constraint was >=0.7)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pytest==3.8.2 (constraint was ==3.8.2)
  found candidate six==1.11.0 (constraint was >=1.10.0)

Finding secondary dependencies:
  attrs==18.2.0             requires -
  six==1.11.0               requires -
  pluggy==0.7.1             requires -
  atomicwrites==1.2.1       requires -
  more-itertools==4.3.0     requires six<2.0.0,>=1.0.0
  pytest==3.8.2             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pathlib2>=2.2.0; python_version < "3.6", pluggy>=0.7, py>=1.5.0, setuptools, six>=1.10.0
  pathlib2==2.3.2           requires six
  py==1.7.0                 requires -

New dependencies found in this round:
  adding ['six', '<2.0.0,>=1.0.0,>=1.10.0', '[]']
Removed dependencies in this round:
  removing ['six', '>=1.10.0', '[]']
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  atomicwrites>=1.0
  attrs>=17.4.0
  more-itertools>=4.0.0
  pathlib2>=2.2.0
  pluggy>=0.7
  py>=1.5.0
  pytest==3.8.2
  six<2.0.0,>=1.0.0,>=1.10.0

Finding the best candidates:
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate pathlib2==2.3.2 (constraint was >=2.2.0)
  found candidate pluggy==0.7.1 (constraint was >=0.7)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pytest==3.8.2 (constraint was ==3.8.2)
  found candidate six==1.11.0 (constraint was >=1.0.0,>=1.10.0,<2.0.0)

Finding secondary dependencies:
  pytest==3.8.2             requires atomicwrites>=1.0, attrs>=17.4.0, more-itertools>=4.0.0, pathlib2>=2.2.0; python_version < "3.6", pluggy>=0.7, py>=1.5.0, setuptools, six>=1.10.0
  pathlib2==2.3.2           requires six
  pluggy==0.7.1             requires -
  six==1.11.0               requires -
  py==1.7.0                 requires -
  attrs==18.2.0             requires -
  more-itertools==4.3.0     requires six<2.0.0,>=1.0.0
  atomicwrites==1.2.1       requires -
------------------------------------------------------------
Result of round 3: stable, done

Updated Pipfile.lock (d06084)!
```

### Steps to replicate

`$ pipenv lock -d` or `$ pipenv lock`. (Should they produce different results?)

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'/home/sandeep/.local/lib/python3.5/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `2.7.12`: `/usr/bin/python2.7`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `3.5.2`: `/usr/bin/python3.5`
  - `3.5.2`: `/home/sandeep/.local/share/virtualenvs/pipenv_playground-oPVKHwn5/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-36-generic',
 'platform_system': 'Linux',
 'platform_version': '#39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LOGNAME`
  - `XDG_SEAT_PATH`
  - `DISPLAY`
  - `USER`
  - `WINDOWID`
  - `PS1`
  - `PROWLER_IO_HOME`
  - `GTK_MODULES`
  - `DEFAULTS_PATH`
  - `UPSTART_JOB`
  - `COMPIZ_BIN_PATH`
  - `GTK_IM_MODULE`
  - `QT_ACCESSIBILITY`
  - `PIPENV_ACTIVE`
  - `IM_CONFIG_PHASE`
  - `INSTANCE`
  - `MANDATORY_PATH`
  - `UNITY_DEFAULT_PROFILE`
  - `DESKTOP_SESSION`
  - `VTE_VERSION`
  - `LANGUAGE`
  - `XDG_SESSION_DESKTOP`
  - `LD_LIBRARY_PATH`
  - `QT4_IM_MODULE`
  - `SSH_AUTH_SOCK`
  - `UPSTART_SESSION`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `XDG_CONFIG_DIRS`
  - `QT_QPA_PLATFORMTHEME`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_SESSION_ID`
  - `HOME`
  - `PROMPT_COMMAND`
  - `SHLVL`
  - `QT_IM_MODULE`
  - `XDG_SESSION_PATH`
  - `PIP_REQUIRE_VIRTUALENV`
  - `LESSCLOSE`
  - `PIP_PYTHON_PATH`
  - `GDM_LANG`
  - `XDG_SESSION_TYPE`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XMODIFIERS`
  - `SESSION`
  - `VIRTUAL_ENV`
  - `XDG_VTNR`
  - `GNOME_KEYRING_CONTROL`
  - `GPG_AGENT_INFO`
  - `_`
  - `XDG_DATA_DIRS`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_KEYRING_PID`
  - `GDMSESSION`
  - `XDG_SEAT`
  - `LESSOPEN`
  - `TERM`
  - `CLUTTER_IM_MODULE`
  - `XAUTHORITY`
  - `COMPIZ_CONFIG_PROFILE`
  - `PWD`
  - `SESSIONTYPE`
  - `PIP_SHIMS_BASE_MODULE`
  - `UPSTART_INSTANCE`
  - `LANG`
  - `XDG_GREETER_DATA_DIR`
  - `SHELL`
  - `GTK2_MODULES`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `XDG_CURRENT_DESKTOP`
  - `UPSTART_EVENTS`
  - `JOB`
  - `UNITY_HAS_3D_SUPPORT`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/sandeep/.local/share/virtualenvs/pipenv_playground-oPVKHwn5/bin:/home/sandeep/bin:/home/sandeep/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/sandeep/pipenv_playground`
  - `VIRTUAL_ENV`: `/home/sandeep/.local/share/virtualenvs/pipenv_playground-oPVKHwn5`

---------------------------

Contents of `Pipfile` ('/home/sandeep/pipenv_playground/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
name = "pypi"
verify_ssl = true

[requires]
python_version = "3.5"

[dev-packages]
pytest = "==3.6.4"

[packages]
pytest = "==3.8.2"

```

Contents of `Pipfile.lock` ('/home/sandeep/pipenv_playground/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "486a40d2fd93cecb2e8672db6d7c76370ea13be1e606608a4c6d2630ead06084"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "atomicwrites": {
            "hashes": [
                "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
                "sha256:ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee"
            ],
            "version": "==1.2.1"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
                "sha256:c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e",
                "sha256:fcbfeaea0be121980e15bc97b3817b5202ca73d0eae185b4550cbfce2a3ebb3d"
            ],
            "version": "==4.3.0"
        },
        "pathlib2": {
            "hashes": [
                "sha256:8eb170f8d0d61825e09a95b38be068299ddeda82f35e96c3301a8a5e7604cb83",
                "sha256:d1aa2a11ba7b8f7b21ab852b1fb5afb277e1bb99d5dfc663380b5015c0d80c5a"
            ],
            "markers": "python_version < '3.6'",
            "version": "==2.3.2"
        },
        "pluggy": {
            "hashes": [
                "sha256:6e3836e39f4d36ae72840833db137f7b7d35105079aee6ec4a62d9f80d594dd1",
                "sha256:95eb8364a4708392bae89035f45341871286a333f749c3141c20573d2b3876e1"
            ],
            "version": "==0.7.1"
        },
        "py": {
            "hashes": [
                "sha256:bf92637198836372b520efcba9e020c330123be8ce527e535d185ed4b6f45694",
                "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6"
            ],
            "version": "==1.7.0"
        },
        "pytest": {
            "hashes": [
                "sha256:7e258ee50338f4e46957f9e09a0f10fb1c2d05493fa901d113a8dafd0790de4e",
                "sha256:9332147e9af2dcf46cd7ceb14d5acadb6564744ddff1fe8c17f0ce60ece7d9a2"
            ],
            "index": "pypi",
            "version": "==3.8.2"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    },
    "develop": {
        "atomicwrites": {
            "hashes": [
                "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
                "sha256:ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee"
            ],
            "version": "==1.2.1"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
                "sha256:c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e",
                "sha256:fcbfeaea0be121980e15bc97b3817b5202ca73d0eae185b4550cbfce2a3ebb3d"
            ],
            "version": "==4.3.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:6e3836e39f4d36ae72840833db137f7b7d35105079aee6ec4a62d9f80d594dd1",
                "sha256:95eb8364a4708392bae89035f45341871286a333f749c3141c20573d2b3876e1"
            ],
            "version": "==0.7.1"
        },
        "py": {
            "hashes": [
                "sha256:bf92637198836372b520efcba9e020c330123be8ce527e535d185ed4b6f45694",
                "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6"
            ],
            "version": "==1.7.0"
        },
        "pytest": {
            "hashes": [
                "sha256:7e258ee50338f4e46957f9e09a0f10fb1c2d05493fa901d113a8dafd0790de4e",
                "sha256:9332147e9af2dcf46cd7ceb14d5acadb6564744ddff1fe8c17f0ce60ece7d9a2"
            ],
            "index": "pypi",
            "version": "==3.8.2"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    }
}

```
</details>

**Comment by techalchemy** [comment] 2018-10-20 01:34
Hm I have been wondering about this myself lately, I think we need to make a behavioral change in our internals.

@uranusjr I think I need to run this by kenneth also, but I think we should take the approach we took in Passa and lock both separately but merge them during installation rather than overriding at lock time. Thoughts? I think the implementation change isn't as bad now that the code is a little less messy

**Comment by techalchemy** [comment] 2018-10-22 16:51
Hmm this is a duplicate of #2330, closing this in favor of that one for now

**Closed by techalchemy** 2018-10-22 16:51 UTC
Labels: behavior change, dependency resolution

**Comment by uranusjr** [comment] 2018-10-24 04:09
I think merging is the right approach here, but that would need some work (unless we reuse some code from Passa). Incidentally pip also has an issue somewhat similar in spirit (regarding `install_requires` and `extras_require` entries having different specifiers) pypa/pip#5894

**Comment by techalchemy** [comment] 2018-10-29 06:49
I actually wrote a fix already in requirementslib in sarugaku/requirementslib#86 by porting a dictionary merge function from boltons and using it to expose `requirementslib.models.lockfile.Lockfile.get_deps(dev,only)` and if you specify `True, False` it will recursively merge requirements from the lockfile info dev requirements
