### ISSUE TITLE
pipenv hangs when authentication is required

### ISSUE THREAD

**Issue by thedrow** [pypa/pipenv#3399] opened 2018-12-19 13:29 UTC
### Issue description

When credentials are required to a private repository but not provided, pipenv simply hangs instead of giving up.

### Expected result

pipenv hangs instead of quitting.

### Actual result

```
pipenv install --dev pytest-runner pyyaml nose pytest pytest-cov pytest-mock pyfakefs coverage boto3 --verbose
Installing pytest-runner…
⠋ Installing...Installing 'pytest-runner'
$ ['/home/omer/.local/share/virtualenvs/foo-3GWjSLzv/bin/pip', 'install', '--verbose', '--upgrade', 'pytest-runner', '-i', 'https://pypi.org/simple', '--extra-index-url', 'https://$CLIENT_ID@packagecloud.io/foo/bar/pypi/simple']
✘ 
```

### Steps to replicate

Create a private repository which requires credentials.
Add the private repository as a source.
Don't provide them while running `pipenv install`.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26/libexec/bin/python3.7'`

Python installations found:

  - `3.7.1`: `/home/linuxbrew/.linuxbrew/bin/python3.7`
  - `3.7.1`: `/home/linuxbrew/.linuxbrew/bin/python3.7m`
  - `3.7.0`: `/home/omer/.pyenv/versions/3.7.0/bin/python`
  - `3.7.0`: `/home/omer/.pyenv/versions/3.7.0/bin/python3.7m`
  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `3.5.3`: `/home/omer/.pyenv/versions/pypy3.5-6.0.0/bin/python`
  - `2.7.15`: `/home/linuxbrew/.linuxbrew/bin/python2`
  - `2.7.15rc1`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-42-generic',
 'platform_system': 'Linux',
 'platform_version': '#45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `CLUTTER_IM_MODULE`
  - `LS_COLORS`
  - `LD_LIBRARY_PATH`
  - `_fzf_orig_completion_cat`
  - `LC_MEASUREMENT`
  - `LESSCLOSE`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `XDG_MENU_PREFIX`
  - `_`
  - `LANG`
  - `DISPLAY`
  - `OLDPWD`
  - `GNOME_SHELL_SESSION_MODE`
  - `_fzf_orig_completion_uniq`
  - `_fzf_orig_completion_cd`
  - `_fzf_orig_completion_cp`
  - `COLORTERM`
  - `USERNAME`
  - `_fzf_orig_completion_sort`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `_fzf_orig_completion_grep`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `RBENV_SHELL`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `GNOME_TERMINAL_SCREEN`
  - `_fzf_orig_completion_less`
  - `_fzf_orig_completion_telnet`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `_fzf_orig_completion_head`
  - `QT_ACCESSIBILITY`
  - `LIBVIRT_DEFAULT_URI`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `_fzf_orig_completion_awk`
  - `LC_ADDRESS`
  - `_fzf_orig_completion_diff`
  - `_fzf_orig_completion_mv`
  - `GJS_DEBUG_OUTPUT`
  - `LC_NUMERIC`
  - `_fzf_orig_completion_ftp`
  - `_fzf_orig_completion_tee`
  - `GTK_MODULES`
  - `PAPERSIZE`
  - `WINDOWPATH`
  - `SHELL`
  - `VTE_VERSION`
  - `TERM`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `_fzf_orig_completion_tail`
  - `GNOME_TERMINAL_SERVICE`
  - `XDG_SEAT`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LANGUAGE`
  - `MANPATH`
  - `_fzf_orig_completion_du`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `_fzf_orig_completion_pushd`
  - `XDG_CONFIG_DIRS`
  - `LC_IDENTIFICATION`
  - `_fzf_orig_completion_ls`
  - `_fzf_orig_completion_ld`
  - `INFOPATH`
  - `_fzf_orig_completion_sed`
  - `_fzf_orig_completion_ln`
  - `GJS_DEBUG_TOPICS`
  - `_fzf_orig_completion_rmdir`
  - `_fzf_orig_completion_wc`
  - `SESSION_MANAGER`
  - `_fzf_orig_completion_rm`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26/libexec/tools:/home/omer/.rbenv/shims:/home/omer/.pyenv/shims:/home/omer/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/omer/go/bin:/home/omer/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/omer/.dotnet/tools:/home/linuxbrew/.linuxbrew/opt/fzf/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/omer/Documents/Projects/foo`

---------------------------

Contents of `Pipfile` ('/home/omer/Documents/Projects/foo/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "packagecloud"
url = "https://$CLIENT_ID@packagecloud.io/foo/bar/pypi/simple"
verify_ssl = true

[dev-packages]
pytest-runner = "*"
pyyaml = "*"
nose = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pyfakefs = "*"
coverage = "*"
boto3 = "*"

[packages]
foo = {editable = true,path = "."}

```

Contents of `Pipfile.lock` ('/home/omer/Documents/Projects/foo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "b8d5999492bb5e0baef84fd92de2abf845c17cbdfed70c67f1c77c965a956393"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "packagecloud",
                "url": "https://$CLIENT_ID@packagecloud.io/foo/bar/pypi/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "analytics-python": {
            "hashes": [
                "sha256:69d88b2d3e2c350e6803487a1a802e0fd111e86665d4c9b16c3c6f5fbc6c445f",
                "sha256:f3d1ca27cb277da67c10d71a5c9c593d2a9ec99109e31409ab771b44821a86bf"
            ],
            "version": "==1.2.9"
        },
        "aws-parsecf-enterprise": {
            "hashes": [
                "sha256:515c453b34985650c0ce212d7e5750cf8e63613ff670fe7e5d1e28f2770ad90d"
            ],
            "version": "==1.0.1"
        },
        "boto3": {
            "hashes": [
                "sha256:09d1ae44f15659e425b7526de452bfa3840e12dd3e08dd0b067a78f619e997b5",
                "sha256:88233f9bdc1e6ee58c9489cef6c573bf7e660acfcc1597bc3ff765a065e1a0f0"
            ],
            "version": "==1.9.68"
        },
        "botocore": {
            "hashes": [
                "sha256:7fd7954f19a49c9794bed696c801f3dfd7bdde306d17c9bb9fb0c069e6b42e5a",
                "sha256:f6dc444ca92f33e1a3129e39b2c6d9941e4931fda3f3aff02fe82290013ef2d0"
            ],
            "version": "==1.12.68"
        },
        "cached-property": {
            "hashes": [
                "sha256:3a026f1a54135677e7da5ce819b0c690f156f37976f3e30c5430740725203d7f",
                "sha256:9217a59f14a5682da7c4b8829deadbfc194ac22e9908ccf7c8820234e80a1504"
            ],
            "version": "==1.5.1"
        },
        "certifi": {
            "hashes": [
                "sha256:47f9c83ef4c0c621eaef743f133f09fa8a74a9b75f037e8624f83bd1b6626cb7",
                "sha256:993f830721089fef441cdfeb4b2c8c9df86f0c63239f06bd025a76a7daddb033"
            ],
            "version": "==2018.11.29"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "colorama": {
            "hashes": [
                "sha256:05eed71e2e327246ad6b38c540c4a3117230b19679b875190486ddd2d721422d",
                "sha256:f8ac84de7840f5b9c4e3347b3c1eaa50f7e49c2b07596221daec5edaabbd7c48"
            ],
            "version": "==0.4.1"
        },
        "docutils": {
            "hashes": [
                "sha256:02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6",
                "sha256:51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274",
                "sha256:7a4bd47eaf6596e1295ecb11361139febe29b084a87bf005bf899f9a42edc3c6"
            ],
            "version": "==0.14"
        },
        "idna": {
            "hashes": [
                "sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407",
                "sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c"
            ],
            "version": "==2.8"
        },
        "jmespath": {
            "hashes": [
                "sha256:6a81d4c9aa62caf061cb517b4d9ad1dd300374cd4706997aff9cd6aedd61fc64",
                "sha256:f11b4461f425740a1d908e9a3f7365c3d2e569f6ca68a2ff8bc5bcd9676edd63"
            ],
            "version": "==0.9.3"
        },
        "foo": {
            "editable": true,
            "path": "."
        },
        "python-dateutil": {
            "hashes": [
                "sha256:891c38b2a02f5bb1be3e4793866c8df49c7d19baabf9c1bad62547e0b4866aca",
                "sha256:95511bae634d69bc7329ba55e646499a842bc4ec342ad54a8cdb65645a0aad3c"
            ],
            "markers": "python_version >= '2.7'",
            "version": "==2.6.1"
        },
        "pyyaml": {
            "hashes": [
                "sha256:3d7da3009c0f3e783b2c873687652d83b1bbfd5c88e9813fb7e5b03c0dd3108b",
                "sha256:3ef3092145e9b70e3ddd2c7ad59bdd0252a94dfe3949721633e41344de00a6bf",
                "sha256:40c71b8e076d0550b2e6380bada1f1cd1017b882f7e16f09a65be98e017f211a",
                "sha256:558dd60b890ba8fd982e05941927a3911dc409a63dcb8b634feaa0cda69330d3",
                "sha256:a7c28b45d9f99102fa092bb213aa12e0aaf9a6a1f5e395d36166639c1f96c3a1",
                "sha256:aa7dd4a6a427aed7df6fb7f08a580d68d9b118d90310374716ae90b710280af1",
                "sha256:bc558586e6045763782014934bfaf39d48b8ae85a2713117d16c39864085c613",
                "sha256:d46d7982b62e0729ad0175a9bc7e10a566fc07b224d2c79fafb5e032727eaa04",
                "sha256:d5eef459e30b09f5a098b9cea68bebfeb268697f78d647bd255a085371ac7f3f",
                "sha256:e01d3203230e1786cd91ccfdc8f8454c8069c91bee3962ad93b87a4b2860f537",
                "sha256:e170a9e6fcfd19021dd29845af83bb79236068bf5fd4df3327c1be18182b2531"
            ],
            "version": "==3.13"
        },
        "requests": {
            "hashes": [
                "sha256:502a824f31acdacb3a35b6690b5fbf0bc41d63a24a45c4004352b0242707598e",
                "sha256:7bf2a778576d825600030a110f3c0e3e8edc51dfaafe1c146e39a2027784957b"
            ],
            "version": "==2.21.0"
        },
        "s3transfer": {
            "hashes": [
                "sha256:90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1",
                "sha256:c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f"
            ],
            "version": "==0.1.13"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39",
                "sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"
            ],
            "markers": "python_version >= '3.4'",
            "version": "==1.24.1"
        }
    },
    "develop": {
        "atomicwrites": {
            "hashes": [
                "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
                "sha256:ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee"
            ],
            "version": "==1.2.1"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "boto3": {
            "hashes": [
                "sha256:09d1ae44f15659e425b7526de452bfa3840e12dd3e08dd0b067a78f619e997b5",
                "sha256:88233f9bdc1e6ee58c9489cef6c573bf7e660acfcc1597bc3ff765a065e1a0f0"
            ],
            "version": "==1.9.68"
        },
        "botocore": {
            "hashes": [
                "sha256:7fd7954f19a49c9794bed696c801f3dfd7bdde306d17c9bb9fb0c069e6b42e5a",
                "sha256:f6dc444ca92f33e1a3129e39b2c6d9941e4931fda3f3aff02fe82290013ef2d0"
            ],
            "version": "==1.12.68"
        },
        "coverage": {
            "hashes": [
                "sha256:09e47c529ff77bf042ecfe858fb55c3e3eb97aac2c87f0349ab5a7efd6b3939f",
                "sha256:0a1f9b0eb3aa15c990c328535655847b3420231af299386cfe5efc98f9c250fe",
                "sha256:0cc941b37b8c2ececfed341444a456912e740ecf515d560de58b9a76562d966d",
                "sha256:10e8af18d1315de936d67775d3a814cc81d0747a1a0312d84e27ae5610e313b0",
                "sha256:1b4276550b86caa60606bd3572b52769860a81a70754a54acc8ba789ce74d607",
                "sha256:1e8a2627c48266c7b813975335cfdea58c706fe36f607c97d9392e61502dc79d",
                "sha256:2b224052bfd801beb7478b03e8a66f3f25ea56ea488922e98903914ac9ac930b",
                "sha256:447c450a093766744ab53bf1e7063ec82866f27bcb4f4c907da25ad293bba7e3",
                "sha256:46101fc20c6f6568561cdd15a54018bb42980954b79aa46da8ae6f008066a30e",
                "sha256:4710dc676bb4b779c4361b54eb308bc84d64a2fa3d78e5f7228921eccce5d815",
                "sha256:510986f9a280cd05189b42eee2b69fecdf5bf9651d4cd315ea21d24a964a3c36",
                "sha256:5535dda5739257effef56e49a1c51c71f1d37a6e5607bb25a5eee507c59580d1",
                "sha256:5a7524042014642b39b1fcae85fb37556c200e64ec90824ae9ecf7b667ccfc14",
                "sha256:5f55028169ef85e1fa8e4b8b1b91c0b3b0fa3297c4fb22990d46ff01d22c2d6c",
                "sha256:6694d5573e7790a0e8d3d177d7a416ca5f5c150742ee703f3c18df76260de794",
                "sha256:6831e1ac20ac52634da606b658b0b2712d26984999c9d93f0c6e59fe62ca741b",
                "sha256:77f0d9fa5e10d03aa4528436e33423bfa3718b86c646615f04616294c935f840",
                "sha256:828ad813c7cdc2e71dcf141912c685bfe4b548c0e6d9540db6418b807c345ddd",
                "sha256:85a06c61598b14b015d4df233d249cd5abfa61084ef5b9f64a48e997fd829a82",
                "sha256:8cb4febad0f0b26c6f62e1628f2053954ad2c555d67660f28dfb1b0496711952",
                "sha256:a5c58664b23b248b16b96253880b2868fb34358911400a7ba39d7f6399935389",
                "sha256:aaa0f296e503cda4bc07566f592cd7a28779d433f3a23c48082af425d6d5a78f",
                "sha256:ab235d9fe64833f12d1334d29b558aacedfbca2356dfb9691f2d0d38a8a7bfb4",
                "sha256:b3b0c8f660fae65eac74fbf003f3103769b90012ae7a460863010539bb7a80da",
                "sha256:bab8e6d510d2ea0f1d14f12642e3f35cefa47a9b2e4c7cea1852b52bc9c49647",
                "sha256:c45297bbdbc8bb79b02cf41417d63352b70bcb76f1bbb1ee7d47b3e89e42f95d",
                "sha256:d19bca47c8a01b92640c614a9147b081a1974f69168ecd494687c827109e8f42",
                "sha256:d64b4340a0c488a9e79b66ec9f9d77d02b99b772c8b8afd46c1294c1d39ca478",
                "sha256:da969da069a82bbb5300b59161d8d7c8d423bc4ccd3b410a9b4d8932aeefc14b",
                "sha256:ed02c7539705696ecb7dc9d476d861f3904a8d2b7e894bd418994920935d36bb",
                "sha256:ee5b8abc35b549012e03a7b1e86c09491457dba6c94112a2482b18589cc2bdb9"
            ],
            "index": "pypi",
            "version": "==4.5.2"
        },
        "docutils": {
            "hashes": [
                "sha256:02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6",
                "sha256:51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274",
                "sha256:7a4bd47eaf6596e1295ecb11361139febe29b084a87bf005bf899f9a42edc3c6"
            ],
            "version": "==0.14"
        },
        "jmespath": {
            "hashes": [
                "sha256:6a81d4c9aa62caf061cb517b4d9ad1dd300374cd4706997aff9cd6aedd61fc64",
                "sha256:f11b4461f425740a1d908e9a3f7365c3d2e569f6ca68a2ff8bc5bcd9676edd63"
            ],
            "version": "==0.9.3"
        },
        "more-itertools": {
            "hashes": [
                "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
                "sha256:c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e",
                "sha256:fcbfeaea0be121980e15bc97b3817b5202ca73d0eae185b4550cbfce2a3ebb3d"
            ],
            "version": "==4.3.0"
        },
        "nose": {
            "hashes": [
                "sha256:9ff7c6cc443f8c51994b34a667bbcf45afd6d945be7477b52e97516fd17c53ac",
                "sha256:dadcddc0aefbf99eea214e0f1232b94f2fa9bd98fa8353711dacb112bfcbbb2a",
                "sha256:f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98"
            ],
            "index": "pypi",
            "version": "==1.3.7"
        },
        "pluggy": {
            "hashes": [
                "sha256:447ba94990e8014ee25ec853339faf7b0fc8050cdc3289d4d71f7f410fb90095",
                "sha256:bde19360a8ec4dfd8a20dcb811780a30998101f078fc7ded6162f0076f50508f"
            ],
            "version": "==0.8.0"
        },
        "py": {
            "hashes": [
                "sha256:bf92637198836372b520efcba9e020c330123be8ce527e535d185ed4b6f45694",
                "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6"
            ],
            "version": "==1.7.0"
        },
        "pyfakefs": {
            "hashes": [
                "sha256:75695aedcd62e88f9e4a98b09bccf03524393d1806dafa8b7d53f9cacb67a249",
                "sha256:af3633627a6fda5e78745f7294f7c8f739d8854e6edcf53f7bed5a0d1f6e2aee"
            ],
            "index": "pypi",
            "version": "==3.5.3"
        },
        "pytest": {
            "hashes": [
                "sha256:f689bf2fc18c4585403348dd56f47d87780bf217c53ed9ae7a3e2d7faa45f8e9",
                "sha256:f812ea39a0153566be53d88f8de94839db1e8a05352ed8a49525d7d7f37861e9"
            ],
            "index": "pypi",
            "version": "==4.0.2"
        },
        "pytest-cov": {
            "hashes": [
                "sha256:513c425e931a0344944f84ea47f3956be0e416d95acbd897a44970c8d926d5d7",
                "sha256:e360f048b7dae3f2f2a9a4d067b2dd6b6a015d384d1577c994a43f3f7cbad762"
            ],
            "index": "pypi",
            "version": "==2.6.0"
        },
        "pytest-mock": {
            "hashes": [
                "sha256:53801e621223d34724926a5c98bd90e8e417ce35264365d39d6c896388dcc928",
                "sha256:d89a8209d722b8307b5e351496830d5cc5e192336003a485443ae9adeb7dd4c0"
            ],
            "index": "pypi",
            "version": "==1.10.0"
        },
        "pytest-runner": {
            "hashes": [
                "sha256:d23f117be39919f00dd91bffeb4f15e031ec797501b717a245e377aee0f577be",
                "sha256:d987fec1e31287592ffe1cb823a8c613c533db4c6aaca0ee1191dbc91e2fcc61"
            ],
            "index": "pypi",
            "version": "==4.2"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:891c38b2a02f5bb1be3e4793866c8df49c7d19baabf9c1bad62547e0b4866aca",
                "sha256:95511bae634d69bc7329ba55e646499a842bc4ec342ad54a8cdb65645a0aad3c"
            ],
            "markers": "python_version >= '2.7'",
            "version": "==2.6.1"
        },
        "pyyaml": {
            "hashes": [
                "sha256:3d7da3009c0f3e783b2c873687652d83b1bbfd5c88e9813fb7e5b03c0dd3108b",
                "sha256:3ef3092145e9b70e3ddd2c7ad59bdd0252a94dfe3949721633e41344de00a6bf",
                "sha256:40c71b8e076d0550b2e6380bada1f1cd1017b882f7e16f09a65be98e017f211a",
                "sha256:558dd60b890ba8fd982e05941927a3911dc409a63dcb8b634feaa0cda69330d3",
                "sha256:a7c28b45d9f99102fa092bb213aa12e0aaf9a6a1f5e395d36166639c1f96c3a1",
                "sha256:aa7dd4a6a427aed7df6fb7f08a580d68d9b118d90310374716ae90b710280af1",
                "sha256:bc558586e6045763782014934bfaf39d48b8ae85a2713117d16c39864085c613",
                "sha256:d46d7982b62e0729ad0175a9bc7e10a566fc07b224d2c79fafb5e032727eaa04",
                "sha256:d5eef459e30b09f5a098b9cea68bebfeb268697f78d647bd255a085371ac7f3f",
                "sha256:e01d3203230e1786cd91ccfdc8f8454c8069c91bee3962ad93b87a4b2860f537",
                "sha256:e170a9e6fcfd19021dd29845af83bb79236068bf5fd4df3327c1be18182b2531"
            ],
            "version": "==3.13"
        },
        "s3transfer": {
            "hashes": [
                "sha256:90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1",
                "sha256:c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f"
            ],
            "version": "==0.1.13"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39",
                "sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"
            ],
            "markers": "python_version >= '3.4'",
            "version": "==1.24.1"
        }
    }
}

```
</details>

**Comment by UniversalSuperBox** [comment] 2018-12-19 20:42
I can add that I was able to put in my credentials while Pipenv is hanging, it's just updating the last line of its output so that I couldn't see the prompt.

**Comment by frostming** [comment] 2019-01-04 13:52
Duplicate of #3412

**Closed by frostming** 2019-01-04 13:52 UTC
