### ISSUE TITLE
Mirror setup failure: parse error and ignored .env

### ISSUE THREAD

**Issue by memco** [pypa/pipenv#2348] opened 2018-06-12 15:33 UTC
I tried to run `pipenv install --three --pypi-mirror https://pypi.python.org/simple` (the pipfile specifies a separate mirror) and after setting up the virtualenv it says 

```
Installing ---pypi-mirror…
WARNING: Invalid requirement, parse error at "'--pypi-m'"
``` 

This seems to be similar behavior to #2326. 

Additionally, what is the correct usage of `PIPENV_PYPI_MIRROR`? I have this setup in my .env, but it seems to be using the [[source]] url anyway. Does the [[source]] name impact the mirror flag in any way?

The pipfile looks like this:
```
[[source]]

url = "http://ourmirror/devpi/root/pypi/+simple"
verify_ssl = false
name = "ourmirror"

[packages]
…
```

The end goal is that I would like to be able to override the custom mirrors when they are not available, but have them be the default.

I am running this on Mac 10.13.4 with python 3.6.5 installed via homebrew.

**Comment by uranusjr** [comment] 2018-06-12 16:03
Judging from the log, I believe you mistyped `--pypi-mirror` as `---pypi-mirror` (one extra dash) :p

Also, even if you typed correctly, the `--pypi-mirror` flag is not available on Homebrew yet (v2018.05.18), only in master. Failing to identify it as a flag, `install` would try to treat it as a package, yielding the result you got.

Closing since this is not a bug. I do wonder why `ignore_unknown_options` is set for `install`, however… @techalchemy do you know the context?

**Closed by uranusjr** 2018-06-12 16:03 UTC
