### ISSUE TITLE
pkg_resources.VersionConflict: (importlib-metadata 2.1.1 (/home/salim/.local/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))

### ISSUE THREAD

**Issue by Piskuliki0723** [pypa/pipenv#4597] opened 2021-01-21 16:43 UTC
I am not updating my Linux. I haven't updated python3.
An error appeared unexpectedly. I cannot create any virtual environment:
`pipenv --python 3.7`
`pkg_resources.VersionConflict: (importlib-metadata 2.1.1 (/home/salim/.local/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))`
I did just `pipenv shell`
but after `pipenv install`
I am getting the same error.
All past virtual environments work. But new ones are not being created. Can I fix the problem without updating my system or changing python3.7 versions?

I've also tried pipenv --python 3.8.
pipenv --python 3.8
```
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: /home/salim/Desktop/1/Pipfile
Using /usr/bin/python3.8 (3.8.2) to create virtualenv…
⠧ Creating virtual environment...created virtual environment CPython3.8.2.final.0-64 in 398ms
  creator CPython3Posix(dest=/home/salim/.local/share/virtualenvs/1-TTkpkNMv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/salim/.local/share/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Traceback (most recent call last):
  File "/home/salim/.local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/cli/command.py", line 204, in cli
    clear=state.clear,
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/core.py", line 580, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/core.py", line 545, in ensure_virtualenv
    pypi_mirror=pypi_mirror,
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/core.py", line 512, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/core.py", line 999, in do_create_virtualenv
    project._environment.add_dist("pipenv")
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/environment.py", line 135, in add_dist
    self.extend_dists(dist)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/home/salim/.local/lib/python3.7/site-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 643, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 2.1.1 (/home/salim/.local/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))

```
Same error in my folder just one file
'hello.py'
print ("hello")

**Any help please.**

**Comment by frostming** [comment] 2021-01-22 00:31
Duplicate of #4549 and #4476 , close it now.

**Closed by frostming** 2021-01-22 00:31 UTC
