### ISSUE TITLE
Dependencies cannot be resolved

### ISSUE THREAD

**Issue by exolab** [pypa/pipenv#4426] opened 2020-08-14 09:27 UTC
I just cannot get pipenv to work at all.

I tried installing using `pip install --user` as well as "raw" installation using curl.

The end result is always this:

```
$ pipenv lock --clear                                                            
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
[ResolutionFailure]:   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
[ResolutionFailure]:   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   Fil "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 1093, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 818, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches pytest<4.0,>=2.7,>=3.6.0,>=4.6,~=3.6 (from -r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 9))
Tried: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.1, 2.7.2, 2.7.2, 2.7.3, 2.7.3, 2.8.0, 2.8.0, 2.8.1, 2.8.1, 2.8.2, 2.8.2, 2.8.3, 2.8.3, 2.8.4, 2.8.4, 2.8.5, 2.8.5, 2.8.6, 2.8.6, 2.8.7, 2.8.7, 2.9.0, 2.9.0, 2.9.1, 2.9.1, 2.9.2, 2.9.2, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 3.0.2, 3.0.2, 3.0.3, 3.0.3, 3.0.4, 3.0.4, 3.0.5, 3.0.5, 3.0.6, 3.0.6, 3.0.7, 3.0.7, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3, 3.2.4, 3.2.4, 3.2.5, 3.2.5, 3.3.0, 3.3.0, 3.3.1, 3.3.1, 3.3.2, 3.3.2, 3.4.0, 3.4.0, 3.4.1, 3.4.1, 3.4.2, 3.4.2, 3.5.0, 3.5.0, 3.5.1, 3.5.1, 3.6.0, 3.6.0, 3.6.1, 3.6.1, 3.6.2, 3.6.2, 3.6.3, 3.6.3, 3.6.4, 3.6.4, 3.7.0, 3.7.0, 3.7.1, 3.7.1, 3.7.2, 3.7.2, 3.7.3, 3.7.3, 3.7.4, 3.7.4, 3.8.0, 3.8.0, 3.8.1, 3.8.1, 3.8.2, 3.8.2, 3.9.1, 3.9.1, 3.9.2, 3.9.2, 3.9.3, 3.9.3, 3.10.0, 3.10.0, 3.10.1, 3.10.1, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.0.2, 4.0.2, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 4.2.0, 4.2.0, 4.2.1, 4.2.1, 4.3.0, 4.3.0, 4.3.1, 4.3.1, 4.4.0, 4.4.0, 4.4.1, 4.4.1, 4.4.2, 4.4.2, 4.5.0, 4.5.0, 4.6.0, 4.6.0, 4.6.1, 4.6.1, 4.6.2, 4.6.2, 4.6.3, 4.6.3, 4.6.4, 4.6.4, 4.6.5, 4.6.5, 4.6.6, 4.6.6, 4.6.7, 4.6.7, 4.6.8, 4.6.8, 4.6.9, 4.6.9, 4.6.10, 4.6.10, 4.6.11, 4.6.11, 5.0.0, 5.0.0, 5.0.1, 5.0.1, 5.1.0, 5.1.0, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.3, 5.1.3, 5.2.0, 5.2.0, 5.2.1, 5.2.1, 5.2.2, 5.2.2, 5.2.3, 5.2.3, 5.2.4, 5.2.4, 5.3.0, 5.3.0, 5.3.1, 5.3.1, 5.3.2, 5.3.2, 5.3.3, 5.3.3, 5.3.4, 5.3.4, 5.3.5, 5.3.5, 5.4.0, 5.4.0, 5.4.1, 5.4.1, 5.4.2, 5.4.2, 5.4.3, 5.4.3, 6.0.0, 6.0.0, 6.0.1, 6.0.1
Skipped pre-versions: 6.0.0rc1, 6.0.0rc1
There are incompatible versions in the resolved dependencies:
  pytest~=3.6 (from -r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 9))
  pytest<4.0,>=3.6.0 (from amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
  pytest>=2.7 (from pytest-mock==1.13.0->amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
  pytest>=4.6 (from pytest-cov==2.10.0->amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
```

Assuming I messed up somewhere along the way, I tried to 
```
rm -rf ~/.local/bin/pipenv-resolver
rm -rf ~/.local/bin/pipenv
rm -rf ~/.local/share/virtualenv*
rm -rf ~/.local/lib/python3.8/site-packages
rm -rf ~/.cache/pipenv
```

then reinstall pipenv. That did not help.

I am probably making an easy mistake, but I am stumped.

**Comment by frostming** [comment] 2020-08-14 09:30
See the last lines in the error output:
```
There are incompatible versions in the resolved dependencies:
  pytest~=3.6 (from -r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 9))
  pytest<4.0,>=3.6.0 (from amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
  pytest>=2.7 (from pytest-mock==1.13.0->amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
  pytest>=4.6 (from pytest-cov==2.10.0->amundsen-databuilder==2.6.2->-r /tmp/pipenv0p7gchkyrequirements/pipenv-mykjpoq5-constraints.txt (line 15))
```
It is impossible for Pipenv to find a resolution that satisfies all the requirements. So it fails as expected. Not a bug, closing it now

**Closed by frostming** 2020-08-14 09:30 UTC

**Comment by exolab** [comment] 2020-08-14 09:33
I am aware it is not a bug, which is why I though I selected "Issue: Usage / Requests for Help".

**Comment by frostming** [comment] 2020-08-14 09:53
To remove the conflicting dependencies, pin `pytest-cov>=2.5.1,<=2.9` in your Pipfile
