### ISSUE TITLE
`pipenv install fabric3` doesn't work with an error

### ISSUE THREAD

**Issue by gh640** [pypa/pipenv#2495] opened 2018-07-03 09:48 UTC
##### Issue description

When I tried to update a package maintained with pipenv after update pipenv to `2018.7.1`, I met the following error and couldn't update it.

```text
$ pipenv update django

...

pipenv.patched.notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'platform_python_implementation != "PyPy"; platform_python_implementation != "PyPy"', parse error at '; platfo'
```

I investigated and found that it is caused by fabric3 package in my case. I could reproduce the error with the following command in a clean project.

```text
$ pipenv --version
pipenv, version 2018.7.1
$ pipenv install fabric3
Installing fabric3...
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: fabric3 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (1.14.post1)
Requirement already satisfied: six>=1.10.0 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from fabric3) (1.11.0)
Requirement already satisfied: paramiko<3.0,>=2.0 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from fabric3) (2.4.1)
Requirement already satisfied: bcrypt>=3.1.3 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from paramiko<3.0,>=2.0->fabric3) (3.1.4)
Requirement already satisfied: cryptography>=1.5 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from paramiko<3.0,>=2.0->fabric3) (2.2.2)
Requirement already satisfied: pynacl>=1.0.1 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from paramiko<3.0,>=2.0->fabric3) (1.2.1)
Requirement already satisfied: pyasn1>=0.1.7 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from paramiko<3.0,>=2.0->fabric3) (0.4.3)
Requirement already satisfied: cffi>=1.1 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from bcrypt>=3.1.3->paramiko<3.0,>=2.0->fabric3) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from cryptography>=1.5->paramiko<3.0,>=2.0->fabric3) (0.24.0)
Requirement already satisfied: idna>=2.1 in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from cryptography>=1.5->paramiko<3.0,>=2.0->fabric3) (2.7)
Requirement already satisfied: pycparser in /path/share/virtualenvs/venvname-CSo2ZBZk/lib/python3.6/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko<3.0,>=2.0->fabric3) (2.18)

Adding fabric3 to Pipfile's [dev-packages]...
Pipfile.lock (43168b) out of date, updating to (8f29af)...
Locking [dev-packages] dependencies...
path/py3/lib/python3.6/site-packages/pipenv/resolver.py", line 76, in main
    system=system,
  File "/path/py3/lib/python3.6/site-packages/pipenv/resolver.py", line 63, in resolve
    allow_global=system,
  File "/path/py3/lib/python3.6/site-packages/pipenv/utils.py", line 402, in resolve_deps
    req_dir=req_dir
  File "/path/py3/lib/python3.6/site-packages/pipenv/utils.py", line 293, in actually_resolve_deps
    results = resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS)
  File "/path/py3/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 104, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/path/py3/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 209, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/path/py3/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 311, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/path/py3/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 193, in from_line
    markers = Marker(markers)
  File "/path/py3/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 281, in __init__
    raise InvalidMarker(err_str)
pipenv.patched.notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'platform_python_implementation != "PyPy"; platform_python_implementation != "PyPy"', parse error at '; platfo'
```

##### Expected result

The installation command `pipenv install` works.

##### Actual result

The above error occurs and the installation process fails.

##### Steps to replicate

```text
$ pip install pipenv==2018.7.1
$ pipenv --version
pipenv, version 2018.7.1
$ pipenv install fabric3
```

If I miss anything important to share, please let me know. Thank you in advance.

(I believe pasting the result of `pipenv --support` is not necessary in this case. If it's necessary, please let me know.)

**Comment by amir20** [comment] 2018-07-03 15:03
I also get this error by doing just `pipenv update`. My version is `pipenv, version 2018.7.1`.  This happened right after I did `pip install -U pipenv`

**Comment by erinxocon** [comment] 2018-07-04 18:51
Hi guys!  Can you try pulling from master and trying again?  I think we fixed this.

**Comment by erinxocon** [comment] 2018-07-04 18:52
Also it'd be nice to see the `pipenv --support` It is apart of the issue template for a reason :)

**Comment by uranusjr** [comment] 2018-07-04 19:01
According to #2508 (a very similar? the same? issue), `pipenv --clear` may help as well.

**Comment by amir20** [comment] 2018-07-04 23:28
Let me know if I can help any other way.

**Comment by amir20** [comment] 2018-07-05 02:03
I have tried removing lock file. Reinstalling pipenv. Reinstalling all dependencies and no luck. :( This also happens to me when I try to `pipenv install`

**Comment by amir20** [comment] 2018-07-05 02:08
Rolling back to `pipenv==2018.6.25` does work for now.

**Comment by erinxocon** [comment] 2018-07-05 03:56
Hi @amir20!  Thanks for using pipenv and for giving us all that information.  Hmm if `pipenv —clear` didn’t work than I don’t think you had the master branch installed.  This is an unreleased command that is currently only in master.  Trying to replicate with your Pipfile now.

**Comment by erinxocon** [comment] 2018-07-05 04:18
@amir20 after testing with the latest commit from master I can confirm that your pipfile installs fine...as long as I have MS Build Tools installed!  I’m going to close this now as it’s very similar to another issue as @uranusjr mentioned.  If it still doesn’t work with the master branch let me know!

**Closed by erinxocon** 2018-07-05 04:18 UTC

**Comment by amir20** [comment] 2018-07-05 06:01
`pip install git+ssh://git@github.com/pypa/pipenv.git@master` actually works because I do have my ssh keys. I just misunderstood something earlier. I didn't realize that `--clean` was something that was added in master. 

I can now run `pipenv --clear` which says `Clearing caches…`. 

With the cache cleared, `pipenv update` works! So I think we are all good here. 

And you are welcome about using pipenv. I was new to python world a few months ago and I couldn't understand why nothing decent existed out there for managing dependencies. I am loving pipenv now because it's exactly what I would expect a dep management tool to do.

**Comment by gh640** [comment] 2018-07-05 10:18
@uranusjr thank your for your support! `pipenv --clear` after updating the package to the HEAD works like a charm :)
