### ISSUE TITLE
Git dependency with specified branch in Pipfile turns into PyPI dependency in Pipfile.lock

### ISSUE THREAD

**Issue by inducer** [pypa/pipenv#1779] opened 2018-03-18 20:33 UTC
##### Expected result

Given [this line](https://github.com/inducer/relate/blob/899f02159e00b2995c456d6fd47128aaca36c2cf/Pipfile#L93) in my Pipfile (a hacked version of mozilla's bleach, don't judge), I was expecting [the corresponding lines](https://github.com/inducer/relate/blob/899f02159e00b2995c456d6fd47128aaca36c2cf/Pipfile.lock#L86) of `Pipfile.lock` to reflect the git dependency. The issue may well be that another part of the dependencies also links to bleach (in which case I would expect an error).

##### Actual result

`Pipfile.lock` points to the version from the package index.

##### Steps to replicate

* Clone the linked repo at the specified revision
* `rm Pipfile.lock`
* `pipenv install`

#### `pipenv help` output

<details><summary>$ python -m pipenv.help output</summary>
Pipenv version: `'11.8.0'`

Pipenv location: `'/home/andreas/work/django/relate/.env/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/andreas/work/django/relate/.env/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.7`: `/usr/bin/python3.7m`
  - `3.7`: `/usr/bin/python3.7`

  - `3.6.4`: `/home/andreas/work/django/relate/.env/bin/python`
  - `2.7.14`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.4`: `/home/andreas/work/django/relate/.env/bin/python3`
  - `3.6.4`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-1-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.15.4-1 (2018-02-18)',
 'python_full_version': '3.6.4+',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LANG`
  - `USER`
  - `LOGNAME`
  - `HOME`
  - `PATH`
  - `MAIL`
  - `SHELL`
  - `SSH_CLIENT`
  - `SSH_CONNECTION`
  - `SSH_TTY`
  - `TERM`
  - `DISPLAY`
  - `XDG_SESSION_ID`
  - `XDG_RUNTIME_DIR`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LANGUAGE`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `MANPATH`
  - `PREFERRED_EDITOR`
  - `EDITOR`
  - `PKG_CONFIG_PATH`
  - `LD_LIBRARY_PATH`
  - `PYTHONSTARTUP`
  - `BROWSER`
  - `AF_PATH`
  - `COLORTERM`
  - `OCCA_DIR`
  - `TEXMACS_PATH`
  - `SSH_AUTH_SOCK`
  - `GOOGLE_APPLICATION_CREDENTIALS`
  - `VIRTUAL_ENV`
  - `PS1`
  - `_`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/andreas/work/django/relate/.env/bin:/home/andreas/pack/TeXmacs-1.99.6-10945-i386-pc-linux-gnu//bin:/sbin:/usr/sbin:/home/andreas/bin:.:/home/andreas/pool/bin:/bin:/home/andreas/pack/pocl-build/bin:/home/andreas/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/andreas/pack/ispc-v1.9.0-linux`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `de_DE.UTF-8`
  - `PWD`: `/home/andreas/work/django/relate`
  - `VIRTUAL_ENV`: `/home/andreas/work/django/relate/.env`

---------------------------

**Comment by techalchemy** [comment] 2018-04-11 01:10
OK so I did confirm something else has a hard dependency on bleach, so whatever gets installed last is going to take precedence unfortunately

It looks like `nbconvert` is the other package using bleach, so you should just list it above your custom `bleach` ref and it should work.  Fixing this is actually kind of complicated and probably out of scope for now

**Closed by techalchemy** 2018-04-11 01:10 UTC

**Comment by inducer** [comment] 2018-04-11 01:39
Thanks for taking a look.

> Fixing this is actually kind of complicated and probably out of scope for now

Well, I'd still argue that it's incorrect behavior. (So I'd suggest keeping this open, but maybe with a 'later' tag.) All I'm expecting is an error message that tells me what I'm asking for can't be done.

**Comment by techalchemy** [comment] 2018-04-11 01:54
The issue is well understood and has essentially nothing to do with your specific situation, so we don't really have a need to track it here
