### ISSUE TITLE
Changing python version requirements without deleting Pipfile.lock causes issues.

### ISSUE THREAD

**Issue by boarder7395** [pypa/pipenv#4809] opened 2021-10-19 21:11 UTC
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

I tried accessing https://pipenv.pypa.io/en/latest/diagnose/ to debug the issue but it seems that site is down currently.

### Issue description

If you have a Pipfile that specifies a specific python version:

```
[requires]
python_version = "3.8"
```
and lock the file `pipenv lock --dev`

then change the python_version to say 3.7
```
[requires]
python_version = "3.7"
```
and lock the file again `pipenv  lock --dev`

### Expected result

The Pipflie.lock to be updated correctly. 

### Actual result

The lock file was updated but received a failure when running `pipenv install --deploy --dev`

#9 2.022✔ Successfully created virtual environment! 
#9 2.234 Virtualenv location: /opt/deps/.venv
#9 2.273 Warning: Your Pipfile requires python_version ~=3.7, but you are using 3.7.3 (/opt/deps/.venv/bin/python).
#9 2.273   $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
#9 2.273   $ pipenv check will surely fail.
#9 2.284 Warning: Your Pipfile requires python_version ~=3.7, but you are using 3.7.3 (/opt/deps/.venv/bin/python).
#9 2.284   $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
#9 2.289 [DeployException]:       return ctx.invoke(f, obj, *args, **kwargs)
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 610, in invoke
#9 2.289 [DeployException]:       return callback(*args, **kwargs)
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
#9 2.289 [DeployException]:       return f(get_current_context(), *args, **kwargs)
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/cli/command.py", line 253, in install
#9 2.289 [DeployException]:       site_packages=state.site_packages
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1928, in do_install
#9 2.289 [DeployException]:       site_packages=site_packages,
#9 2.289 [DeployException]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 612, in ensure_project
#9 2.289 [DeployException]:       raise exceptions.DeployException
#9 2.289 ERROR:: Aborting deploy

Although if you first remove the pipfile.lock `rm Pipfile.lock`
and run `pipenv lock --dev` with the new python version everything runs successfully.

### Steps to replicate

See Above.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@3.9/bin/python3.9'`

Python installations found:

  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.10`: `/Users/tkalbach/.pyenv/versions/3.7.10/bin/python3`
  - `3.6.13`: `/Users/tkalbach/.pyenv/versions/3.6.13/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT '
                     '2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64',
 'python_full_version': '3.9.7',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `SHELL`
  - `COLORTERM`
  - `XPC_FLAGS`
  - `HISTCONTROL`
  - `TERM_PROGRAM_VERSION`
  - `CONDA_EXE`
  - `_CE_M`
  - `HISTSIZE`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `JAVA_HOME`
  - `SSH_AUTH_SOCK`
  - `AWS_PROFILE`
  - `SDKMAN_CANDIDATES_DIR`
  - `EDITOR`
  - `PWD`
  - `LOGNAME`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `SDKMAN_VERSION`
  - `TMPDIR`
  - `GIT_ASKPASS`
  - `CLICOLOR`
  - `BASH_COMPLETION_COMPAT_DIR`
  - `TERM`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `_CE_CONDA`
  - `USER`
  - `VSCODE_GIT_IPC_HANDLE`
  - `CONDA_SHLVL`
  - `MAVEN_HOME`
  - `SDKMAN_DIR`
  - `SHLVL`
  - `LESS_TERMCAP_ue`
  - `INPUTRC`
  - `LESS_TERMCAP_us`
  - `SDKMAN_CANDIDATES_API`
  - `XPC_SERVICE_NAME`
  - `CONDA_PYTHON_EXE`
  - `PS1`
  - `LOCAL_CONFIG`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `PATH`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `SDKMAN_PLATFORM`
  - `__CF_USER_TEXT_ENCODING`
  - `TERM_PROGRAM`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/curl/bin:/Users/tkalbach/.krew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/curl/bin:/Users/tkalbach/miniconda3/condabin:/Users/tkalbach/.sdkman/candidates/maven/current/bin:/Users/tkalbach/.sdkman/candidates/java/current/bin:/Users/tkalbach/.krew/bin:/Users/tkalbach/.istioctl/bin:/Users/tkalbach/.istioctl/bin`
  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `code --wait`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/tkalbach/repos/tie2order/builds`

---------------------------

</details>

**Comment by matteius** [comment] 2021-12-24 02:23
@boarder7395 I think the issue here is the --deploy flag, which I had to reference the docs
`--deploy — Make sure the packages are properly locked in Pipfile.lock, and abort if the lock file is out-of-date.`
Ok, but I think it is also complaining because the virtualenv that got created the first time was python 3.8 and it is expecting 3.7.  Then I managed to reproduce your issue as a side effect because in my example I picked Django = "*" but in going from python 3.8 which supports Django 4 to Python 3.7 which doesn't, I found the difference in the lock file to be just that.  So if I change your example from going from 3.8 to 3.9 then it works just fine with the same lock file.

```
davis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv lock --dev

Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

  $ pipenv check will surely fail.

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (8e97b7)!

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy --dev

Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

Usage: pipenv install [OPTIONS] [PACKAGES]...



ERROR:: Aborting deploy

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy 

Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

Usage: pipenv install [OPTIONS] [PACKAGES]...



ERROR:: Aborting deploy

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install

Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

  $ pipenv check will surely fail.

Installing dependencies from Pipfile.lock (8e97b7)...

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:06

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv --rm

Removing virtualenv (/home/mdavis/.virtualenvs/pipenv-4809-3gFA167c)...

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy 

Warning: Python 3.7 was not found on your system...

Would you like us to install CPython 3.7.12 with Pyenv? [Y/n]: Y

Installing CPython 3.7.12 with /home/mdavis/.pyenv/bin/pyenv (this may take a few minutes)...

✔ Success! 

patching file Doc/library/ctypes.rst

patching file Lib/test/test_unicode.py

patching file Modules/_ctypes/_ctypes.c

patching file Modules/_ctypes/callproc.c

patching file Modules/_ctypes/ctypes.h

patching file setup.py

patching file 'Misc/NEWS.d/next/Core and Builtins/2020-06-30-04-44-29.bpo-41100.PJwA6F.rst'

patching file Modules/_decimal/libmpdec/mpdecimal.h



Creating a virtualenv for this project...

Pipfile: /home/mdavis/shared-projects/pipenv-4809/Pipfile

Using /home/mdavis/.pyenv/versions/3.7.12/bin/python3.7m (3.7.12) to create virtualenv...

⠹ Creating virtual environment...created virtual environment CPython3.7.12.final.0-64 in 1545ms

  creator CPython3Posix(dest=/home/mdavis/.virtualenvs/pipenv-4809-3gFA167c, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mdavis/.local/share/virtualenv)

    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator



✔ Successfully created virtual environment! 

Virtualenv location: /home/mdavis/.virtualenvs/pipenv-4809-3gFA167c

Installing dependencies from Pipfile.lock (8e97b7)...

An error occurred while installing django==4.0 --hash=sha256:59304646ebc6a77b9b6a59adc67d51ecb03c5e3d63ed1f14c909cdfda84e8010 --hash=sha256:d5a8a14da819a8b9237ee4d8c78dfe056ff6e8a7511987be627192225113ee75! Will try again.

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:08

Installing initially failed dependencies...

[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement django==4.0 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29, 2.0a1, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.12, 2.0.13, 2.1a1, 2.1b1, 2.1rc1, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.2a1, 2.2b1, 2.2rc1, 2.2, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.20, 2.2.21, 2.2.22, 2.2.23, 2.2.24, 2.2.25, 3.0a1, 3.0b1, 3.0rc1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.1a1, 3.1b1, 3.1rc1, 3.1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.2a1, 3.2b1, 3.2rc1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10)

[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for django==4.0

ERROR: Couldn't install package: django

 Package installation failed...

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:04

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ ls

Pipfile  Pipfile.lock

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ cp Pipfile.lock Pipfile.lock.bad

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ rm Pipfile.lock

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv lock --dev

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (8e97b7)!

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy 

Installing dependencies from Pipfile.lock (8e97b7)...

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:00

```

```
# Take 2 going from Python 3.8 to Python 3.9 no issue because the requirements are compatible.
mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install 

Warning: Your Pipfile requires python_version 3.9, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

  $ pipenv check will surely fail.

Pipfile.lock (1ee349) out of date, updating to (f57020)...

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (f57020)!

Installing dependencies from Pipfile.lock (f57020)...

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:06

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy

Warning: Your Pipfile requires python_version 3.9, but you are using 3.8.12 (/home/mdavis/./p/bin/python).

  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.

Usage: pipenv install [OPTIONS] [PACKAGES]...



ERROR:: Aborting deploy

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv --rm

Removing virtualenv (/home/mdavis/.virtualenvs/pipenv-4809-3gFA167c)...

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4809$ pipenv install --deploy

Creating a virtualenv for this project...

Pipfile: /home/mdavis/shared-projects/pipenv-4809/Pipfile

Using /usr/bin/python3.9 (3.9.7) to create virtualenv...

⠧ Creating virtual environment...created virtual environment CPython3.9.7.final.0-64 in 391ms

  creator CPython3Posix(dest=/home/mdavis/.virtualenvs/pipenv-4809-3gFA167c, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mdavis/.local/share/virtualenv)

    added seed packages: pip==21.3.1, setuptools==59.2.0, wheel==0.37.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator



✔ Successfully created virtual environment! 

Virtualenv location: /home/mdavis/.virtualenvs/pipenv-4809-3gFA167c

Installing dependencies from Pipfile.lock (f57020)...

Ignoring backports.zoneinfo: markers 'python_version < "3.9"' don't match your environment

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:05

**Comment by matteius** [comment] 2021-12-24 02:26
Since your issue doesn't have an example packages section in the Pipfile, and I feel that the triage performed is sufficient so I am closing this for the time being.

**Closed by matteius** 2021-12-24 02:26 UTC
