### ISSUE TITLE
Windows install only works in admin cmd

### ISSUE THREAD

**Issue by brimurr** [pypa/pipenv#3779] opened 2019-06-04 14:36 UTC
### Issue description

Installation on windows using the installation guide https://docs.pipenv.org/en/latest/install/

pip install --user pipenv

### Expected result

After installation use of the pipenv command e.g. pipenv check, or pipenv install requests. 

### Actual result

Entering these commands the terminal just hangs with no response.

HOWEVER, if I open a cmd prompt as admin ("Run as Administrator"), the command works successfully.

I do not expect or want to run these command as admin.

### Steps to replicate

pipenv check

-------------------------------------------------------------------------------

WHEN RUNNING IN ADMIN:-

```
> C:\Users\bmg\example_project>pipenv --support
> <details><summary>$ pipenv --support</summary>
> 
> Pipenv version: `'2018.11.26'`
> 
> Pipenv location: `'C:\\Users\\bmg\\AppData\\Roaming\\Python\\Python37\\site-packages\\pipenv'`
> 
> Python location: `'c:\\users\\bmg\\appdata\\local\\programs\\python\\python37-32\\python.exe'`
> 
> Python installations found:
> 
>   - `3.7.3`: `C:\Users\bmg\AppData\Local\Programs\Python\Python37-32\python.exe`
> 
> PEP 508 Information:
> 
> ```
> {'implementation_name': 'cpython',
>  'implementation_version': '3.7.3',
>  'os_name': 'nt',
>  'platform_machine': 'AMD64',
>  'platform_python_implementation': 'CPython',
>  'platform_release': '10',
>  'platform_system': 'Windows',
>  'platform_version': '10.0.14393',
>  'python_full_version': '3.7.3',
>  'python_version': '3.7',
>  'sys_platform': 'win32'}
> ```
> 
> System environment variables:
> 
>   - `ACROREAD_DIR`
>   - `ALLUSERSPROFILE`
>   - `ANSOFTLM_LICENSE_FILE`
>   - `APPDATA`
>   - `CDS_IGNORE_LIC_FEATURE`
>   - `CDS_LIB_CONCEPT_CUSTOM_CSFSEARCH`
>   - `CDS_LIC_FILE`
>   - `CDS_LIC_ONLY`
>   - `COMMONPROGRAMFILES`
>   - `COMMONPROGRAMFILES(X86)`
>   - `COMMONPROGRAMW6432`
>   - `COMPUTERNAME`
>   - `COMSPEC`
>   - `HOMEDRIVE`
>   - `HOMEPATH`
>   - `HOMESHARE`
>   - `LM_LICENSE_FILE`
>   - `LM_PROJECT`
>   - `LOCALAPPDATA`
>   - `LOGONSERVER`
>   - `MATRACEAPPS`
>   - `MGC_DISABLE_PRESPLASH_CHECKS`
>   - `MGLS_LICENSE_FILE`
>   - `MINITAB_LICENSE_FILE`
>   - `NILM_LICENSE_FILE`
>   - `NUMBER_OF_PROCESSORS`
>   - `OS`
>   - `PATH`
>   - `PATHEXT`
>   - `PROCESSOR_ARCHITECTURE`
>   - `PROCESSOR_ARCHITEW6432`
>   - `PROCESSOR_IDENTIFIER`
>   - `PROCESSOR_LEVEL`
>   - `PROCESSOR_REVISION`
>   - `PROGRAMDATA`
>   - `PROGRAMFILES`
>   - `PROGRAMFILES(X86)`
>   - `PROGRAMW6432`
>   - `PROMPT`
>   - `PSMODULEPATH`
>   - `PUBLIC`
>   - `SISOFTD_LICENSE_FILE`
>   - `SYSTEMDRIVE`
>   - `SYSTEMROOT`
>   - `TEMP`
>   - `TMP`
>   - `UATDATA`
>   - `USERDNSDOMAIN`
>   - `USERDOMAIN`
>   - `USERDOMAIN_ROAMINGPROFILE`
>   - `USERNAME`
>   - `USERPROFILE`
>   - `WINDIR`
>   - `XILINXD_LICENSE_FILE`
>   - `PIP_DISABLE_PIP_VERSION_CHECK`
>   - `PYTHONDONTWRITEBYTECODE`
>   - `PIP_SHIMS_BASE_MODULE`
>   - `PIP_PYTHON_PATH`
>   - `PYTHONFINDER_IGNORE_UNSUPPORTED`
> 
> Pipenv–specific environment variables:
> 
> 
> Debug–specific environment variables:
> 
>   - `PATH`: `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\doxygen\bin;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\TortoiseGit\bin;C:\Program Files\TortoiseSVN\bin;C:\Users\bmg\AppData\Roaming\Python\Python37\Scripts;C:\Users\bmg\AppData\Local\Microsoft\WindowsApps;C:\Users\bmg\AppData\Local\Programs\Python\Python37-32;C:\Users\bmg\AppData\Local\Programs\Python\Python37-32\Scripts`
> 
> 
> ---------------------------
> 
> Contents of `Pipfile` ('C:\\Users\\bmg\\example_project\\Pipfile'):
> 
> ```toml
> [[source]]
> name = "pypi"
> url = "https://pypi.org/simple"
> verify_ssl = true
> 
> [dev-packages]
> 
> [packages]
> 
> [requires]
> python_version = "3.7"
> 
> ```
> 
> </details>
> 
```

**Comment by frostming** [comment] 2019-07-15 05:55
Any more information? As you know, the dev environment varies from person to person, making it a headache to reproduces such environment-specific issue like this. From a roughly guess this issue is possibly because you installed your Python env and Pipenv under different accounts.

**Comment by frostming** [comment] 2019-10-05 12:43
No new updates, close this now, feel free to reopen when you get more information about the bug.

**Closed by frostming** 2019-10-05 12:43 UTC
Labels: Status: Awaiting Update :hourglass_flowing_sand:, Status: Needs More Information

**Comment by scottnm** [comment] 2020-04-11 20:00
I ran into a similar issue and the suggestion from @frostming helped me self-service

My situation was...
- 1 PC with 2 user accounts
- everything works fine on main acct
- after installing pipenv on second acct things didn't work (lots of errors when using `pipenv shell`
- uninstalled `pipenv`
- installed python via windows store
- reinstalled `pipenv`
- everything works ✅

in case anyone else comes looking for this post, this is what worked for me
