### ISSUE TITLE
install a package, the lock file will not update

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#2626] opened 2018-07-23 11:01 UTC
When I install a package success.The console promotes me Pipfile.lock updating.
But it did not update.

Here is the log:
Adding pyserial==3.4 to Pipfile's [packages]...
Pipfile.lock (a6e5c1) out of date, updating to (4f7cb4)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...

**Comment by uranusjr** [comment] 2018-07-23 12:09
Cannot reproduce, lock file updates correctly for me.

Closing due to insufficient information to continue.

```
uranusjr@tp-mba pipenv-2626 $ ls
Pipfile      Pipfile.lock
uranusjr@tp-mba pipenv-2626 $ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.7"
uranusjr@tp-mba pipenv-2626 $ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "7e7ef69da7248742e869378f8421880cf8f0017f96d94d086813baa518a65489"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}
uranusjr@tp-mba pipenv-2626 $ pipenv install pyserial
Installing pyserial…
Collecting pyserial
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Installing collected packages: pyserial
Successfully installed pyserial-3.4

Adding pyserial to Pipfile's [packages]…
Pipfile.lock (a65489) out of date, updating to (67e43d)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (67e43d)!
Installing dependencies from Pipfile.lock (67e43d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
uranusjr@tp-mba pipenv-2626 $ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "a9fcc5931682bbca22ad91dbdb3120c32c21b4d52002de0845650e7bb167e43d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyserial": {
            "hashes": [
                "sha256:6e2d401fdee0eab996cf734e67773a0143b932772ca8b42451440cfed942c627",
                "sha256:e0770fadba80c31013896c7e6ef703f72e7834965954a78e71a3049488d4d7d8"
            ],
            "index": "pypi",
            "version": "==3.4"
        }
    },
    "develop": {}
}
```

**Closed by uranusjr** 2018-07-23 12:09 UTC
