### ISSUE TITLE
PyPIRepository() got an unexpected keyword argument 'use_json'

### ISSUE THREAD

**Issue by Fak3** [pypa/pipenv#1639] opened 2018-03-09 17:20 UTC
Hi, i thried to initialize new pipenv from my requirements, and got this error instead.

OS: linux 
Python: 3.6
Pipenv: 11.1.8

```bash
$ pipenv install -r requirements.in --three
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
urces, clear=clear, verbose=verbose)
  File "/home/u1/.virtualenvs/npserver/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 395, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/home/u1/.virtualenvs/npserver/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 316, in actually_resolve_reps
    pypi = PyPIRepository(pip_options=pip_options, use_json=True, session=session)
TypeError: __init__() got an unexpected keyword argument 'use_json'
```

**Comment by kennethreitz** [comment] 2018-03-09 17:53
is pipenv in your requirements.in?

**Comment by kennethreitz** [comment] 2018-03-09 19:07
i'm convinced this is something wrong with your environment, so closing for now. 

please comment with additional details, if you have any. we're happy to help (even though the issue's closed)

**Comment by sijis** [comment] 2018-03-09 20:00
I seem to have bumped in the same problem as @Fak3. 
I downgraded from 11.1.8 to 11.1.7 and it worked as expected.

I don't have anything in my requirements.in.

**Comment by kennethreitz** [comment] 2018-03-09 20:10
This is extremely strange. Can you please upgrade to 11.1.9 and run the following and paste the results?

    $ python -m pipenv.help

**Comment by sijis** [comment] 2018-03-09 20:21
```
 saviles  /  tmp  test2  pip install --user -U pipenv
Collecting pipenv
  Downloading pipenv-11.1.9.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 372kB/s 
Requirement already up-to-date: setuptools>=36.2.1 in /home/saviles/.local/lib/python3.6/site-packages (from pipenv)
Requirement already up-to-date: virtualenv in /home/saviles/.local/lib/python3.6/site-packages (from pipenv)
Requirement already up-to-date: virtualenv-clone>=0.2.5 in /home/saviles/.local/lib/python3.6/site-packages (from pipenv)
Installing collected packages: pipenv
  Found existing installation: pipenv 11.1.7
    Uninstalling pipenv-11.1.7:
      Successfully uninstalled pipenv-11.1.7
  Running setup.py install for pipenv ... done
Successfully installed pipenv-11.1.9
 saviles  /  tmp  test2  python -m pipenv.help
/usr/bin/python: No module named pipenv
 saviles  /  tmp  test2  python -V
Python 2.7.14
```
`pip` does show it installed:
```
 saviles  /  tmp  test2  pip list | grep pipenv
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pipenv (11.1.9)
```
I found that odd, so tried the same with python3

`saviles  /  tmp  test2  2  python3 -m pipenv.help`
                                                                                                                                                                                                                                                                                                                                  
Pipenv version: `'11.1.9'`                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                            
Pipenv location: `'/home/saviles/.local/lib/python3.6/site-packages/pipenv'`                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                            
Python location: `'/usr/bin/python3'`                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                            
Other Python installations in `PATH`:                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                            
  - `2.7`: `/usr/bin/python2.7`                                                                                                                                                                                                                                                                                                                                                             
  - `2.7`: `/usr/bin/python2.7`                                                                                                                                                                                                                                                                                                                                                             
  - `2.7`: `/usr/bin/python2.7`                                                                                                                                                                                                                                                                                                                                                             
  - `3.5`: `/home/saviles/.pyenv/shims/python3.5`                                                                                                                                                                                                                                                                                                                                           
  - `3.5`: `/home/saviles/.pyenv/shims/python3.5`                                                                                                                                                                                                                                                                                                                                           
  - `3.5`: `/home/saviles/.pyenv/shims/python3.5`                                                                                                                                                                                                                                                                                                                                           
  - `3.6`: `/usr/bin/python3.6m`                                                                                                                                                                                                                                                                                                                                                            
  - `3.6`: `/usr/bin/python3.6`                                                                                                                                                                                                                                                                                                                                                             
  - `3.6`: `/usr/bin/python3.6`                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                            
  - `2.7.14`: `/usr/bin/python`                                                                                                                                                                                                                                                                                                                                                             
  - `2.7.14`: `/home/saviles/.pyenv/shims/python`                                                                                                                                                                                                                                                                                                                                           
  - `2.7.14`: `/home/saviles/.pyenv/shims/python`                                                                                                                                                                                                                                                                                                                                           
  - `2.7.14`: `/home/saviles/.pyenv/shims/python`                                                                                                                                                                                                                                                                                                                                           
  - `2.7.14`: `/usr/bin/python`                                                                                                                                                                                                                                                                                                                                                             
  - `2.7.14`: `/usr/bin/python2`                                                                                                                                                                                                                                                                                                                                                            
  - `2.7.14`: `/usr/bin/python2`                                                                                                                                                                                                                                                                                                                                                            
  - `3.6.4`: `/usr/bin/python3`                                                                                                                                                                                                                                                                                                                                                             
  - `3.6.4`: `/home/saviles/.pyenv/shims/python3`                                                                                                                                                                                                                                                                                                                                           
  - `3.6.4`: `/home/saviles/.pyenv/shims/python3`                                                                                                                                                                                                                                                                                                                                           
  - `3.6.4`: `/home/saviles/.pyenv/shims/python3`                                                                                                                                                                                                                                                                                                                                           
  - `3.6.4`: `/usr/bin/python3`                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                            
PEP 508 Information:                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            
```                                                                                                                                                                                                                                                                                                                                                                                         
{'implementation_name': 'cpython',                                                                                                                                                                                                                                                                                                                                                          
 'implementation_version': '3.6.4',                                                                                                                                                                                                                                                                                                                                                         
 'os_name': 'posix',                                                                                                                                                                                                                                                                                                                                                                        
 'platform_machine': 'x86_64',                                                                                                                                                                                                                                                                                                                                                              
 'platform_python_implementation': 'CPython',                                                                                                                                                                                                                                                                                                                                               
 'platform_release': '4.15.6-300.fc27.x86_64',                                                                                                                                                                                                                                                                                                                                              
 'platform_system': 'Linux',                                                                                                                                                                                                                                                                                                                                                                
 'platform_version': '#1 SMP Mon Feb 26 18:43:03 UTC 2018',                                                                                                                                                                                                                                                                                                                                 
 'python_full_version': '3.6.4',                                                                                                                                                                                                                                                                                                                                                            
 'python_version': '3.6',                                                                                                                                                                                                                                                                                                                                                                   
 'sys_platform': 'linux'}                                                       
 ```
 
 
 System environment variables:                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                            
  - `QTINC`                                                                                                                                                                                                                                                                                                                                                                                 
  - `LS_COLORS`                                                                                                                                                                                                                                                                                                                                                                             
  - `TMUX_COLUMNS_3`                                                                                                                                                                                                                                                                                                                                                                        
  - `TMUX_COLUMNS_2`                                                                                                                                                                                                                                                                                                                                                                        
  - `TMUX_COLUMNS_1`
  - `TMUX_COLUMNS_0`
  - `TMUX_COLUMNS_5`
  - `TMUX_COLUMNS_4`
  - `TERMINATOR_UUID`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `GDM_LANG`
  - `TMUX_PWD_5`
  - `HISTCONTROL`
  - `TMUX_PWD_4`
  - `TMUX_PWD_3`
  - `TMUX_PWD_2`
  - `TMUX_PWD_1`
  - `TMUX_PWD_0`
  - `DISPLAY`
  - `GUESTFISH_RESTORE`
  - `HOSTNAME`
  - `PYENV_ROOT`
  - `QTDIR`
  - `OLDPWD`
  - `COLORTERM`
  - `GUESTFISH_INIT`
  - `USERNAME`
  - `PYENV_HOOK_PATH`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `SSH_AUTH_SOCK`
  - `XDG_SESSION_ID`
  - `USER`
  - `PYENV_DIR`
  - `GUESTFISH_PS1`
  - `DESKTOP_SESSION`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `PYENV_VERSION`
  - `TMUX`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `TERMINATOR_DBUS_NAME`
  - `XDG_SESSION_DESKTOP`
  - `GJS_DEBUG_OUTPUT`
  - `LOADEDMODULES`
  - `TERMINATOR_DBUS_PATH`
  - `MAIL`
  - `QTLIB`
  - `WINDOWPATH`
  - `SHELL`
  - `TERM`
  - `VTE_VERSION`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `XDG_CURRENT_DESKTOP`
  - `POWERLINE_COMMAND`
  - `MOZ_GMP_PATH`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `TMUX_PANE`
  - `PYENV_SHELL`
  - `SHLVL`
  - `XDG_SEAT`
  - `MODULEPATH`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `PATH`
  - `GUESTFISH_OUTPUT`
  - `MODULESHOME`
  - `HISTSIZE`
  - `GJS_DEBUG_TOPICS`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `BASH_FUNC_module%%`
  - `BASH_FUNC_scl%%`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/usr/bin:/home/saviles/.pyenv/libexec:/home/saviles/.pyenv/plugins/python-build/bin:/home/saviles/.local/bin:/home/saviles/bin:/home/saviles/.pyenv/shims:/home/saviles/.pyenv/bin:/home/saviles/.pyenv/shims:/home/saviles/.pyenv/bin:/home/saviles/.local/bin:/home/saviles/bin:/home/saviles/.pyenv/shims:/home/saviles/.pyenv/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr
/local/sbin:/usr/bin:/usr/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/test2`


---------------------------


Contents of `Pipfile` ('/tmp/test2/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

requests = "*"


[dev-packages]



[requires]

python_version = "3.6"

```


Contents of `Pipfile.lock` ('/tmp/test2/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "33a0ec7c8e3bae6f62dd618f847de92ece20e2bd4efb496927e2524b9c7b8df8"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:14131608ad2fd56836d33a71ee60fa1c82bc9d2c8d98b7bdbc631fe1b3cd1296",
                "sha256:edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d"
            ],
            "version": "==2018.1.18"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "version": "==2.18.4"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    },
    "develop": {}
}

```

**Comment by kennethreitz** [comment] 2018-03-09 20:25
Lastly, `$ which -a pipenv`

**Comment by sijis** [comment] 2018-03-09 20:27
```
 saviles  /  tmp  test2  which -a pipenv
~/.local/bin/pipenv
~/.local/bin/pipenv
```

```
 saviles  /  tmp  test2  head ~/.local/bin/pipenv
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pipenv==11.1.9','console_scripts','pipenv'
__requires__ = 'pipenv==11.1.9'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
```

**Comment by kennethreitz** [comment] 2018-03-09 20:31
hmmm....

``` $ python3```

```pycon
>>> import pipenv
>>> print(pipenv.resolver.__file__)
````

**Comment by sijis** [comment] 2018-03-09 20:35
```
 saviles  /  tmp  test2  python3           
Python 3.6.4 (default, Feb  8 2018, 14:42:51)  
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux                                               
Type "help", "copyright", "credits" or "license" for more information.                        
>>> import pipenv                              
>>> print(pipenv.resolver.__file__)            
/home/saviles/.local/lib/python3.6/site-packages/pipenv/resolver.py                           
>>> 
```

Out of curiousity, i also tried with `python`

```
 saviles  /  tmp  test2  python
Python 2.7.14 (default, Feb 27 2018, 20:43:24) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pipenv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pipenv
>>> 
```

Its definitely leaning towards something my py2 env. However, odd that it was only noticeable in that 11.1.8 release.

**Comment by kennethreitz** [comment] 2018-03-09 20:37
i won't worry about it then :)

**Comment by sijis** [comment] 2018-03-09 20:42
Let me see if i can reproduce this and make sure its not some lingering setup for me.

**Comment by kennethreitz** [comment] 2018-03-09 20:48
feel free to comment as you get more info :)

**Comment by tkossak** [comment] 2018-03-09 22:09
I have the same error:

```bash
$ pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
s, clear=clear, verbose=verbose)
  File "/home/kossak/anaconda3/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 395, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/home/kossak/anaconda3/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 316, in actually_resolve_reps
    pypi = PyPIRepository(pip_options=pip_options, use_json=True, session=session)
TypeError: __init__() got an unexpected keyword argument 'use_json'

$ pipenv --version
pipenv, version 11.2.0

$ pip -V
pip 9.0.1 from /home/kossak/anaconda3/lib/python3.6/site-packages (python 3.6)

$ python -V
Python 3.6.4

$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.1.6
Codename:       Hakoila

```
My Pipfile is:

```ini
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

"discord.py" = "*"
logzero = "*"
fs = "*"


[dev-packages]



[requires]

python_version = "3.6"
```

And I don't have requirements.txt nor requirements.in

**Comment by kennethreitz** [comment] 2018-03-09 22:12
I don't understand ![](http://share.kennethreitz.org/2r3q141n2d3y/Screen%20Shot%202018-03-09%20at%205.11.40%20PM.png)

**Comment by sijis** [comment] 2018-03-09 22:17
@kennethreitz Yeah, it doesn't make sense to me either. The code signature is correct but its almost as if its using/loading another one.

I've been trying in docker, so its a fresh environment but i'm seeing a slew of other issues :/. You may see a handful of bug reports soonish.

**Comment by kennethreitz** [comment] 2018-03-09 22:23
Many thanks for your contributions.

**Comment by kennethreitz** [comment] 2018-03-10 01:34
can anyone having this issue try again with the latest version and see if this is still happening?

**Comment by sijis** [comment] 2018-03-10 01:38
I should be able to try in about 30 minutes.

**Comment by sijis** [comment] 2018-03-10 02:24
Same error :/, however, I think i'm onto something.

**Comment by kennethreitz** [comment] 2018-03-10 02:34
did we try ‘which -a pipenv’?

**Comment by sijis** [comment] 2018-03-10 02:44
Yup: https://github.com/pypa/pipenv/issues/1639#issuecomment-371936118

I tried sticking `iimport ipdb; ipdb.set_trace()` right before the error line:
`vim /home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py +316`

and I ended up with this gem of an error:
```
Locking [dev-packages] dependencies…
/pipenv/../ipdb/__init__.py", line 7, in <module>
    from ipdb.__main__ import set_trace, post_mortem, pm, run             # noqa
  File "/home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/../ipdb/__main__.py", line 15, in <module>
    from IPython import get_ipython
  File "/home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/../IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/../IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/../traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/saviles/.local/lib/python3.6/site-packages/pipenv/../pipenv/../traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

I'm wondering if the python pathing is jacked up somehow. Maybe with pyenv?

I'm spinning up a vm (not a container) with a vanilla system to reproduce.

**Comment by sijis** [comment] 2018-03-10 03:33
The issue reported is not reproduceable on a fresh system install.
I'll look further and see if i can narrow down what tool/config could be causing this weirdness.

**Comment by kennethreitz** [comment] 2018-03-10 03:41
Looking forward to what you discover :)

**Closed** 2018-03-10 03:41 UTC

**Comment by tkossak** [comment] 2018-03-10 15:35
I solved this problem by `pip uninstall pip-tools`. `pip-tools` package has [PyPIRepository](https://github.com/jazzband/pip-tools/blob/master/piptools/repositories/pypi.py#L27) class without `use_json` parameter in its [__init__(...)](https://github.com/jazzband/pip-tools/blob/master/piptools/repositories/pypi.py#L36).

**Comment by techalchemy** [comment] 2018-03-10 15:48
@kennethreitz let’s make sure we grab piptools imports from the right place too

**Comment by sijis** [comment] 2018-03-10 15:48
@tkossak I also just figured that out.

I figured it was conflicting with something else in the environment.

I searched if there was another reference of that class. There was
```
 saviles  /  tmp  test1  1  grep -R 'PyPIRepository(' /home/saviles/.local/lib/
/home/saviles/.local/lib/python3.6/site-packages/piptools/scripts/compile.py:    repository = PyPIRepository(pip_options, session)
/home/saviles/.local/lib/python3.6/site-packages/piptools/repositories/pypi.py:class PyPIRepository(BaseRepository):
/home/saviles/.local/lib/python3.6/site-packages/pipenv/utils.py:    pypi = PyPIRepository(pip_options=pip_options, use_json=False, session=session)
/home/saviles/.local/lib/python3.6/site-packages/pipenv/patched/piptools/scripts/compile.py:    repository = PyPIRepository(pip_options, session)
/home/saviles/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py:class PyPIRepository(BaseRepository):
```

Uninstalled it and things worked as expected.

**Comment by tkossak** [comment] 2018-03-10 15:52
Maybe we should convert `pipenv/patched` direcotries (and others) to packages and do imports like this:
`from pipenv.piptools.repositories.pypi import PyPIRepository`
instead of
`from piptools.repositories.pypi import PyPIRepository` and without:
```python
# Inject vendored directory into system path.
v_path = os.path.abspath(os.path.sep.join([os.path.dirname(os.path.realpath(__file__)), 'vendor']))
sys.path.insert(0, v_path)

# Inject patched directory into system path.
v_path = os.path.abspath(os.path.sep.join([os.path.dirname(os.path.realpath(__file__)), 'patched']))
sys.path.insert(0, v_path)
```

in [_ _ init _ _.py](https://github.com/pypa/pipenv/blob/master/pipenv/__init__.py)?

**Comment by techalchemy** [comment] 2018-03-10 16:04
@tkossak yeah we just ran into this same issue over in #1653 so I’m thinking that’s probably the case. In all likelihood we want to do both but we should probably be explicit about imports, especially patched ones

**Comment by tkossak** [comment] 2018-03-14 11:37
@kennethreitz Shouldn't this issue be open until Pipenv can import proper versions of packages?

**Comment by kennethreitz** [comment] 2018-03-14 12:37
this issue has been long-resolved, in my view.

**Comment by tkossak** [comment] 2018-03-14 14:54
I guess by "long-resolved" you mean "in the last 5 days", because last time this issue appeared, was 5 days ago. Didn't see any commit mentioning this issue, but glad it's resolved, thank you.

**Comment by kennethreitz** [comment] 2018-03-14 14:55
yes :)
