### ISSUE TITLE
PIPENV RUN <bash-script> forgets virtual env

### ISSUE THREAD

**Issue by lugggas** [pypa/pipenv#4848] opened 2021-11-08 15:18 UTC
### Issue description

When I run a bash script via `pipenv run` the bash script is not executed within the virtual env. When I execute the same bash script after activating the env it works.

### Expected result

The bash script should be executed in the virtual env. 

### Steps to replicate

script.sh
```bash
#!/bin/bash
which python
```
Pipfile
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"

[scripts]
script = "./script.sh"
```

1. pipenv install
2. chmod a+x ./script.sh
3. pipenv run script

Output: /usr/local/bin/python
Expected: /root/.local/share/virtualenvs/package-mPHlBhtO/bin/python

When I do
1. pipenv install
2. pipenv shell
3. ./script.sh

Output: /root/.local/share/virtualenvs/package-mPHlBhtO/bin/python
Expected: /root/.local/share/virtualenvs/package-mPHlBhtO/bin/python

-------------------------------------------------------------------------------

$pipenv --support
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"

[scripts]
script = "./script.sh"root@6a38d50fd0da:/package#
root@6a38d50fd0da:/package# pipenv shell
Launching subshell in virtual environment...
root@6a38d50fd0da:/package#  . /root/.local/share/virtualenvs/package-mPHlBhtO/bin/activate
((package) ) root@6a38d50fd0da:/package# ./script.sh
/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python
((package) ) root@6a38d50fd0da:/package# pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.5.post0'`

Pipenv location: `'/usr/local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python3`
  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python`
  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python3.9`
  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python3`
  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python`
  - `3.9.2`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin/python3.9`
  - `3.9.2`: `/usr/bin/python3`
  - `3.9.2`: `/usr/bin/python3.9`
  - `3.8.12`: `/usr/local/bin/python`
  - `3.8.12`: `/usr/local/bin/python3`
  - `3.8.12`: `/usr/local/bin/python3.8`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.10.47-linuxkit',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Sat Jul 3 21:51:47 UTC 2021',
 'python_full_version': '3.8.12',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PIPENV_ACTIVE`
  - `HOSTNAME`
  - `PYTHON_VERSION`
  - `PWD`
  - `PYTHON_SETUPTOOLS_VERSION`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `VIRTUAL_ENV`
  - `GPG_KEY`
  - `TERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SHLVL`
  - `PYTHON_PIP_VERSION`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHON_GET_PIP_SHA256`
  - `PS1`
  - `PYTHON_GET_PIP_URL`
  - `PATH`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/root/.local/share/virtualenvs/package-mPHlBhtO/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/package`
  - `VIRTUAL_ENV`: `/root/.local/share/virtualenvs/package-mPHlBhtO`

---------------------------

Contents of `Pipfile` ('/package/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"

[scripts]
script = "./script.sh"
```

Contents of `Pipfile.lock` ('/package/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "a36a5392bb1e8bbc06bfaa0761e52593cf2d83b486696bf54667ba8da616c839"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by philgyford** [comment] 2021-11-08 16:21
Duplicate of #4838 ?

**Comment by frostming** [comment] 2021-11-09 00:53
Yes, a duplicate

**Closed by frostming** 2021-11-09 00:53 UTC
