### ISSUE TITLE
pipenv run fails when code contains PEP 484 type hints

### ISSUE THREAD

**Issue by silasary** [pypa/pipenv#1465] opened 2018-02-22 04:06 UTC
My code contains the following snippit, which is valid syntax from python 3.6+

```py
from typing import List

NAMES: List[str] = []
```

When running the script via `pipenv run`,  I get a syntax error.

##### Describe your environment

1. Windows 10
1. Python version: Python 3.6.1
1. Pipenv version: pipenv, version 9.1.0

##### Expected result

Script runs correctly.

##### Actual result

```
$>pipenv run example.py
  File "<SNIP>\example.py", line 3
    NAMES: List[str] = []
         ^
SyntaxError: invalid syntax
```

Note that using `pipenv shell` then `python example.py` works correctly.

##### Steps to replicate

Create an empty 3.6 pipenv, and try to execute the following script:

```py
from typing import List

NAMES: List[str] = []

print("It works!")
```

I have set up a repo as per the above steps here: https://github.com/silasary/pipenv_issue_1465

**Comment by dschaller** [comment] 2018-02-22 04:37
@silasary do you hit the same issue if you run `pipenv run python example.py`?

**Comment by uranusjr** [comment] 2018-02-22 05:21
`pipenv run python example.py` should work. This likely happens only on Windows. When you run the script directly (without calling `python` explicitly), the [Python Launcher](https://www.python.org/dev/peps/pep-0397/) is used to invoke the script. The Python Launcher is usually able to detect whether it is in a virtual environment (and use the “correct” Python under the circumstance), but maybe `pipenv run` missed some environment setup so the virtualenv Python is not picked up correctly.

As a confirmation, what does this command give you in a new command prompt?

```
$ py --version
```

**Comment by uranusjr** [comment] 2018-02-22 05:31
From the PEP and the launcher’s source, it seems to use the environment variable `VIRTUAL_ENV` to do the detection. This is likely a consequence of #829, which in turn is caused by pypa/virtualenv#1057.

Development of Virtualenv has unfortunately staled for quite a while, and the proposed fix is probably not going be merged in near future. All we can do here is to recommend users to always use `pipenv run python` (unless we’re going to either take over Virtualenv maintenance, or drop it completely…).

**Comment by silasary** [comment] 2018-02-22 05:31
`pipenv run python example.py` runs properly.

`py --version` gives me `Python 3.6.1`

**Closed** 2018-02-22 05:32 UTC
Labels: windows, wontfix
