### ISSUE TITLE
What's going on with the project?

### ISSUE THREAD

**Issue by JBKahn** [pypa/pipenv#3978] opened 2019-10-08 00:18 UTC
Having not heard back to [my post on the release issue](https://github.com/pypa/pipenv/issues/3369) and it having been almost a year since the last release, I'm somewhat concerned about the survival of the project. I would genuinely like to provide support if I can but I don't really know where the project is at. The lack of any recent releases makes me imagine that one of these is true:

1. Master is broken and has been for a long time.
1. The state of master is 'worse' than the last release i.e. removed features or functionality that needs to be put back.

If master is healthy and has bug fixes and features, what has blocked making a release for so long? Is there a way to contribute? As a user of pipenv I'm concerned that it's dead even though I see master has commits in it. I'm not sure where else to post or ask this.

**Comment by edisongustavo** [comment] 2019-10-08 12:02
I'm wondering the same thing. I'm trying to decide which dependency manager to use (pipenv, poetry, pip-tools) and while pipenv seemed to be a good choice, this lack of maintenance is not helping.

**Comment by AlJohri** [comment] 2019-10-08 22:30
linking https://github.com/pypa/pipenv/issues/3742

**Comment by Jamim** [comment] 2019-10-08 23:01
To be honest, I personally believe that it's worth to just forget the `pipenv` since there is a much better and healthy [alternative](https://github.com/sdispater/poetry), so it's better to focus on improving it.

**Comment by RonRothman** [comment] 2019-10-11 23:29
FWIW, we've started to directly use [`pip-tools`](https://github.com/jazzband/pip-tools) (comprising `pip-compile` and `pip-sync`) with a fair amount of success. It's a bit lower level that Pipenv (we wrote some tooling around it), but it's been very stable, is actively maintained, and gets the job done nicely.

**Comment by brainwane** [comment] 2020-03-04 21:56
I spoke with @techalchemy in IRC today and pipenv now has an update in https://github.com/pypa/pipenv/issues/3369#issuecomment-594875477 .

**Comment by brainwane** [comment] 2020-03-25 21:15
@JBKahn Thanks for opening this issue, and thanks to everyone for sharing your thoughts and concerns.

Pipenv is working toward a new release -- see #3369 for specific details. The goal is to get that out this month.

I helped @techalchemy write a new update email he's just posted [on distutils-sig](https://mail.python.org/archives/list/distutils-sig@python.org/thread/EY2KKSWVCYBVO2RB6OMD7TFOWO35B2WG/) (mirrored [on the pypa-dev list](https://groups.google.com/forum/#!msg/pypa-dev/qLO8Pd4i_Co/AHUkg-2pBgAJ)). Dan notes:

> As some of you may already know, I recently changed jobs and am now working for Canonical where I have part of my time allocated to open source work in general (and pipenv in particular).

So: thanks, Canonical!

Dan's email also includes a few ways you can help, directly and indirectly, to expedite this release.

I'm going to close this issue now as a duplicate of #3369, but that is not meant as any disrespect to any of you who have commented, reacted, or subscribed to this issue -- just to centralize where people should look for updates. Thanks again.

**Closed by brainwane** 2020-03-25 21:15 UTC
Labels: Type: Maintenance :construction:
