### ISSUE TITLE
Unable to install mmcv-full with pipenv.

### ISSUE THREAD

**Issue by Keiku** [pypa/pipenv#5056] opened 2022-04-19 03:44 UTC
### Issue description

Unable to install mmcv-full with pipenv.

### Expected result

Can be installed without problems

### Actual result

An error will occur as shown below.

```none
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ pipenv lock     12:10:07
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (a7d644)!
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ pipenv sync     12:10:51
Installing dependencies from Pipfile.lock (a7d644)...
An error occurred while installing https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-manylinux1_x86_64.whl#egg=mmcv-full --hash=sha256:7459572935a7ba6293fee619c205583d76cd832464ffe9f15115ebe0396450e4! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:20
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting mmcv-full==1.4.7
[pipenv.exceptions.InstallError]:   Using cached https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-manylinux1_x86_64.whl (47.7 MB)
[pipenv.exceptions.InstallError]: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
[pipenv.exceptions.InstallError]:     mmcv-full==1.4.7 from https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-manylinux1_x86_64.whl#egg=mmcv-full (from -r /tmp/pipenv-vznfd55f-requirements/pipenv-1z06yhcm-requirement.txt (line 1)):
[pipenv.exceptions.InstallError]:         Expected sha256 7459572935a7ba6293fee619c205583d76cd832464ffe9f15115ebe0396450e4
[pipenv.exceptions.InstallError]:              Got        95dde9139fec10789406aa13e4824c3187805f52f23acd5aa6b924094be5e427
ERROR: Couldn't install package: mmcv-full
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:02
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ 
```

### Steps to replicate

For commands only, it can be reproduced as follows.

```bash
pip install pipenv
pipenv --python 3.8.6
pipenv install "mmcv-full==1.4.7" -i https://download.openmmlab.com/mmcv/dist/cu113/t
orch1.10.0/index.html
```

Another method is to write it in the Pipfile in advance and then `lock` and `sync`.

```Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mmcv-full = {file = "https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-manylinux1_x86_64.whl"}
torch = {file = "https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp38-cp38-linux_x86_64.whl"}
torchvision = {file = "https://download.pytorch.org/whl/cu113/torchvision-0.11.0%2Bcu113-cp38-cp38-linux_x86_64.whl"}
mmdet = "==2.23.0"

[dev-packages]

[requires]
python_version = "3.8"
```

After creating the above Pipfile, do `pipenv lock` and `pipenv sync`.

```bash
pipenv lock
pipenv sync
```

-------------------------------------------------------------------------------

**Environment**

It is running in the following environment.

```
⋊> ~ nvidia-container-cli info                                               12:05:06
NVRM version:   465.19.01
CUDA version:   11.3

Device Index:   0
Device Minor:   0
Model:          NVIDIA Tesla T4
Brand:          Nvidia
GPU UUID:       GPU-b2fd7cfe-e194-bdb7-3a2a-78a5d8528d38
Bus Location:   00000000:00:1e.0
Architecture:   7.5
⋊> ~ lsb_release -a                                                          12:05:32
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
⋊> ~  
```

**Comment by matteius** [comment] 2022-04-19 03:51
@Keiku Sometimes things are right on time -- I think I both encountered this tonight with the re-vendoring of pip 22.0.4 from master and I think I may have fixed it as well by making another update to the `collect_hashes` method.  Would you be able try the master branch?  `python setup.py develop --user` after cloning it is how I do it, but there are other ways.  I assume you are reporting this issue for `2022.4.8`?

**Comment by matteius** [comment] 2022-04-19 03:52
Specifically I think this is what will fix it:  https://github.com/pypa/pipenv/pull/4966/commits/11ac5befad53f6b80b9e1f1727daa9b5d43f3042

**Comment by Keiku** [comment] 2022-04-19 04:15
@matteius Thank you for your reply. I'm using version `2022.4.8`. Which version wouldn't this problem occur?

```
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ pipenv --version
pipenv, version 2022.4.8
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ 
```

**Comment by Keiku** [comment] 2022-04-19 04:21
I'll try the main branch for now.

**Comment by matteius** [comment] 2022-04-19 04:24
@Keiku It has only been merged into the main branch, not released to pypi yet.  So you could do:  `pip install git+https://github.com/pypa/pipenv.git --user` which would help me verify it won't be an issue going forward.

Otherwise you could roll back to:  `2022.3.28` for the time being.

**Comment by Keiku** [comment] 2022-04-19 05:09
@matteius I was able to install it with `pipenv==2022.3.28`. Thank you very much. I haven't tried the main branch yet due to a PATH setting issue. If I have time, I will report it.

**Comment by matteius** [comment] 2022-04-19 05:11
@Keiku I suspect the path issue is from using the `--user` flag and doing a user-level install, which is preferred but isn't on the PATH by default.  If you do a global install you can drop the `--user` flag our add to your PATH something like:  `export PATH=$PATH:~/.local/bin`

**Comment by Keiku** [comment] 2022-04-19 07:07
@matteius In pipenv version `2022.4.9.dev0`, the below error occur with `lock`. I'm not sure why this is happening.

```
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ pipenv --version
pipenv, version 2022.4.9.dev0
⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ pipenv lock     15:41:16
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!

Traceback (most recent call last):
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 857, in <module>
    main()
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 843, in main
    _main(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 822, in _main
    resolve_packages(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 771, in resolve_packages
    results, resolver = resolve(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 751, in resolve
    return resolve_deps(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 1066, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 862, in actually_resolve_deps
    resolver.resolve()
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 661, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 168, in _add_to_criteria
    candidates=build_iter_view(matches),
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/structs.py", line 164, in build_iter_view
    matches = list(matches)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/factory.py", line 452, in <genexpr>
    and all(req.is_satisfied_by(c) for req in requirements[identifier])
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/factory.py", line 452, in <genexpr>
    and all(req.is_satisfied_by(c) for req in requirements[identifier])
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/requirements.py", line 93, in is_satisfied_by
    return spec.contains(candidate.version, prereleases=True)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/vendor/packaging/specifiers.py", line 728, in contains
    item = parse(item)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/anasys/.local/lib/python3.9/site-packages/pipenv/vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

⋊> /m/n/k/c/work on dev-mmdet-2.23.0 ⨯ 
```

**Comment by matteius** [comment] 2022-04-20 04:51
Thanks @Keiku -- I was able to reproduce something similar with your example on linux yesterday though my system doesn't support those specific wheels on linux because its in a VM so I grabbed the windows versions and tried your version with 3.8 and also the latest with 3.10 and both succeeded, was not able to get that TypeError tonight.

```
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-5056
$ pipenv lock
Creating a virtualenv for this project...
Pipfile: C:\Users\matte\Projects\pipenv-triage\pipenv-5056\Pipfile
Using c:/users/matte/.pyenv/pyenv-win/shims/python3.bat (3.8.10) to create virtualenv...
[ ===] Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 968ms
  creator CPython3Windows(dest=C:\Users\matte\.virtualenvs\pipenv-5056-E0-NNWzz, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3
.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv)
    added seed packages: pip==22.0.4, setuptools==60.9.1, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\matte\.virtualenvs\pipenv-5056-E0-NNWzz
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (df20b9)!

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-5056
$ ls
Pipfile  Pipfile.good  Pipfile.good.38  Pipfile.lock  Pipfile.lock.good.38  Pipfile.old

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-5056
$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "a335d49e7479479f2c535a92dbeb6cd28d7c383a4e7a85074751550b94df20b9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "torch": {
            "file": "https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp38-cp38-win_amd64.whl",
            "hashes": [
                "sha256:969109d6ceef35992fd573f90342a1078399274f5791c060f7a112674bd74e66"
            ],
            "index": "pypi",
            "version": "==1.10.0+cu113"
        },
        "typing-extensions": {
            "hashes": [
                "sha256:6657594ee297170d19f67d55c05852a874e7eb634f4f753dbd667855e07c1708",
                "sha256:f1c24655a0da0d1b67f07e17a5e6b2a105894e6824b92096378bb3668ef02376"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==4.2.0"
        }
    },
    "develop": {}
}

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-5056
$ pipenv sync
Installing dependencies from Pipfile.lock (df20b9)...
  ================================ 2/2 - 00:01:40
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
```

**Comment by matteius** [comment] 2022-04-20 05:09
I was just able to reproduce it @Keiku --  It works fine to have a Pipefile like this with everything except torchvision, but as soon as I add that in, I get the `TypeError: expected string or bytes-like object` error.

```
# Good Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mmcv-full = {file = "https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-win_amd64.whl"}
torch = {file = "https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp38-cp38-win_amd64.whl"}
torchvision = {file = "https://download.pytorch.org/whl/cu113/torchvision-0.11.0%2Bcu113-cp38-cp38-win_amd64.whl"}
mmdet = "==2.23.0"

[dev-packages]

[requires]
python_version = "3.8"
```

```
# Bad Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mmcv-full = {file = "https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-win_amd64.whl"}
torch = {file = "https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp38-cp38-win_amd64.whl"}
mmdet = "==2.23.0"

[dev-packages]

[requires]
python_version = "3.8"
```

Going to investigate further but I suspect maybe something not compatible with that specific wheel of torchvision and the new pip 22.0.4 we vendor'd into pipenv.

**Comment by matteius** [comment] 2022-04-20 05:16
If I upgrade `torch` and `torchvision` to the next version the lock works fine so I do think it has to do with something in that specific `torchvision` wheel.  

```
# This works and has all of the dependencies 
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mmcv-full = {file = "https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.7-cp38-cp38-win_amd64.whl"}
torch = {file = "https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp38-cp38-win_amd64.whl"}
torchvision = {file = "https://download.pytorch.org/whl/cu113/torchvision-0.12.0%2Bcu113-cp38-cp38-win_amd64.whl"}
mmdet = "==2.23.0"

[dev-packages]

[requires]
python_version = "3.8"
```

**Comment by Keiku** [comment] 2022-04-20 05:25
@matteius Thank you for your detailed investigation. I didn't realize it was a torch and torchvision version issue. Thank you very much. If I have a similar problem in the future, are there any tips to solve it?

**Comment by matteius** [comment] 2022-04-20 05:38
@Keiku Just to be clear you did spot a real issue in `2022.4.8` for the hash generation not matching the installation for some of these wheel type package link installs.  That specifically has been fixed in the main branch in the same PR that vendored in the new version of pip and packaging, which seem to have an issue with the older version of `torchvision` though I have not yet been able to pin-point what is specifically different about that package or why it worked before.   I would like to continue to investigate as I have time to do so, but the fact that the newer version of torchvision did not have an issue at this step seems suspicious something in the METADATA of the wheel not quite up to standard that newer pip/packaging is expecting.  That is just my current theory.

**Comment by Keiku** [comment] 2022-04-21 01:58
@matteius Thank you for the various surveys. Personally, there is no problem with close, but I will leave it to you to decide close based on the status of the remaining tasks.

**Comment by matteius** [comment] 2022-04-21 02:01
Thanks @Keiku  -- there should be a new release in an hour or so that will included the latest changes and the fix for the original issue.  The `torchvision` version error difference remains a mystery, but I will keep it in mind if we get any other issue reports with the same error like that.  May end up closing at some point soon based on your positive feedback.  Thanks!

**Closed** 2022-06-27 09:16 UTC
Labels: triage

**Comment by Keiku** [comment] 2022-06-27 13:17
Thank you for closing.
