### ISSUE TITLE
Do a release already

### ISSUE THREAD

**Issue by tleonhardt** [pypa/pipenv#4109] opened 2020-01-23 05:15 UTC
I did a `pip` install of `pipenv` from GitHub using:
```sh
pip3 install -U git+git://github.com/pypa/pipenv
```

I noticed that it fixed a few bugs and also **very noticeably improved the previously crappy performance of pipenv**.  

You folks have done some good work maintaining this project.  I think the Python community would benefit by you doing a release to PyPI.

**Comment by dangelsaurus** [comment] 2020-01-24 03:00
looks like #1356 is fixed?

**Comment by tleonhardt** [comment] 2020-02-12 03:04
#4058 has some info in regards to this

**Comment by Flimm** [comment] 2020-02-24 09:49
This issue seems like a duplicate of https://github.com/pypa/pipenv/issues/3742

**Comment by brainwane** [comment] 2020-03-06 02:15
Thanks for the note! Am closing as a duplicate of #3742. Thanks again.

**Closed by brainwane** 2020-03-06 02:15 UTC
Labels: triage
