### ISSUE TITLE
TypeError in delegator if path contains non-ASCII

### ISSUE THREAD

**Issue by FrancoisGG** [pypa/pipenv#3072] opened 2018-10-21 17:51 UTC
When running "pipenv install requests", I have the following warning  

virtualenv.py:1041: **DeprecationWarning**: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

---------------------------------------------------
Here is the full information I get on the shell:
---------------------------------------------------

```
Creating a virtualenv for this project…
Pipfile: D:\MatchVision\CameraMatch\Pipfile
Using c:\python37\python.exe (3.7.0) to create virtualenv…
Already using interpreter c:\python37\python.exe
Using base prefix 'c:\\python37'
C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in C:\Users\FrançoisGuély\.virtualenvs\CameraMatch-_4iFpTqG\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 770, in call_subprocess
    line = line.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 31: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 2343, in <module>
    main()
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 947, in create_environment
    download=download,
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 772, in call_subprocess
    line = line.decode(fs_encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 31: invalid continuation byte

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\cli\command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\core.py", line 1724, in do_install
    pypi_mirror=pypi_mirror,
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\core.py", line 565, in ensure_project
    pypi_mirror=pypi_mirror,
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\core.py", line 500, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\core.py", line 901, in do_create_virtualenv
    click.echo(crayons.blue("{0}".format(c.err)), err=True)
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\delegator.py", line 146, in err
    return self._pexpect_out
  File "C:\Users\FrançoisGuély\AppData\Roaming\Python\Python37\site-packages\pipenv\vendor\delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: can only concatenate str (not "type") to str
```

------------------------------------------------------------
AND HERE ARE THE ENVIROMENT RELATED INFORMATION :
-----------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'C:\\Users\\FranþoisGuÚly\\AppData\\Roaming\\Python\\Python37\\site-packages\\pipenv'`

Python location: `'c:\\python37\\python.exe'`

Python installations found:

  - `3.7.0`: `C:\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONFIGSETROOT`
  - `DASHLANE_DLL_DIR`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `INTEL_DEV_REDIST`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MIC_LD_LIBRARY_PATH`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenvûspecific environment variables:

Debugûspecific environment variables:

  - `PATH`: `C:\Python37\Scripts\;C:\Python37\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\chocolatey\bin;C:\Users\FranþoisGuÚly\AppData\Local\Microsoft\WindowsApps;C:\Users\FranþoisGuÚly\AppData\Roaming\Dashlane\6.1841.0.13779\bin\Firefox_Extension\{442718d9-475e;C:\Users\FranþoisGuÚly\AppData\Roaming\Python\Python37\Scripts\`

---------------------------

</details>

**Comment by uranusjr** [comment] 2018-10-22 06:06
Looks like there are two issues here. The DeprecationWarning one is tracked in pypa/virtualenv#955, nothing we can do here.

The other seems to be a reporting error with non-ASCII in the path? I’m modifying the title to reflect that.

**Comment by techalchemy** [comment] 2018-10-22 11:59
In that case this is a duplicate of #2859, closing in favor of that

**Closed** 2018-10-22 12:00 UTC
Labels: vendored dependencies
