### ISSUE TITLE
Pipenv fails on Windows if > or < are used in a version spec

### ISSUE THREAD

**Issue by LegoStormtroopr** [pypa/pipenv#1205] opened 2017-12-14 05:59 UTC
[Unable to install a virtualenv on Windows](https://ci.appveyor.com/project/LegoStormtroopr/aristotle-metadata-registry-361e5/build/1.0.684/job/px965t9jtk3esdqs) 
[Link goes to an appveyor failure]

Sample Pip file
```
[[source]]

verify_ssl = true
name = "pypi"
url = "https://pypi.python.org/simple"


[packages]

coverage = '>=4.4.1'


[dev-packages]

[requires]

python_version = "3.5"


[[source]]

verify_ssl = true
url = "https://pypi.python.org/simple/"
```

##### Describe your environment

1. OS Type - Windows 10
1. Python version: `$ python -V` - Python 3.5.2
1. Pipenv version: `$ pipenv --version` - pipenv, version 9.0.0

##### Expected result

Virtualenv is installed

##### Actual result

Virtual env fails 

```
PS C:\Users\spe130\git\aristotle-metadata-registry> pipenv install --python C:\Users\spe130\AppData\Local\Programs\Python\Python35\python.exe
```
```
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using C:\Users\spe130\AppData\Local\Programs\Python\Python35\python.exe to create virtualenv…
Running virtualenv with interpreter C:\Users\spe130\AppData\Local\Programs\Python\Python35\python.exe
Using base prefix 'C:\\Users\\spe130\\AppData\\Local\\Programs\\Python\\Python35'
New python executable in C:\Users\spe130\.virtualenvs\aristotle-metadata-registry-QU7S9wP3\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\spe130\.virtualenvs\aristotle-metadata-registry-QU7S9wP3
Pipfile.lock (c62754) out of date, updating to (47bf12)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "C:\Users\spe130\AppData\Local\Programs\Python\Python35\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv==9.0.0', 'console_scripts', 'pipenv')()
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\vendor\click\core.py", line 722,
 in __call__
    return self.main(*args, **kwargs)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\vendor\click\core.py", line 697,
 in main
    rv = self.invoke(ctx)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\vendor\click\core.py", line 1066
, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\vendor\click\core.py", line 895,
 in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\vendor\click\core.py", line 535,
 in invoke
    return callback(*args, **kwargs)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\cli.py", line 1859, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\cli.py", line 1303, in do_init
    do_lock(system=system, pre=pre)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\cli.py", line 1090, in do_lock
    deps = convert_deps_to_pip(project.packages, project, r=False, include_index=True)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\project.py", line 364, in packages
    return self._build_package_list('packages')
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\project.py", line 84, in _build_package_list
    any(is_installable_file(i) for i in [k, v]) or
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\project.py", line 84, in <genexpr>
    any(is_installable_file(i) for i in [k, v]) or
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\site-packages\pipenv\utils.py", line 873, in is_installable_file
    return lookup_path.is_file() or (lookup_path.is_dir() and
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\pathlib.py", line 1332, in is_file
    return S_ISREG(self.stat().st_mode)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\pathlib.py", line 1126, in stat
    return self._accessor.stat(self)
  File "c:\users\spe130\appdata\local\programs\python\python35\lib\pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '>=4.4.1'
```

##### Steps to replicate

See above

##### Workaround

```
[[source]]

verify_ssl = true
name = "pypi"
url = "https://pypi.python.org/simple"


[packages]

coverage = '~=4.4.1'

[dev-packages]

[requires]

python_version = "3.5"


[[source]]

verify_ssl = true
url = "https://pypi.python.org/simple/"
```

Output
```
PS C:\Users\spe130\git\aristotle-metadata-registry> pipenv install --python C:\Users\spe130\AppData\Local\Programs\Pytho
n\Python35\python.exe
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using C:\Users\spe130\AppData\Local\Programs\Python\Python35\python.exe to create virtualenv…
Running virtualenv with interpreter C:\Users\spe130\AppData\Local\Programs\Python\Python35\python.exe
Using base prefix 'C:\\Users\\spe130\\AppData\\Local\\Programs\\Python\\Python35'
New python executable in C:\Users\spe130\.virtualenvs\aristotle-metadata-registry-QU7S9wP3\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\spe130\.virtualenvs\aristotle-metadata-registry-QU7S9wP3
Pipfile.lock (426b1f) out of date, updating to (c62754)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (c62754)!
Installing dependencies from Pipfile.lock (c62754)…
  ================================ 1/1 - 00:00:03
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

Testing it:
```
PS C:\Users\spe130\git\aristotle-metadata-registry> pipenv run coverage
Code coverage for Python.  Use 'coverage help' for help.
```

**Comment by LegoStormtroopr** [comment] 2017-12-14 06:05
I only used the tilde form (`~=`) because of this line, but I'm not sure why it works.

https://github.com/pypa/pipenv/blob/master/pipenv/utils.py#L874

**Comment by nateprewitt** [comment] 2017-12-14 07:27
Thanks for taking the time to report this @legostormtroopr! We actually have a patch for this already merged on master (#1183) that will be available in the next release.

**Comment by nateprewitt** [comment] 2017-12-14 07:28
Hit enter a little too fast, I'm going to close this out because the issue is resolved. Thanks again!

**Closed by nateprewitt** 2017-12-14 07:28 UTC

**Comment by LegoStormtroopr** [comment] 2017-12-15 00:02
Cheer for the info. Any clue on when the next release is coming out?

**Comment by nateprewitt** [comment] 2017-12-15 00:11
@LegoStormtroopr last week but our testing environment got a bit borked when we moved over to pypa. Still trying to get a point of contact to get that resolved. Once we can verify a stable build, I'll cut a release. Hopefully this weekend at the latest. 🤞

**Comment by LegoStormtroopr** [comment] 2017-12-15 00:23
Cheers. No rush, just planning. Thanks for the update, and thanks for this amazing tool!
