### ISSUE TITLE
Issue when installing rasa

### ISSUE THREAD

**Issue by serranomorante** [pypa/pipenv#3804] opened 2019-06-19 22:36 UTC
Hello. I'm having some trouble installing Rasa (lastest version: 1.1.3) with pipenv.
Just the installation works, but the process of "locking" presents issues because it triggers out the timeout after several minutes of waiting.
My pipenv works just fine with other packages, but only with rasa I've been experimenting this issue.
I absolutely don't understand what the problem is.
Please help.
Thanks!

## Steps to reproduce
1. Install python 3.7
2. Install pip (in case of linux)
3. Install pipenv
Then, in the directory of choice:
`pipenv install rasa`

## Environment
Same error in:
1. Windows 10 64 bits with Python 3.7 and lastest versions of **pip** and **pipenv**
2. Ubuntu 18.04 64 bits with Python 3.6 and lastest versions of **pip** and **pipenv**

## Source

<details><summary>Pipfile</summary>
[[source]] 
name = "pypi" 
url = "https://pypi.org/simple" 
verify_ssl = true 

[dev-packages]
pylint = "*" 

[packages] 
rasa = "*" 

[requires] 
python_version = "3.6"
</details>

<details><summary>Error log</summary>

```bash
$ pipenv install

Pipfile.lock not found, creating…  

Locking [dev-packages] dependencies…  

Success!  

Locking [packages] dependencies…  

Traceback (most recent call last):  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 109, in expect_loop  

    return self.timeout()  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 82, in timeout  

    raise TIMEOUT(msg)  

pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x0000013334182DD8>  

searcher: searcher_re:  

    0: re.compile('\n')  

   

During handling of the above exception, another exception occurred:  

   

Traceback (most recent call last):  

  File "c:\users\research\anaconda3\lib\runpy.py", line 193, in _run_module_as_main  

    "__main__", mod_spec)  

  File "c:\users\research\anaconda3\lib\runpy.py", line 85, in _run_code  

    exec(code, run_globals)  

  File "C:\Users\research\Anaconda3\Scripts\pipenv.exe\__main__.py", line 9, in <module>  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__  

    return self.main(*args, **kwargs)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main  

    rv = self.invoke(ctx)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke  

    return _process_result(sub_ctx.command.invoke(sub_ctx))  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke  

    return ctx.invoke(self.callback, **ctx.params)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke  

    return callback(*args, **kwargs)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func  

    return ctx.invoke(f, obj, *args, **kwargs)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke  

    return callback(*args, **kwargs)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func  

    return f(get_current_context(), *args, **kwargs)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\cli\command.py", line 254, in install  

    editable_packages=state.installstate.editables,  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\core.py", line 1874, in do_install  

    keep_outdated=keep_outdated  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\core.py", line 1244, in do_init  

    pypi_mirror=pypi_mirror,  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\core.py", line 1068, in do_lock  

    lockfile=lockfile  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\utils.py", line 649, in venv_resolve_deps  

    c = resolve(cmd, sp)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\utils.py", line 517, in resolve  

    result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\delegator.py", line 215, in expect  

    self.subprocess.expect(pattern=pattern, timeout=timeout)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 341, in expect  

    timeout, searchwindowsize, async_)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 369, in expect_list  

    return exp.expect_loop(timeout)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 119, in expect_loop  

    return self.timeout(e)  

  File "c:\users\research\anaconda3\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 82, in timeout  

    raise TIMEOUT(msg)  

pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x0000013334182DD8>  

searcher: searcher_re:  

    0: re.compile('\n')  

<pexpect.popen_spawn.PopenSpawn object at 0x0000013334182DD8>  

searcher: searcher_re:  

    0: re.compile('\n') ```

**Comment by frostming** [comment] 2019-06-20 01:09
The link is not available, please follow the issue template to fill in the information.

**Comment by serranomorante** [comment] 2019-06-24 21:52
@frostming hey, still need more information? The update have been done.

**Comment by frostming** [comment] 2019-06-25 01:36
@serranomorante I can't reproduce the issue, but it took 8 minutes to be done, mainly on the resolution process. `rasa` itself has 112 sub-dependencies, making it super slow for resolution.

**Comment by serranomorante** [comment] 2019-06-25 01:54
@frostming maybe in more slower machines it just trigger the timeout?

I have an intel i5 6gb ram 2.40GHz, dual core.

**Comment by frostming** [comment] 2019-07-15 05:48
It's a connection issue, and there are no more suggestions we can give, close it now.

**Closed by frostming** 2019-07-15 05:48 UTC
