### ISSUE TITLE
If this project is dead, just tell us

### ISSUE THREAD

**Issue by thieman** [pypa/pipenv#4058] opened 2019-12-13 01:22 UTC
Duplicate of https://github.com/pypa/pipenv/issues/3742 and the 6 or so similar issues already linked there.

As of writing, it's been 381 days and 669 commits since a release. Please consider the impact of the project maintainers' silence regarding the lack of a release on:

- people who are continuing to contribute PRs that will never see a release
- people who are deciding today, without knowing the project is dead, to commit their own projects to using pipenv
- the existing user base, who again may not realize it's time to move on and are continuing to deal with bugs that have been fixed in master for months

I'm not mad, I don't think you're bad people, but the least y'all can do is be honest with us about whether or not we should move on to something else. If there's actually a chance that we'll get a new release ever, then great. If not, tell us.

**Comment by ovalseven8** [comment] 2019-12-13 09:54
Yesterday, [poetry](https://github.com/python-poetry/poetry) version 1.0.0 was released. It may be a good replacement for many pipenv users.

**Comment by ociule** [comment] 2019-12-13 14:26
I have been using pipenv master for a while for this reason. One can do it with:

`pip install git+https://github.com/pypa/pipenv.git@master`

There are countless fixes that are in master but not in a release yet.

I know that maintainers are overworked and I'm grateful that they have found time for patches and reviewing PRs. It would be great if this discussion brings in new volunteers to help.

**Comment by jvanwinkle-earnup** [comment] 2019-12-13 15:19
Quite dead

**Comment by ObserverOfTime** [comment] 2019-12-13 15:22
I've been using poetry for a while and it's honestly a lot better.

**Comment by MiguelPF** [comment] 2019-12-13 15:23
We just committed to using it in one of the projects and now we have to revert I guess we will try poetry.

**Comment by MostAwesomeDude** [comment] 2019-12-13 15:28
I've been using [Nix](https://nixos.org/nix/) for a while, and the [nixpkgs](https://nixos.org/nixpkgs/manual/#python) support for Python is pretty good.

**Comment by pauloxnet** [comment] 2019-12-13 15:30
I'm still using **[pip-tools](https://github.com/jazzband/pip-tools)** for personal and work projects, it works very well and it's a **[Jazzband](https://github.com/jazzband)** project.

**Comment by softinio** [comment] 2019-12-13 16:03
I really wish the mention of pipenv was removed from here: https://packaging.python.org/guides/tool-recommendations/#application-dependency-management

Personally I highly recommend and wish we had a community effort to use `Nix` but other than that Poetry looks pretty good to me.

**Comment by richardARPANET** [comment] 2019-12-13 16:23
All hail vanilla pip.

**Comment by benatkin** [comment] 2019-12-13 17:55
If thousands of people are using it, it isn't dead. I'm using it, and had issues which I resolved by docs and issue comments, but I haven't had to install it from git. I don't want to switch to Poetry, not because I don't like change, but because it doesn't seem very pythonic to me (especially toml,  which is not just against signficant indentation but minimizes use of indentation in general). No need to go this route, when it's easier and better for the community figure out why it's so long between releases, and fix it. If you don't use it, nothing is forcing us to, though having it under pypa makes it seem more official than it should be, and perhaps it should be moved to its own organization.

**Comment by n-cc** [comment] 2019-12-13 18:07
> If thousands of people are using it, it isn't dead. 

Want to know how many people are still using Windows XP?

**Comment by techalchemy** [comment] 2019-12-13 18:18
Thanks for your concern -- The project is not dead; it has been held back by several subdependencies and a complicated release process. This is on me and the next release (which is actually almost finished) seeks to address a large number of these underlying issues including a single point of failure in the maintainership chain.  Unfortunately that requires a substantial amount of documentation which is also currently in progress.

I recently accepted a role that affords me time to tackle these issues so I have been making progress, albeit slowly.  I apologize for failing to be more communicative but this is incredibly important to everyone, myself included, and updates will be cascading to pipenv shortly.

**Comment by slhck** [comment] 2019-12-13 18:24
Thanks for the sign of life and the positive message.

As mentioned in several comments in other issues, people have been repeatedly asking how they can help to get the next release done. None of these comments were ever really addressed with concrete suggestions ("help fix the unit tests", "look at issue XYZ", ...), and up until now there were not even any critical issues open. I truly think that there are enough people who **want** to help and invest time, but they simply don't know where their help is needed.

**Comment by erinxocon** [comment] 2019-12-13 21:41
I can say that I have not been able to work on pipenv in the last year due to many things in my personal and work life.  Managing an open source project is hard, when I started work on pipenv way back when I had a lot more free time than I do now.  I appreciate the effort @techalchemy and others have put in so so much! It's hard when you can't dedicate all your time to an open source project that I love because real world stuff :/ I do agree that we could advertise areas we need help in better; I agree with @slhck, I think there are enough people who want to help and invest time!

**Comment by hartwork** [comment] 2019-12-16 13:56
> [..] and updates will be cascading to pipenv shortly.

:+1: We have [updated pipenv to 2018.11.26 in Gentoo now](https://github.com/gentoo/gentoo/commit/c9138d9a4d1bcd4c1a5e5c1086d354717890c0a9) and are looking forward to the next pipenv release.

**Comment by and-semakin** [comment] 2019-12-17 11:58
@techalchemy let's create some communication channel, for example, Gitter room, so that people can quickly reach maintainers and ask what help do you need. I personally would be happy to help you fix some bugs or decrease burden.

**Comment by softinio** [comment] 2019-12-17 16:23
Be great if gitter can be avoided for this purpose they have deprecated their mobile apps and have become unusable for a lot of people. 

Pallets project use discord which works really well and highly recommend or Zulip as python based.

**Comment by guhcampos** [comment] 2019-12-18 16:45
There is a #pipenv channel in the Python Developers slack https://pythondev.slack.com/archives/C8UK1J3DM

**Comment by thernstig** [comment] 2020-01-13 12:14
Would be great if you can pin this issue :)

**Comment by penguinolog** [comment] 2020-02-13 12:53
Ok, looks like project is de-facto dead.

**Comment by hartwork** [comment] 2020-02-13 15:57
This message https://github.com/pypa/pipenv/issues/4058#issuecomment-565550646 by @techalchemy is two months old and there a no commits on `master` since then so I get where that impression comes from.

**Comment by JosefAssad** [comment] 2020-02-15 11:19
> Thanks for your concern -- The project is not dead

It's pining for the fjords?

**Comment by fridex** [comment] 2020-02-15 16:42
We maintain a fork of Pipenv called [thoth-pipenv](https://pypi.org/project/thoth-pipenv) in [1]. We released Pipenv from the current master branch to address some issues within our team. Feel free to use it If it helps.

There is also another lightweight tool called "[micropipenv](https://pypi.org/project/micropipenv)" [2] - it operates on Pipfile/Pipfile.lock as Pipenv would do, but there is no resolver or virtual environment management. It simply converts Pipfile/Pipfile.lock to pip-tools style requirements.{in,txt}. It might be helpful when migrating from Pipenv or for installing software that has already resolved Pipfile.lock.

[1] https://github.com/thoth-station/pipenv
[2] https://github.com/thoth-station/micropipenv

**Comment by hartwork** [comment] 2020-02-15 18:32
> > Thanks for your concern -- The project is not dead
> 
> It's pining for the fjords?

That's a [reference to Monty Python](https://www.urbandictionary.com/define.php?term=pining%20for%20the%20fjords), if anyone wonders

**Comment by laktak** [comment] 2020-02-16 16:39
> > Thanks for your concern -- The project is not dead
>
> It's pining for the fjords?

Certainly not for the domains:
```
http://pipenv.org/
This Domain Name Has Expired 
```

**Comment by fat0** [comment] 2020-02-16 22:33
https://pipenv.kennethreitz.org/en/latest/

**Comment by kstrauser** [comment] 2020-02-18 17:56
@fridex [dephell](https://github.com/dephell/dephell) is also brilliant for migrating between requirements.txt / pipenv / poetry.

**Comment by and-semakin** [comment] 2020-02-21 11:48
Also take a look to https://github.com/David-OConnor/pyflow, looks like an interesting alternative

**Comment by adamwojt** [comment] 2020-02-22 23:07
RIPenv :skull:

**Comment by sclarson** [comment] 2020-02-28 15:53
@techalchemy  Do you have any related issues or broken out work that could be done in this project or others to help with the release process?

**Comment by brainwane** [comment] 2020-03-04 21:56
I spoke with @techalchemy in IRC today and pipenv now has an update in https://github.com/pypa/pipenv/issues/3369#issuecomment-594875477 , including some issues that people could help with in order to help expedite the release.

**Comment by brainwane** [comment] 2020-03-25 20:49
@thieman hi and hope you're doing well! And thanks to everyone who commented in this issue.

Pipenv is working toward a new release -- see #3369 for specific details. The goal is to get that out this month.

I helped @techalchemy write a new update email he's just posted [on distutils-sig](https://mail.python.org/archives/list/distutils-sig@python.org/thread/EY2KKSWVCYBVO2RB6OMD7TFOWO35B2WG/) (mirrored [on the pypa-dev list](https://groups.google.com/forum/#!msg/pypa-dev/qLO8Pd4i_Co/AHUkg-2pBgAJ)). Dan notes:

> As some of you may already know, I recently changed jobs and am now working for Canonical where I have part of my time allocated to open source work in general (and pipenv in particular).

So: thanks, Canonical!

Dan's email also includes a few ways you can help, directly and indirectly, to expedite this release.

I'm going to close this issue now as a duplicate of #3369, but that is not meant as any disrespect to any of you who have commented, reacted, or subscribed to this issue -- just to centralize where people should look for updates. Thanks again.

**Closed by brainwane** 2020-03-25 20:49 UTC
Labels: Priority: Critical, Type: Maintenance :construction:, Type: Question :grey_question:
