### ISSUE TITLE
Issue templates refer to dead forum link

### ISSUE THREAD

**Issue by thernstig** [pypa/pipenv#2755] opened 2018-08-19 15:31 UTC
##### Issue description

The three issue templates refer to this forum, which does not work:
https://kenneth-reitz.uservoice.com/forums/913660-general

**Comment by gtalarico** [comment] 2018-09-02 00:08
Duplicate of: 
https://github.com/pypa/pipenv/issues/2809

**Closed** 2018-09-02 11:12 UTC

**Comment by thernstig** [comment] 2018-09-03 12:58
@gtalarico acutally #2809 was a duplicat of this one?
