### ISSUE TITLE
Unable install RPiO.GPIO

### ISSUE THREAD

**Issue by Batov** [pypa/pipenv#3375] opened 2018-12-13 12:59 UTC
Unable to install RPiO.GPIO on Raspberry Pi

```
pi@raspberrypi:~/Insurance-Tracker $ python3 -m pipenv install RPi.GPIO
Creating a virtualenv for this project…
Pipfile: /home/pi/Insurance-Tracker/Pipfile
Using /usr/bin/python3.5 (3.5.3) to create virtualenv…
⠙ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/pi/.local/share/virtualenvs/Insurance-Tracker-BOxuNttJ/bin/python3.5
Also creating executable in /home/pi/.local/share/virtualenvs/Insurance-Tracker-BOxuNttJ/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3.5
✔ Successfully created virtual environment!
Virtualenv location: /home/pi/.local/share/virtualenvs/Insurance-Tracker-BOxuNttJ
Installing RPi.GPIO…
✔ Installation Succeeded
Pipfile.lock (7ba4fa) out of date, updating to (703c34)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches rpi
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches rpi
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/pi/.local/lib/python3.5/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches rpi
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches rpi
No versions found
Was https://pypi.org/simple reachable?
```

**Comment by frostming** [comment] 2018-12-13 13:17
Duplicate of #3324 , Fixed in #3338

**Closed by frostming** 2018-12-13 13:17 UTC

**Comment by scwall** [comment] 2018-12-20 23:02
Hello I have the same problem, it does not seem fixed. I'm trying to install RPi.GPIO but it does not want to do it. However the package does exist. Thank you

```
ERROR: ERROR: Could not find a version that matches rpi-gpio
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches rpi-gpio
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches rpi-gpio
No versions found
Was https://pypi.org/simple reachable?

```

**Comment by frostming** [comment] 2018-12-21 00:51
@scwall Please read my previous comment. An issue closed does not necessarily mean that it is released, the issue gets closed by the merging of related PR. Please wait for the next release or use the master branch.

As a workaround, you can manually modify the package name in Pipfile to `RPi.GPIO` and all will work fine.

**Comment by lkgarrison** [comment] 2019-09-08 02:15
I just encountered this issue as well and was a bit surprised to see there hasn't been a release in 9 months. Can one be expected in the near future?

**Comment by andrewhao** [comment] 2020-09-13 06:39
This worked for me in my version of Pipfile:

```pipfile
"RPi.GPIO" = "*"
```
