### ISSUE TITLE
pipenv can't create when python in a readonly folder

### ISSUE THREAD

**Issue by ghost** [pypa/pipenv#3594] opened 2019-03-08 05:16 UTC
I use the Python from MS Store. And when i used 'pipenv install', have error 
`Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pipenv\core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pipenv\core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pipenv\core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pipenv\core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.`

Then I use 'python -m venv .venv' create a new venv, and active this. command 'pipenv install' work well.
Should pipenv can run if python in a readonly folder? and how could I fix it. 

    > pipenv --support | clip
﻿<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'C:\\Users\\***\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pipenv'`

Python location: `'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.752.0_x64__qbz5n2kfra8p0\\python.exe'`

Python installations found:

  - `3.7.2`: `C:\Users\***\AppData\Local\Microsoft\WindowsApps\python.exe`
  - `3.7.2`: `C:\Users\***\AppData\Local\Microsoft\WindowsApps\python3.7.exe`
  - `3.7.2`: `C:\Users\***\AppData\Local\Microsoft\WindowsApps\python3.exe`
  - `3.7.2`: `C:\Users\***\AppData\Local\Microsoft\WindowsApps\pythonw.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PYTHONUSERBASE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv?specific environment variables:

Debug?specific environment variables:

  - `PATH`: `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\***\AppData\Local\Microsoft\WindowsApps;C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts;`

---------------------------

Contents of `Pipfile` ('C:\\Users\\***\\PycharmProjects\\untitled2\\Pipfile'):

```toml

```

</details>

**Comment by frostming** [comment] 2019-03-08 05:29
Good to know someone is using Python from the MS store.

**Comment by frostming** [comment] 2019-03-08 05:30
Can you try creating a virtualenv with `virtualenv` command?

**Comment by WenqiangXie** [comment] 2019-03-12 06:47
> Can you try creating a virtualenv with virtualenv command?

Yes, and it's not work. Just 'python -m venv .env' work. It seem some problem of python form MS Store. And have to wait Python Foundation to fix it. I found the most problem is that python can't load dll file like before. I fix numpy dll load error when I add some code to load dll file by ctype in __init__.py (core). And now it's seem also have some problem to load dll file and I can't find which one.

I am sorry to ask this problem.

**Comment by techalchemy** [comment] 2019-03-17 06:50
hmmm /cc @zooba (not sure if this is relevant to you or not)

@WenqiangXie you may need to use `--site-packages` when running `pipenv install` in order for the libraries to link correctly, there was a bug in virtualenv recently.  Let us know if this helps

**Comment by zooba** [comment] 2019-03-18 15:33
I can't tell what the problem is here.

virtualenv is a long way behind venv right now. If you're relying on that, then you're probably going to see problems (until it starts using venv).

The DLL hell issues (numpy, etc.) have been resolved in numpy already, and I'm doing what I can from the Python side (which amounts to "potentially break lots of projects by making it possible for them to fix themselves").

**Comment by matteius** [comment] 2022-03-13 11:34
Closing this down as the original reporter is a ghost account now.

**Closed by matteius** 2022-03-13 11:34 UTC
Labels: Status: Needs More Information, Status: Awaiting Update :hourglass_flowing_sand:
