### ISSUE TITLE
Error when executing pipenv install

### ISSUE THREAD

**Issue by adlermedrado** [pypa/pipenv#1617] opened 2018-03-08 21:37 UTC
I'm getting an error when trying to run `pipenv install`

1. Ubuntu Linux
1. Python version: `Python 3.6.4`
1. Pipenv version: 11.1.5

##### Expected result

The dependencies install

##### Actual result
```
adler@masada:~/devel/project$ pipenv install 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
le "/home/adler/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 19, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 392, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 325, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 310, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 181, in from_line
    markers = Marker(markers)
  File "/home/adler/.local/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/packaging/markers.py", line 282, in __init__
    raise InvalidMarker(err_str)
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version in "3.4, 3.5, 3.6"; python_version in "3.4, 3.5, 3.6"', parse error at '; python'
```

**Comment by kennethreitz** [comment] 2018-03-08 21:42
Please provide your pipfile

**Comment by techalchemy** [comment] 2018-03-08 22:26
If you specified `somepackage; python_version in "3.4, 3.5, 3.6"'` as a marker, that's not a valid marker and will continue to throw this error

**Comment by adlermedrado** [comment] 2018-03-08 22:31
Hi.

This is the Pipfile.

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]

ipdb = "*"
pre-commit = "*"
pytest-cov = "*"
pytest-django = "*"
vcrpy = "*"
pgcli = "*"


[packages]

belogging = "*"
django = "*"
dj-database-url = "*"
django-cache-url = "*"
django-extensions = "*"
django-widget-tweaks = "*"
django-model-utils = "*"
prettyconf = "*"
"psycopg2" = "*"
unipath = "*"
requests = "*"
pillow = "*"
python-magic = "*"


[requires]

python_version = "3.6"
```

Thank you.

**Comment by kennethreitz** [comment] 2018-03-08 23:09
@notdaniel please provide your `Pipfile`. We can't fix the bug if we can't reproduce it :)

**Comment by notdaniel** [comment] 2018-03-08 23:12
@kennethreitz Apologies. Here is mine:

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]

pylint = "*"
honcho = "*"
yapf = "*"
konch = "*"
ptpython = "*"
rdbtools = "*"
python-lzf = "*"
"autopep8" = "*"


[packages]

aiohttp = "*"
cchardet = "*"
aiodns = "*"
click = "*"
logzero = "*"
python-telegram-bot = "*"
redis = "*"
walrus = "*"
blinker = "*"
pendulum = "*"
requests = "*"
pyrsistent = "*"
ccxt = "*"
boltons = "*"
ujson = "*"
prettyprinter = "*"
crayons = "*"
"delegator.py" = "*"
twitter = "*"
pytest = "*"
python-decouple = "*"


[requires]

python_version = "3.6"


[pipenv]

allow_prereleases = true```

**Comment by kennethreitz** [comment] 2018-03-08 23:13
Thank you. I'll work on a fix ASAP. It's been a long day, though — so might not be until tomorrow.

**Comment by kennethreitz** [comment] 2018-03-08 23:18
another report: https://github.com/pypa/pipenv/issues/1622

**Comment by techalchemy** [comment] 2018-03-09 04:01
This should be fixed in #1624 -- feel free to try it out and let me know: `pip install -e git+https://github.com/pypa/pipenv@bugfix/resolver-markers#egg=pipenv`

**Closed** 2018-03-09 06:44 UTC
Labels: bug, dependency resolution

**Comment by rosygupta** [comment] 2018-03-17 12:14
@techalchemy I'm facing this issue in pipenv 11.8.0 version. Can you please confirm if its fixed in it?

**Comment by msheiny** [comment] 2018-03-19 15:21
@kennethreitz im still hitting this issue in `11.8.3` . Anything else I can provide for debugging?

```
[[source]]

verify_ssl = true
url = "https://pypi.python.org/simple"
name = "pypi"


[packages]

django-logging-json = {git = "https://github.com/freedomofpress/django-logging.git", ref = "Remove_Elastic", editable = true}
pshtt-dependency-hell = {git = "https://github.com/nabla-c0d3/sslyze.git", ref = "ef357c2e76b6ba66f23db5fb1f95c7e8a6c13b9d", editable = true}
bleach = "*"
django-allauth = "==0.34.0"
django-allauth-2fa = "*"
django-anymail = {extras = ["mailgun"], version = ">=1.4"}
django-modelcluster = "*"
django-recaptcha = "*"
django-settings-export = "*"
django-webpack-loader = "*"
Django = "==1.11.5"
feedparser = "*"
gunicorn = "*"
lxml = "*"
markdown2 = ">=2.3.5"
pshtt = "==0.3.0"
psycopg2 = "*"
Pygments = "*"
unittest-xml-reporting = "*"
wagtail-django-recaptcha = "*"
wagtail-factories = "*"
wagtail-metadata = "*"
wagtail = "<1.13"
zxcvbn-python = "*"


[dev-packages]

factory_boy = "*"
# https://github.com/kevin1024/vcrpy/issues/342
vcrpy = "==1.11.0"

```

**Comment by techalchemy** [comment] 2018-03-20 05:42
@msheiny see #1791

**Comment by msheiny** [comment] 2018-03-20 12:51
thanks @techalchemy !! :heart:

**Comment by rosygupta** [comment] 2018-03-20 16:20
@msheiny How does that issue help? I didn't get it.

**Comment by techalchemy** [comment] 2018-03-20 16:30
@rosygupta thought it was fixed, new fix coming
