### ISSUE TITLE
pipenv doesn't throw error, when `extras` are a string instead of a list-like

### ISSUE THREAD

**Issue by con-f-use** [pypa/pipenv#5440] opened 2022-10-24 15:51 UTC
```
[packages]
msal = {version="==1.20.0", extras="broker"}
```

Something like text above in a Pipfile, during locking, results in the bug evidenced by output below:

```
There are incompatible versions in the resolved dependencies:
  msal[b,e,k,o,r]==1.20.0 (from -r /run/user/1000/pipenvji73rdf6requirements/pipenv-mcbzzrng-constraints.txt (line 22))
```

It should error. Note that is not immediately obvious what is going wrong, as the letters in `[b,e,k,o,r]` are not even in the same order as the extra dependency "broker".

**Comment by oz123** [comment] 2022-10-24 18:25
Question: have you added `extras="broker"` manually ?

**Comment by con-f-use** [comment] 2022-10-24 21:40
I assume you mean as opposed to via `pip install msal[broker]`? Then yes, I have used an editor to change the `Pipfile` manually. Still pipenv should not mis-interpret that and iterate over a string.

**Comment by oz123** [comment] 2022-10-24 21:42
I agree with you, but still, I wanted to know what the root cause was.

**Comment by oz123** [comment] 2022-10-25 08:12
Also, I think this should be fixed in https://github.com/sarugaku/plette

**Comment by oz123** [comment] 2022-10-25 19:11
There you go 🙂 I think the actual fix is in plette but I might be wrong.

**Comment by cullo7** [comment] 2022-10-25 21:04
But should i check if it was fixed in plette? Would we still want it resolved in pipenv regardless?

**Comment by oz123** [comment] 2022-10-25 21:08
The PR should be in that repository. You can prototype and test your changes on `pipenv/vendor/plette` but eventually the PR will go there.

**Comment by cullo7** [comment] 2022-11-18 21:01
Oz, is there some way I can contact you? I have some questions regarding this issue and pipenv in general that I'm not sure belong on this issue thread, my email is on my profile. Thanks

**Comment by oz123** [comment] 2022-11-19 13:47
Send you and email. Feel to answer there.

**Comment by oz123** [comment] 2022-12-13 08:33
I was able to pin-point  this bug. It's not about syncing, it's about requirements generation.

```
oznt@dell-gentoo:/tmp/pipenv-ncbhfaai-project $ cat Pipfile
[packages]
msal = {version="==1.20.0", extras="broker"}
oznt@dell-gentoo:/tmp/pipenv-ncbhfaai-project $ pipenv lock
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (d5418ae7afddb195bc750352ac1c92fb7c0040ad281c7a4ca32db6c2a4ad2c7c)!
oznt@dell-gentoo:/tmp/pipenv-ncbhfaai-project $ pipenv requirements 
-i https://pypi.org/simple
certifi==2022.12.7 ; python_version >= '3.6'
cffi==1.15.1
charset-normalizer==2.1.1 ; python_full_version >= '3.6.0'
cryptography==38.0.4 ; python_version >= '3.6'
idna==3.4 ; python_version >= '3.5'
msal[b,e,k,o,r]==1.20.0
pycparser==2.21
pyjwt[crypto]==2.6.0 ; python_version >= '3.7'
requests==2.28.1 ; python_version >= '3.7' and python_version < '4'
urllib3==1.26.13 ; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
```

**Comment by cullo7** [comment] 2022-12-14 00:26
Hi Oz,

Thank you for sending me this, i will look more into the requirements generation mechanism then.

I haven’t had a lot of time to work on this recently, but i will have time this upcoming week and try to submit a fix by then.

Best,

Aiden

**Comment by matteius** [comment] 2022-12-14 02:23
I think Oz did a fix in palette for this today.

**Comment by oz123** [comment] 2022-12-14 06:05
It's already fixed in plette.

**Comment by matteius** [comment] 2022-12-17 18:41
Please try `pipenv==2022.12.17` which includes this fix.

**Closed by matteius** 2022-12-17 18:41 UTC
Labels: Type: Possible Bug, good first issue
