### ISSUE TITLE
Pipenv must not add dependencies if it doesnt exist

### ISSUE THREAD

**Issue by usta** [pypa/pipenv#3418] opened 2018-12-31 18:49 UTC
Hello everyone,

Current workflow of pip have an issue for example : 

for example if you want to add pytest as dependency but you make a typo and forget e 
pipenv install pytst
because of there isnt any package named pytst but Pipenv still adds it to Pipfile

### Issue description

cat PipFile will still show that pytst added to Pipfile

### Expected result

it must be added to Pipfile after checking that package exists

**Comment by frostming** [comment] 2019-01-01 01:53
Duplicate of #3318

**Closed by frostming** 2019-01-01 01:53 UTC
