### ISSUE TITLE
Pipenv error

### ISSUE THREAD

**Issue by xahver** [pypa/pipenv#5375] opened 2022-09-23 23:26 UTC
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run![Screenshot 2022-09-23 191808](https://user-images.githubusercontent.com/102440646/192068953-fa8a9ad2-8960-4221-8e9c-4b20fe11ec2b.png), and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by xahver** [comment] 2022-09-23 23:30
I'm on python version 3.9.4.  Im currently attempting to do app academy open and I ran into this issue which is hindering me from moving on to the next section of learning I looked at someone with a similar experience to mine but they resolved there issue but mine still remains so if anyone could help that'd be great

**Comment by xahver** [comment] 2022-09-23 23:43
Ive tried updating it and failed I tried downgrading setuptools and nothing I tried using pip install git+https://github.com/pypa/pipenv.git@main and still nothing. Im kind of stuck at this point.

**Comment by matteius** [comment] 2022-09-24 00:37
@xahver I am not sure what the issue is based on your report -- you have the deprecation warning that was fixed in `2022.9.21` but you are running a prior version, and those warnings should not affect the behavior of pipenv.

**Comment by xahver** [comment] 2022-09-24 00:51
Is there a way to change versions so I no longer see the warnings for some reason its preventing me from moving forward
![Screenshot 2022-09-23 204632](https://user-images.githubusercontent.com/102440646/192073017-f60c0e38-8143-4bbf-b01b-851ab3a98b4d.png)
I am running the checker for app academy and its saying "pipenv not installed" which is making it so I cant go to the next step.

**Comment by matteius** [comment] 2022-09-24 00:53
@xahver Sure, you can `pip install pipenv --upgrade` but that won't solve your issue, just the deprecation warning.   Its apparently trying to use the pipenv in a specific location, if you type `which pipenv` what is your path?

**Comment by xahver** [comment] 2022-09-24 00:54
when I type which pipenv it pops up /home/xahver/.local/bin/pipenv

**Comment by matteius** [comment] 2022-09-24 00:55
Are you able to share the contents of the script you are running that says pipenv cannot be found?

**Comment by xahver** [comment] 2022-09-24 01:01
I just put 
pipenv --version
then the warning comes up
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
pipenv, version 2022.9.8

**Comment by matteius** [comment] 2022-09-24 01:04
@xahver That is not what I mean -- those are just warnings and do not effect the behavior of pipenv.   What command are you running that generated the output in that screenshot, the codeacademy thing?

**Comment by xahver** [comment] 2022-09-24 01:04
Ohh my bad curl its 
-s https://raw.githubusercontent.com/appacademy/aa-setup-checker/master/run.sh | bash

**Comment by xahver** [comment] 2022-09-24 01:05
curl -s https://raw.githubusercontent.com/appacademy/aa-setup-checker/master/run.sh | bash

**Comment by xahver** [comment] 2022-09-24 01:05
Sorry messed up there

**Comment by matteius** [comment] 2022-09-24 01:09
@xahver It is failing at this part of the script:  https://github.com/appacademy/aa-setup-checker/blob/master/helpers/python-checker.sh#L22
`IS_PIPENV_INSTALLED_IN_PYENV=$(which pipenv | grep -c "pyenv/shims/pipenv")`

Did they give any special instructions for how to install pipenv or for configuring pyenv ahead of time?

**Comment by xahver** [comment] 2022-09-24 01:10
No they just told us to put pip install pipenv and it installed then I went to check the version and boom warning

**Comment by xahver** [comment] 2022-09-24 01:11
They did make us put something else hold on

**Comment by matteius** [comment] 2022-09-24 01:12
@xahver Can you `pip uninstall pipenv --yes` and run it multiple times, until it says it is uninstalled and then do `pip install pipenv` which should get you the latest version which should not have that particular warning.

**Comment by xahver** [comment] 2022-09-24 01:13
We put 
export PIPENV_VENV_IN_PROJECT=1 w=1 
in the visual code application as well I almost forgot about that

**Comment by xahver** [comment] 2022-09-24 01:13
Ok ill try that now

**Comment by xahver** [comment] 2022-09-24 01:16
Yeah its still popping up that warning again

**Comment by matteius** [comment] 2022-09-24 01:17
@xahver `pipenv --version` should be 2022.9.21

**Comment by xahver** [comment] 2022-09-24 01:20
Ok I screenshotted what I did
![Screenshot 2022-09-23 211952](https://user-images.githubusercontent.com/102440646/192074134-8eeec032-f9b3-4d1a-9020-fa2d5cc16fd7.png)

**Comment by matteius** [comment] 2022-09-24 01:21
@xahver Yes that is why I said to run the uninstall command multiple times, somehow you have more than one version installed.

**Comment by xahver** [comment] 2022-09-24 01:21
Wait alright brb doing that now

**Comment by xahver** [comment] 2022-09-24 01:23
![Screenshot 2022-09-23 212301](https://user-images.githubusercontent.com/102440646/192074242-760ac9bf-06d2-411c-bb82-e3edd4b34142.png)

**Comment by xahver** [comment] 2022-09-24 01:24
Still popping up with the old version

**Comment by matteius** [comment] 2022-09-24 01:26
Leave the new version uninstalled until we can get rid of this prior version copy.

I'd recommend removing that old binary `rm /home/xahver/.local/bin/pipenv`

**Comment by xahver** [comment] 2022-09-24 01:29
Just to be sure u want me to delete this 
![Screenshot 2022-09-23 212759](https://user-images.githubusercontent.com/102440646/192074426-057ae70a-dd68-4b92-8b69-9b2535da9830.png)

**Comment by matteius** [comment] 2022-09-24 01:30
Yeah -- somehow you have that version of pipenv installed on your path but its not recognized as something pip manages.

**Comment by xahver** [comment] 2022-09-24 01:31
Alright I deleted it whats the next step

**Comment by matteius** [comment] 2022-09-24 01:31
verify when your `pipenv` that the command is not found.

**Comment by xahver** [comment] 2022-09-24 01:32
Nothings popping up anymore I think thats a good thing

**Comment by matteius** [comment] 2022-09-24 01:33
@xahver Not sure what you mean -- is the command not found or its now finding the new version?

**Comment by xahver** [comment] 2022-09-24 01:34
When I like type it nothing pops up
![Screenshot 2022-09-23 213421](https://user-images.githubusercontent.com/102440646/192074570-1f999af3-f68b-4896-8880-4b97898cf8ce.png)

**Comment by matteius** [comment] 2022-09-24 01:35
it should say command not found, type `which pipenv`

**Comment by xahver** [comment] 2022-09-24 01:35
![Screenshot 2022-09-23 213544](https://user-images.githubusercontent.com/102440646/192074611-8bf0a9cc-4869-4cea-9ad3-f29abcd52c19.png)

**Comment by matteius** [comment] 2022-09-24 01:37
@xahver `sudo rm -rf /home/xahver/.local/bin/pipenv` because the file is still there.

**Comment by xahver** [comment] 2022-09-24 01:39
![Screenshot 2022-09-23 213833](https://user-images.githubusercontent.com/102440646/192074702-8b4646d9-4521-4e5f-9cc8-8ca28a2d1fd7.png)

**Comment by matteius** [comment] 2022-09-24 01:39
Another version exists, again `which pipenv`

**Comment by xahver** [comment] 2022-09-24 01:40
/home/xahver/.pyenv/shims/pipenv

**Comment by xahver** [comment] 2022-09-24 01:40
thats what pops up

**Comment by matteius** [comment] 2022-09-24 01:40
Can you make sure you don't have the `apt` version installed?  `sudo apt remove pipenv`

**Comment by xahver** [comment] 2022-09-24 01:42
![Screenshot 2022-09-23 214153](https://user-images.githubusercontent.com/102440646/192074777-25ed6aa4-9b99-4914-8bb7-5e0d9d654e74.png)

**Comment by xahver** [comment] 2022-09-24 01:42
I got this so i press Y ?

**Comment by matteius** [comment] 2022-09-24 01:43
yes

**Comment by xahver** [comment] 2022-09-24 01:44
done

**Comment by matteius** [comment] 2022-09-24 01:46
Now is `pipenv` command not found?

**Comment by xahver** [comment] 2022-09-24 01:47
![Screenshot 2022-09-23 214702](https://user-images.githubusercontent.com/102440646/192074935-a4d9cb30-3b2a-4dcf-938a-73785c2351ab.png)

**Comment by matteius** [comment] 2022-09-24 01:47
@xahver Ok ready to have you `pip install pipenv`

**Comment by xahver** [comment] 2022-09-24 01:49
YOU DID IT OMG THANK YOU

**Comment by xahver** [comment] 2022-09-24 01:50
Much love now I can get to learning how to code I appreciate it. Thanks so much

**Closed** 2022-09-24 01:51 UTC

**Comment by xahver** [comment] 2022-09-24 01:52
Sounds great thank you for your help hope you have a great day or night wherever your at.
