### ISSUE TITLE
pipenv attempts to install python 2.7 dependencies in a python 3.6 project?

### ISSUE THREAD

**Issue by shapiromatron** [pypa/pipenv#2275] opened 2018-05-28 20:15 UTC
We have a python3.6 project which requires "ruamel.yaml=<0.15". When using a standard virtual environment I can install fine, but when using pipenv it tries to install the python2.7 - only ruamel.ordereddict dependency:

This works:

```bash
python3 -m venv foo
source foo/bin/activate
pip install "ruamel.yaml<0.15"
```

This fails:
```bash
mkdir bar && cd bar
pipenv install "ruamel.yaml<0.15"
```
With the error...

```txt

    ordereddict.c:2859:26: error: no member named 'ma_mask' in 'PyDictObject'
            res = res + (mp->ma_mask + 1) * sizeof(PyOrderedDictEntry);
                         ~~  ^
    3 warnings and 5 errors generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------

  Failed building wheel for ruamel.ordereddict
Command "/Users/ashapiro/.local/share/virtualenvs/bar-eB57WnA1/bin/python3.6...

```

I'm using pyenv for managing python versions and I have both 2.7 and 3.6 installed; my default global is 3.6. Here's output for pipenv:

    $ python -m pipenv.help | pbcopy

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/Users/ashapiro/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/ashapiro/.pyenv/versions/3.6.5/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/Users/ashapiro/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Users/ashapiro/.pyenv/versions/3.6.5/bin/python3.6m`
  - `3.6`: `/Users/ashapiro/.pyenv/versions/3.6.5/bin/python3.6`
  - `3.6`: `/Users/ashapiro/.pyenv/shims/python3.6`

  - `3.6.5`: `/Users/ashapiro/.pyenv/versions/3.6.5/bin/python`
  - `3.6.5`: `/Users/ashapiro/.pyenv/shims/python`
  - `2.7.10`: `/usr/bin/python`
  - `None`: `/Users/ashapiro/.pyenv/shims/python2`
  - `3.6.5`: `/Users/ashapiro/.pyenv/versions/3.6.5/bin/python3`
  - `3.6.5`: `/Users/ashapiro/.pyenv/shims/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT '
                     '2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `CLICOLOR`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `CONDA_SHLVL`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `HISTIGNORE`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/ashapiro/.pyenv/versions/3.6.5/bin:/usr/local/Cellar/pyenv/1.2.4/libexec:/Users/ashapiro/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.utf-8`
  - `PWD`: `/Users/ashapiro/dev/tmp/bar`

---------------------------

Contents of `Pipfile` ('/Users/ashapiro/dev/tmp/bar/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"ruamel.yaml" = "<0.15"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/ashapiro/dev/tmp/bar/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "113808238e9abe32abcf0f6a3b723261b0512c21156d6432bba8178cdbd29363"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "ruamel.ordereddict": {
            "hashes": [
                "sha256:08b4b19fe518d32251a5338e039c4dc9eb0876f2919f94c9b8d2f9446ea80806",
                "sha256:150ce8e6c514a2a2b62753622a75874962561f8e5eeec81a3172ab952807bf0b",
                "sha256:45541836cbfdde630033cae7bbbe35acbac87a0ceec79f944b7a3bedd940fe78",
                "sha256:aee2fa23e884249b4284b728888c553d551e5bfd4de2731f10153fd7813ec55f",
                "sha256:bf0a198c8ce5d973c24e5dba12d3abc254996788ca6ad8448eabc6aa710db149"
            ],
            "version": "==0.4.13"
        },
        "ruamel.yaml": {
            "hashes": [
                "sha256:0eecb39c0edc55c220f71788958bd6608669592269f996a55a4f74039dce6ed5",
                "sha256:8544c8017aebea70f73c5618b45190577e9b30c33580ebb762afd9c900996d3d",
                "sha256:90f9833e97875f14d0893690311d11beeeb88952776d4aff5c218b941b992b86",
                "sha256:9e6628706c6b513cb86f0ab78f6f457a1ecf0fadaaf15c8a2af59eba0d15e3ec",
                "sha256:9f0a9d5c94d0437efc520cc05d70b244101e5185edcd279a7f0a64bb28baaec1",
                "sha256:bd67c6836e530f4a6e404cdd9f698808a01c27947ecec98db46ff8e6e3ec7632",
                "sha256:da6f9adcb779c329cf853c086ecf1699214bb289c8c28439027d24a640bd65f8"
            ],
            "index": "pypi",
            "version": "==0.14.12"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment] 2018-06-03 21:11
Nice, just confirmed but this is fixed in master already

**Closed by techalchemy** 2018-06-03 21:11 UTC

**Comment by shapiromatron** [comment] 2018-06-03 22:07
Thanks! Great project, it’s a big step forward for the python community!

**Comment by shapiromatron** [comment] 2018-08-01 18:35
FYI, this is still failing for me

```
pipenv, version 2018.7.1
pip 18.0
```

**Comment by waprin** [comment] 2019-03-20 00:10
Like @shapiromatron , I'm having no problem installing `yamlfmt` with `pip` in a virtualenv but with just a plain `pipenv install yamlfmt` I'm getting what looks like is the same issue on version `2018.11.26`. @techalchemy can we get this issue re-opened?
