### ISSUE TITLE
pipenv lock --pre won't change 

### ISSUE THREAD

**Issue by kaldown** [pypa/pipenv#2201] opened 2018-05-16 08:27 UTC
installed packages from requirements
`pipenv run pip install -r requirements.txt`
it works correctly
so `pipenv graph` returns same as `pipenv run pip freeze`
but I can not create lock file, nor `pipenv lock`, or `pipenv lock --pre` either
`pipenv graph` output:

```
eth-account==0.1.0a2
  - attrdict [required: <3,>=2.0.0, installed: 2.0.0]
    - six [required: Any, installed: 1.11.0]
  - eth-keyfile [required: >=0.5.0,<0.6.0, installed: 0.5.1]
    - cytoolz [required: <1.0.0,>=0.9.0, installed: 0.9.0.1]
      - toolz [required: >=0.8.0, installed: 0.9.0]
    - eth-keys [required: <1.0.0,>=0.1.0-beta.4, installed: 0.1.0b4]
      - cytoolz [required: <1.0.0,>=0.9.0, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - eth-utils [required: >=0.5.0<1.0.0, installed: 0.8.1]
        - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
          - toolz [required: >=0.8.0, installed: 0.9.0]
        - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - eth-utils [required: >=1.0.0-beta.1,<2.0.0, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - pycryptodome [required: >=3.4.7,<4.0.0, installed: 3.6.1]
  - eth-keys [required: <0.3.0,>=0.2.0b1, installed: 0.1.0b4]
    - cytoolz [required: <1.0.0,>=0.9.0, installed: 0.9.0.1]
      - toolz [required: >=0.8.0, installed: 0.9.0]
    - eth-utils [required: >=0.5.0<1.0.0, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
  - eth-rlp [required: <1,>=0.1.0a2, installed: 0.1.0]
    - eth-utils [required: >=1.0.1,<2, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - hexbytes [required: <1,>=0.1.0, installed: 0.1.0]
      - eth-utils [required: >=1.0.1,<2.0.0, installed: 0.8.1]
        - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
          - toolz [required: >=0.8.0, installed: 0.9.0]
        - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - rlp [required: <1,>=0.6.0, installed: 0.6.0]
  - eth-utils [required: >=1.0.0b1,<2, installed: 0.8.1]
    - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
      - toolz [required: >=0.8.0, installed: 0.9.0]
    - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
  - hexbytes [required: <1,>=0.1.0b0, installed: 0.1.0]
    - eth-utils [required: >=1.0.1,<2.0.0, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
eth-hash==0.1.2
numpy==1.14.2
pkg-resources==0.0.0
pymongo==3.6.1
python-bitcoinrpc==1.0
typed-ast==1.1.0
web3==3.16.5
  - cytoolz [required: >=0.8.2, installed: 0.9.0.1]
    - toolz [required: >=0.8.0, installed: 0.9.0]
  - eth-abi [required: >=0.5.0,<0.6.0, installed: 0.5.0]
    - eth-utils [required: ==0.7.*, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
  - eth-tester [required: ==0.1.0b11, installed: 0.1.0b11]
    - cytoolz [required: <1.0.0,>=0.9.0, installed: 0.9.0.1]
      - toolz [required: >=0.8.0, installed: 0.9.0]
    - eth-keys [required: >=0.1.0b3,<0.2.0, installed: 0.1.0b4]
      - cytoolz [required: <1.0.0,>=0.9.0, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - eth-utils [required: >=0.5.0<1.0.0, installed: 0.8.1]
        - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
          - toolz [required: >=0.8.0, installed: 0.9.0]
        - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - eth-utils [required: <1.0.0,>=0.7.1, installed: 0.8.1]
      - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
        - toolz [required: >=0.8.0, installed: 0.9.0]
      - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
    - rlp [required: <1.0.0,>=0.6.0, installed: 0.6.0]
    - semantic-version [required: <3.0.0,>=2.6.0, installed: 2.6.0]
  - eth-utils [required: <1.0.0,>=0.7.1, installed: 0.8.1]
    - cytoolz [required: <1.0.0,>=0.8.2, installed: 0.9.0.1]
      - toolz [required: >=0.8.0, installed: 0.9.0]
    - pysha3 [required: >=1.0.0,<2.0.0, installed: 1.0.2]
  - lru-dict [required: >=1.1.6, installed: 1.1.6]
  - pysha3 [required: >=0.3, installed: 1.0.2]
  - requests [required: >=2.12.4, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.4.16]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - rlp [required: >=0.4.7, installed: 0.6.0]
  - toolz [required: >=0.8.2, installed: 0.9.0]
websockets==4.0.1
```
notice rlp == 0.6.0 and eth-utils==0.8.1

but PIpfile.lock:
```
{
    "_meta": {
        "hash": {
            "sha256": "3318a8c9cf795facae71cacba9dc932aa533c651b052985dac495707865076b7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "attrdict": {
            "hashes": [
                "sha256:86aeb6d3809e0344409f8148d7cac9eabce5f0b577c160b5e90d10df3f8d2ad3"
            ],
            "version": "==2.0.0"
        },
        "certifi": {
            "hashes": [
                "sha256:13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7",
                "sha256:9fa520c1bacfb634fa7af20a76bcbd3d5fb390481724c597da32c719a7dca4b0"
            ],
            "version": "==2018.4.16"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "cytoolz": {
            "hashes": [
                "sha256:84cc06fa40aa310f2df79dd440fc5f84c3e20f01f9f7783fc9c38d0a11ba00e5"
            ],
            "version": "==0.9.0.1"
        },
        "eth-abi": {
            "hashes": [
                "sha256:717f33b654fdaed61c3276d26bfa6ca2006ce3254c98d6c8ed0ac645acd5b34b",
                "sha256:a0a9bd9c6985f7d696c195911f097ec70adc2199553f61ac6236c7066eea5ba9"
            ],
            "version": "==1.1.1"
        },
        "eth-account": {
            "hashes": [
                "sha256:23262f2e618fee16c80ba295d10f13e480d8908774a2eaa8a2957ee96dec38ed",
                "sha256:42c405c1caa77f9aa5daf0a5cc9e89e7215ee39625a0dc18b7bdf7774bedf87d"
            ],
            "version": "==0.2.2"
        },
        "eth-hash": {
            "hashes": [
                "sha256:43adcab75a957fcf8c453d5542be55e4e0bd4e166270f45b09ac69b4d6486a06",
                "sha256:8695f5f3794497d1357b2ef6e84c67a7daf4bfec1dde9f76ff6b2022c2cc03a6"
            ],
            "version": "==0.1.2"
        },
        "eth-keyfile": {
            "hashes": [
                "sha256:70d734af17efdf929a90bb95375f43522be4ed80c3b9e0a8bca575fb11cd1159",
                "sha256:939540efb503380bc30d926833e6a12b22c6750de80feef3720d79e5a79de47d"
            ],
            "version": "==0.5.1"
        },
        "eth-keys": {
            "hashes": [
                "sha256:5ab2612f457452dc0a318655051cdd05c20f4db2f445003a46c98d324101b0e4",
                "sha256:b48fc92a527bd905525855ebe45e79ba17be6654c4bedb947119648c145c74c0"
            ],
            "version": "==0.2.0b3"
        },
        "eth-rlp": {
            "hashes": [
                "sha256:05d8456981d85e16a9afa57f2f2c3356af5d1c49499cc8512cfcdc034b90dde5",
                "sha256:a94744c207ea731a7266bd0894179dc6e51a6a8965316000c8e823b5d7e07694"
            ],
            "version": "==0.1.2"
        },
        "eth-utils": {
            "hashes": [
                "sha256:0eb71bdafda7e7e4c80ba98c06b3f89472e8ba0183a149be678f13cbb3b2e9b4",
                "sha256:add4cc71b64e40b15c1e7b037905daf59da58e046004bde7a2915f86a7fc8e57"
            ],
            "version": "==1.0.3"
        },
        "hexbytes": {
            "hashes": [
                "sha256:27cc227ae95fc20d44325ac0329a0293d656a05230da079650705030c7d7a819",
                "sha256:67e5608cb4a14d0a4ced058e595bb1f70c207ef2b5219fdc82af10e54bcf38de"
            ],
            "version": "==0.1.0"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "lru-dict": {
            "hashes": [
                "sha256:365457660e3d05b76f1aba3e0f7fedbfcd6528e97c5115a351ddd0db488354cc"
            ],
            "version": "==1.1.6"
        },
        "mypy": {
            "hashes": [
                "sha256:01cf289838f266ae7c6550c813181ee77d21eac9459dbf067e7a95a0a2db9721",
                "sha256:bc251cb31bc236d9fe4bcc442c994c45fff2541f7161ee52dc949741fe9ca3dd"
            ],
            "index": "pypi",
            "version": "==0.600"
        },
        "parsimonious": {
            "hashes": [
                "sha256:ae0869d72a6e57703f24313a5f5748e73ebff836e6fe8b3ddf34ea0dc00d086b"
            ],
            "version": "==0.8.0"
        },
        "pycryptodome": {
            "hashes": [
                "sha256:043c82cd3dd3120286a1b325ace93000cf52abb13a067c3ecb6220f874fe4c30",
                "sha256:0cdd73492859d853f60b8185715312dbca465879661e28d354d1cf5ea11860e7",
                "sha256:15013007e393d0cc0e69f4329a47c4c8597b7f3d02c12c03f805405542f70c71",
                "sha256:19d81b92bff837cdade735b9023808556bb4868e1ce194dad4d5ec4e2b2851f3",
                "sha256:1ceb3e87605c4f0080115a8a00abf45f5df27b0166a37fd669fbff4523273cfc",
                "sha256:2354a77051ed4a2959ce2aac508071eb3e42fc348ea39228b2eac335990bf508",
                "sha256:27bd2878200690b050dca34f505b5c623532324b3de40267c1484784063134df",
                "sha256:322f239e51fda80233762400a8975ab728639b571fa58545b95b9c44042af010",
                "sha256:49a71eb990af30ff6276cfe201eb83ed3640ae989c1b5973f7b55a46c94232d1",
                "sha256:4b5a2680008da3ac0cef2d3661597e0cbf8a3eb19eed35b859fd67e2de63eb85",
                "sha256:6d34fe5134eb5d62368e21e6f203ac1770bc7273e9536c4a280121312c2de53a",
                "sha256:733d5eb7e5ceed8b9d0b3c24c81f52c04cb5de6786461388204fceefe4456aa5",
                "sha256:7c73d3798fe2946953768b788ce554c0d4b390780f5e73d63bd833241af27bfe",
                "sha256:97af76f5200f15e97cac58d77f319dec40b4bada98de697c91a9517e63b41d1a",
                "sha256:97cc46ff02b99dafdc2e0385b325cec0f8a15bf8b285d6ed1d7e4a3bc2067ce1",
                "sha256:a561b59e0c3548eb649af381b7c38c6fd8392bbd4d0a8214794b2b761f405af4",
                "sha256:ab2c633bfc23cf41be9281228517cb6f87879f4f1aeb154ed72bd53ab7cc83e9",
                "sha256:adb54316998337f315520bbd8ef4d8bbd940b4ddfaef8ba1db3c137c5e499399",
                "sha256:b4a3b710287eb1fc3e2cc1af018063f003530dff00c9ea4c55ae19bc1f3923cc",
                "sha256:bcfdb66d6604882c3f96eea922552c2487cc0aec4b883cd217b9d341d2f8fad0",
                "sha256:c08c053eb8716bbbd5e13e38f453b9e46a063e68df8659f3c421dcb7519fd381",
                "sha256:e51da4ef9d9e2695a04044152f380c2db17adc9fc6fad8e24d863ead9cd548ed",
                "sha256:e850e07f54dc3de9a1efdd59d227fcd1cb30cdd307dafdc647c79e8f30cf5032",
                "sha256:ebc579c41fe26748dc1bad4f9105f08740ee28826293a28103b3875968695a5e",
                "sha256:ed94cb1b4bf24be734f2bf2db3e8ea75f3914d2f8e684291bee54bbe4a5a9151",
                "sha256:f5e19802295e63bdf83bb92849285c01f7167840efb1c1e08507a50b10ba7efa",
                "sha256:fc569682f012b1f62f8d28d8f9bc71f1de67648cd1bc124ef8ccf8db4edfc28a"
            ],
            "version": "==3.6.1"
        },
        "pymongo": {
            "hashes": [
                "sha256:051770590ddbd5fb7db17d3315d4c1b0f18039d830dd18e1bae39451c30d31cd",
                "sha256:061085dfe4fbf1d9d6ed2f2e52fe6ab72559e48b4294370b433751638160d10b",
                "sha256:07fdee1c5567f237796a8550233e04853785d8dcf95929f96ab519ed91543109",
                "sha256:0d98731aaea8cb32b535c376f6785927e4e3d9459ffe1440b8a639827a849350",
                "sha256:10f683950f70626ccedf4a662d1c0b3244e8e013c2067872af5633830abd1bfd",
                "sha256:192ee5e33821931f4ec6df5fff4361220c0c92bb5b7437c6db52e20a0c9b4d98",
                "sha256:2954b99cfeb76776879e9f8a4cae9c5e19d5eff92d0b7b663ceddcf192adb66b",
                "sha256:36a992e02fced328de5304145dc3729a8cea12e58ad34b842a6f46d7941c9fc7",
                "sha256:419ed5d5b76ef304815f354d9df7f2085acfd6ff7cc1b714ca702e2239b341c2",
                "sha256:42ec201fd9a26e7c1e611e3db19324dead51dd4646391492eb238b41749340e8",
                "sha256:4400fa92af310bf66b76c313c7ded3bb63f3d63b4f43c3bfbff552cf294dc9fa",
                "sha256:44abdc26989600bb03b62d57616ec7c1b9182290720167c39e38c3a2b0d44e44",
                "sha256:45fb9f589c0f35436dbe391c53a387ffffa8d086b8521a86fca4f3e1d0edbf71",
                "sha256:4807dfbb5cdcfe0224329992dc48b897c780d0ad7553c3799d34f84ba5cab446",
                "sha256:54daf67e1e7e7e5a5160c86123bdd39b1d3b25876c2ab38230dc2a764cb3d98f",
                "sha256:5f2814a9492a724fd77c90ffc01f810276ef9972ae02587bfaae40835f9b8407",
                "sha256:5fd6ce5ed3c6c92d2c94756e6bf041304e5c7c5a5dbea31b8957d52a78bdf01d",
                "sha256:601e00fe7fb283f04c95f5dafb787c0862f48ca015a6f1f81b460c74e4303873",
                "sha256:63a47a97b5cb4c67c86552b15e08df12ff026a648211120adf5ebe00453e85e9",
                "sha256:6c4459d5c2b45ba55e14360e03078426015c1b0881facaec51bd9bd9e2304cec",
                "sha256:7fbd9233e8b6741b047c5857e2ad5efb74091f167d7fa8a2a3379217165058f9",
                "sha256:7ffac35362c07c103b024b89875e8d7f0625129b65c56fa8a3ecebbd56110405",
                "sha256:833bc6cb2ec7058dea9f5840a9314ac74738d2117486a044e88f3976e37ea7a0",
                "sha256:92cb26a2a9b38e8df5215803f950b20a6c847d5e00d1dd125eaa84f05f9472d7",
                "sha256:97d6a218c4ad4f8fdde0143776d5224e884cbcfe631e7446379fa1790d8cf04f",
                "sha256:9e5f0e8967d95a256038817460844a8aab588b9bc9ba6296507a1863960a0e44",
                "sha256:9e6db7ff63fb836d56e62216e10e868c23a99f3cb02875411eb2cb787acf58c7",
                "sha256:a0a695eef38c15570f6da3b4900e1a1d85fa92c754177d5f05267b49da79c92b",
                "sha256:aa46076524471729430afacca3dd8ad4578878eca6fc9e2b593a0b381b5bbeb7",
                "sha256:abf83b908e535b1386a7732825994e6e36eff6394c1829f3e7a23888136484fa",
                "sha256:adb2dba52c8a2a2d7bcd3b267f7bbf7c822850cf6a7cd15211b9f386c3a670ef",
                "sha256:ae7b3479822a03f6f651913de84ba67101f23e051ae88034085e974f472dcfff",
                "sha256:c596af57286ef28cae7a48e3070d222f96f5f0eab76ad39d680ae6b9bbc957c7",
                "sha256:cc15b30f0ac518e6cbd4b6e6e6162f8aa14edfe255d0841146f146151bd58865",
                "sha256:d23498d62063b715078947bef48fa4d34dc354f3b268ed15dc6b46fc809a88e9",
                "sha256:dd29bb5bc9068ccc248c8c145efd839421f04363b468b47cfa2d4902ca369afe",
                "sha256:e2745dd408a26d4517702d1686afc8e1e1638d2167e857c684f912192cc00dcf",
                "sha256:e53ad0cc6c489f83e7f6bb6121aa73bb6f6488410024a3bd77c16af1aa3a1000",
                "sha256:ecb11113407d919f8714cc7d0841985044633d0b561ef3d797e1b494a3e73537",
                "sha256:ece2c2add66d3ec2720a963bf073ca11fc3b0b58159767fc3bc5ddaad791d481",
                "sha256:ef25c8675f5c8c19832f69cd97d728d99bb4ab9c3b200e28a5c8416631afaf3c",
                "sha256:f62a818d643776873713c5676f17bd95ac4176220b13dd12c14edd3a450d1ac9",
                "sha256:f7ebcb846962ee40374db2d9014a89bea9c983ae63c1877957c3a0a756974796"
            ],
            "index": "pypi",
            "version": "==3.6.1"
        },
        "python-bitcoinrpc": {
            "hashes": [
                "sha256:a6a6f35672635163bc491c25fe29520bdd063dedbeda3b37bf5be97aa038c6e7"
            ],
            "index": "pypi",
            "version": "==1.0"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "version": "==2.18.4"
        },
        "rlp": {
            "hashes": [
                "sha256:492c11b18e89af42f98e96bca7671ffee4ad4cf5e69ea23b4d2221157d81b512",
                "sha256:dc6c5887f354508892b70f2897ca3d135411d669e0103092e689c224ef8de8e9"
            ],
            "version": "==1.0.1"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "toolz": {
            "hashes": [
                "sha256:929f0a7ea7f61c178bd951bdae93920515d3fbdbafc8e6caf82d752b9b3b31c9"
            ],
            "version": "==0.9.0"
        },
        "typed-ast": {
            "hashes": [
                "sha256:0948004fa228ae071054f5208840a1e88747a357ec1101c17217bfe99b299d58",
                "sha256:25d8feefe27eb0303b73545416b13d108c6067b846b543738a25ff304824ed9a",
                "sha256:29464a177d56e4e055b5f7b629935af7f49c196be47528cc94e0a7bf83fbc2b9",
                "sha256:2e214b72168ea0275efd6c884b114ab42e316de3ffa125b267e732ed2abda892",
                "sha256:3e0d5e48e3a23e9a4d1a9f698e32a542a4a288c871d33ed8df1b092a40f3a0f9",
                "sha256:519425deca5c2b2bdac49f77b2c5625781abbaf9a809d727d3a5596b30bb4ded",
                "sha256:57fe287f0cdd9ceaf69e7b71a2e94a24b5d268b35df251a88fef5cc241bf73aa",
                "sha256:668d0cec391d9aed1c6a388b0d5b97cd22e6073eaa5fbaa6d2946603b4871efe",
                "sha256:68ba70684990f59497680ff90d18e756a47bf4863c604098f10de9716b2c0bdd",
                "sha256:6de012d2b166fe7a4cdf505eee3aaa12192f7ba365beeefaca4ec10e31241a85",
                "sha256:79b91ebe5a28d349b6d0d323023350133e927b4de5b651a8aa2db69c761420c6",
                "sha256:8550177fa5d4c1f09b5e5f524411c44633c80ec69b24e0e98906dd761941ca46",
                "sha256:a8034021801bc0440f2e027c354b4eafd95891b573e12ff0418dec385c76785c",
                "sha256:bc978ac17468fe868ee589c795d06777f75496b1ed576d308002c8a5756fb9ea",
                "sha256:c05b41bc1deade9f90ddc5d988fe506208019ebba9f2578c622516fd201f5863",
                "sha256:c9b060bd1e5a26ab6e8267fd46fc9e02b54eb15fffb16d112d4c7b1c12987559",
                "sha256:edb04bdd45bfd76c8292c4d9654568efaedf76fe78eb246dde69bdb13b2dad87",
                "sha256:f19f2a4f547505fe9072e15f6f4ae714af51b5a681a97f187971f50c283193b6"
            ],
            "version": "==1.1.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        },
        "web3": {
            "hashes": [
                "sha256:87edb8e9e2be222a51e24010d7604cb5ee8e926f4282136df6842be5cec9eec1",
                "sha256:d282cc6fc4a011e289aecb482ce0f27139013e0ea0258639f23c0d7b08362448"
            ],
            "index": "pypi",
            "version": "==4.2.1"
        },
        "websockets": {
            "hashes": [
                "sha256:0c31bc832d529dc7583d324eb6c836a4f362032a1902723c112cf57883488d8c",
                "sha256:1f3e5a52cab6daa3d432c7b0de0a14109be39d2bfaad033ee5de4a3d3e11dcdf",
                "sha256:341824d8c9ad53fc43cca3fa9407f294125fa258592f7676640396501448e57e",
                "sha256:367ff945bc0950ad9634591e2afe50bf2222bc4fad1088a386c4bb700888026e",
                "sha256:3859ca16c229ddb0fa21c5090e4efcb037c08ce69b0c1dfed6122c3f98cd0c22",
                "sha256:3d425ae081fb4ba1eef9ecf30472ffd79f8e868297ccc7a47993c96dbf2a819c",
                "sha256:64896a6b3368c959b8096b655e46f03dfa65b96745249f374bd6a35705cc3489",
                "sha256:6df87698022aef2596bffdfecc96d656db59c8d719708c8a471daa815ee61656",
                "sha256:80188abdadd23edaaea05ce761dc9a2e1df31a74a0533967f0dcd9560c85add0",
                "sha256:d1a0572b6edb22c9208e3e5381064e09d287d2a915f90233fef994ee7a14a935",
                "sha256:da4d4fbe059b0453e726d6d993760065d69b823a27efc3040402a6fcfe6a1ed9",
                "sha256:da7610a017f5343fdf765f4e0eb6fd0dfd08264ca1565212b110836d9367fc9c",
                "sha256:ebdd4f18fe7e3bea9bd3bf446b0f4117739478caa2c76e4f0fb72cc45b03cbd7",
                "sha256:f5192da704535a7cbf76d6e99c1ec4af7e8d1288252bf5a2385d414509ded0cf",
                "sha256:fd81af8cf3e69f9a97f3a6c0623a0527de0f922c2df725f00cd7646d478af632",
                "sha256:fecf51c13195c416c22422353b306dddb9c752e4b80b21e0fa1fccbe38246677"
            ],
            "version": "==4.0.1"
        }
    },
    "develop": {}
}
```

```
        "rlp": {
            "hashes": [
                "sha256:492c11b18e89af42f98e96bca7671ffee4ad4cf5e69ea23b4d2221157d81b512",
                "sha256:dc6c5887f354508892b70f2897ca3d135411d669e0103092e689c224ef8de8e9"
            ],
            "version": "==1.0.1"

        "eth-utils": {
            "hashes": [
                "sha256:0eb71bdafda7e7e4c80ba98c06b3f89472e8ba0183a149be678f13cbb3b2e9b4",
                "sha256:add4cc71b64e40b15c1e7b037905daf59da58e046004bde7a2915f86a7fc8e57"
            ],
            "version": "==1.0.3"
```

different versions.
How to make them consistent.
and Yes, I've searched for an issues, `--pre` key won't solve my problem.
Could you please be more verbose in your arguments, what exactly means 'Allow pre–releases.'.

Thanks

**Comment by techalchemy** [comment] 2018-05-16 13:27
Sure thing! Pre-releases (I know this term doesn’t make sense) are just releases tagged with an ‘alpha’, ‘beta’, ‘dev’ or ‘rc’ tag so basically 1.0.3 is a normal release while 1.0.3rc1 is 1.0.3 _release candidate 1_ and is a pre-release.  That just means that someday 1.0.3 will be released and that this version is a precursor to that which isn’t finished. 

We have had other issues specifically related to `eth-utils`, you may want to look those up and see how they were resolved. 

Do you still think the `—pre` flag won’t help?

**Comment by uranusjr** [comment] 2018-06-06 08:44
The output is indeed a bit strange:

```toml
[packages]
eth-account = "==0.1.0a2"
eth-hash = "==0.1.2"
numpy = "==1.14.2"
web3 = "==3.16.5"
```

```
$ pipenv lock --pre
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches eth-keys<0.2.0,<0.3.0,>=0.1.0b3,>=0.2.0b1
Skipped pre-versions: 0.1.0b1, 0.1.0b1, 0.1.0b2, 0.1.0b2, 0.1.0b3, 0.1.0b3, 0.1.0b4, 0.1.0b4, 0.2.0b1, 0.2.0b1, 0.2.0b2, 0.2.0b2, 0.2.0b3, 0.2.0b3
There are incompatible versions in the resolved dependencies.
```

Notice the log says it’s skipping pre-versions, even when I specified `--pre`. We might be dropping the flag somewhere…

**Comment by techalchemy** [comment] 2018-06-06 13:00
I think `do_install` drops it in the `do_init` call

**Comment by techalchemy** [comment] 2018-06-18 07:11
oh, I just got around to reading this.  Lets look at the error message: `Could not find a version that matches eth-keys<0.2.0,<0.3.0,>=0.1.0b3,>=0.2.0b1`.  We can filter this down a bit, because `<0.2.0` is already less than `0.3.0` so we can just axe the `0.3.0` constraint, and similarly, `0.2.0b1` is greater than `0.1.0b3`.  This leaves our available package space for `eth-keys` to match against as: `>=0.2.0b1,<0.2.0`.

The versions we skip aren't super useful, because if you look carefully they are usually duplicated a bunch.  We skip lots of stuff, this is one of the reasons I wasn't totally on board with showing the listing of skipped prerelease versions in the first place.  This is super misleading -- it implies that we skipped these versions _because_ they were prerelease versions.  What actually happened is that we skipped these versions, _and also, they happened to be prerelease versions_.

I can tell you without looking at any code or doing any dependency resolution that there is no such version that will satisfy `<0.2.0, >=0.2.0b1`, so this is most likely not a bug.  It would actually be quite odd if we didn't respect the `--pre` argument because we use it ourselves all the time in our own pipfile.


Anyway I've fielded dozens of issues related to this set of ethereum tooling, the maintainers just seem to randomly pin stuff that conflicts across all of their software.  Pip doesn't have a dependency resolver, it will always install whatever you tell it to install.  That is one of the key distinguishing features of pipenv -- if you want to install 5 packages, and 3 of them try to install conflicting versions of `requests`, pipenv doesn't just let them go ahead and race to see who wins -- it will actually stop and tell you about the problem.   I'd recommend opening an issue against the packages you're trying to install and asking them to sort this out

**Closed by techalchemy** 2018-06-18 07:11 UTC
Labels: bug 🐛

**Comment by uranusjr** [comment] 2018-06-18 07:17
> there is no such version that will satisfy `<0.2.0`, `>=0.2.0b1`

I’m not sure how the logic works, but 0.2.0b1, 0.2.0b2, and 0.2.0b3 should all be considered matching this criteria. If they are not, this is a bug.

**Comment by techalchemy** [comment] 2018-06-18 08:08
```

**Comment by jsvisa** [comment] 2018-11-02 10:35
same issue. use `pip install web3` success, but with `pipenv install` failed with:

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches eth-keys<0.3.0,>=0.2.0b3
Skipped pre-versions: 0.1.0b1, 0.1.0b1, 0.1.0b2, 0.1.0b2, 0.1.0b3, 0.1.0b3, 0.1.0b4, 0.1.0b4, 0.2.0b1, 0.2.0b1, 0.2.0b2, 0.2.0b2, 0.2.0b3, 0.2.0b3
There are incompatible versions in the resolved dependencies.
```
