### ISSUE TITLE
pipenv work in win10, High CPU utilization

### ISSUE THREAD

**Issue by offd** [pypa/pipenv#3837] opened 2019-07-11 06:35 UTC
### Issue description

In win10, I use pipenv install create enviroment,but the CPU utilization is high

![image](https://user-images.githubusercontent.com/19191915/61027598-2a116000-a3e9-11e9-97b4-f24c174ee013.png)

![image](https://user-images.githubusercontent.com/19191915/61027570-1ebe3480-a3e9-11e9-8426-407c56bb0fb7.png)

**Comment by frostming** [comment] 2019-07-11 06:37
Duplicate of #3832 Currently use Python 3.7.3 until the virtualenv has released with a fix.

**Closed by frostming** 2019-07-11 06:37 UTC
