### ISSUE TITLE
Dependencies not being installed if I use a Pipfile

### ISSUE THREAD

**Issue by josh-gree** [pypa/pipenv#1805] opened 2018-03-20 15:32 UTC
I am having issues installing `Flask` using `pipenv`

I have tried two approaches. Firstly installing from a Pipfile;

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[requires]
python_version = "3.6"
```

I then run `pipenv install` the output of the command is as follows;

```
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.4) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/bin/python3.6
Also creating executable in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (011179)!
Installing dependencies from Pipfile.lock (011179)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

The output of `pipenv graph` is the following;

```
Flask==0.12.2
  - click [required: >=2.0, installed: 6.7]
  - itsdangerous [required: >=0.21, installed: ?]
  - Jinja2 [required: >=2.4, installed: 2.9.5]
  - Werkzeug [required: >=0.7, installed: ?]
```

If I try to import `flask` in the python shell started with `pipenv python` I get missing library `werkzeug` error.

The second approach which *works* is to start without a `Pipfile` and just run `pipenv install flask` the output of which is;

```
Creating a Pipfile for this project…
Installing flask…
Requirement already satisfied: flask in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages
Requirement already satisfied: click>=2.0 in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages (from flask)
Requirement already satisfied: Werkzeug>=0.7 in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages (from flask)
Requirement already satisfied: itsdangerous>=0.21 in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages (from flask)
Requirement already satisfied: Jinja2>=2.4 in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages (from flask)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages (from Jinja2>=2.4->flask)

Adding flask to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (011179)!
Installing dependencies from Pipfile.lock (011179)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

The `Pipfile` generated is;

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

and the output of `pipenv graph` is;

```
Flask==0.12.2
  - click [required: >=2.0, installed: 6.7]
  - itsdangerous [required: >=0.21, installed: 0.24]
  - Jinja2 [required: >=2.4, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - Werkzeug [required: >=0.7, installed: 0.14.1]
```

I get *no* import errors!

Any help would be appreciated!? This worked perfectly less than a week ago...

I am using `pipenv` version 11.8.3

**Comment by josh-gree** [comment] 2018-03-20 15:45
I think this is probably the same as #1791??

**Comment by techalchemy** [comment] 2018-03-20 16:29
yep closing, sorry!

**Comment by josh-gree** [comment] 2018-03-20 16:50
Have tried your fix but still exactly same issue :-(

**Comment by josh-gree** [comment] 2018-03-20 18:13
Real shame but having to move back to using requirements.txt - love this project but this issue is a really big problem! Hopefully will be fixed in future...

**Comment by techalchemy** [comment] 2018-03-20 21:41
We are quite literally pushing fixes every few hours. We haven’t gotten to yours yet. Have patience.

**Comment by techalchemy** [comment] 2018-03-20 21:46
Wait you wrote the first pipfile by hand and it has no dev-packages section. When you actually let pipenv generate it for you it worked fine. This is not a bug. Closing.

**Closed by techalchemy** 2018-03-20 21:46 UTC

**Comment by uranusjr** [comment] 2018-03-21 04:34
I wonder what makes the difference with the empty section though. If the phenomenon is real there must be a bug hidden somewhere.

**Comment by uranusjr** [comment] 2018-03-21 13:34
Hand-written Pipfile works on my machine.

**Comment by josh-gree** [comment] 2018-03-21 18:04
Sorry I am very impatient - I do apologise!

This still is broken though. I am using pipenv version 11.9.0 now and the issue is still as it was yesterday. If it is not a bug and I am doing something stupid then my bad but I am pretty sure I am not...

My current Pipfile is the following;

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[requires]
python_version = "3.6"
```

No empty dev section just Flask...

```
pipenv run python -c 'import flask'
```

returns the following error;

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/josh-gree/.local/share/virtualenvs/pipenv_test-dFjl2l40/lib/python3.6/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ModuleNotFoundError: No module named 'werkzeug'
```

and `pipenv graph` the following output;

```
Flask==0.12.2
  - click [required: >=2.0, installed: 6.7]
  - itsdangerous [required: >=0.21, installed: ?]
  - Jinja2 [required: >=2.4, installed: 2.9.5]
  - Werkzeug [required: >=0.7, installed: ?]
```

For reference this is the output of `pipenv.help`;

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT '
                     '2017; root:xnu-3789.60.24~6/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TMPDIR`
  - `__CF_USER_TEXT_ENCODING`
  - `HOME`
  - `SHELL`
  - `Apple_PubSub_Socket_Render`
  - `SSH_AUTH_SOCK`
  - `PATH`
  - `LOGNAME`
  - `DISPLAY`
  - `XPC_SERVICE_NAME`
  - `SECURITYSESSIONID`
  - `USER`
  - `XPC_FLAGS`
  - `LANG`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LC_CTYPE`
  - `LSCOLORS`
  - `EDITOR`
  - `gitaccess`
  - `gituname`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/Users/josh-gree/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/josh-gree/pipenv_test`


---------------------------

Contents of `Pipfile` ('/Users/josh-gree/pipenv_test/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[requires]
python_version = "3.6"
```


Contents of `Pipfile.lock` ('/Users/josh-gree/pipenv_test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "cbf8e638e8cd1a98e1008cd9f9ead22772a784d607fbc4e41b89de5b19011179"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "flask": {
            "hashes": [
                "sha256:0749df235e3ff61ac108f69ac178c9770caeaccad2509cb762ce1f65570a8856",
                "sha256:49f44461237b69ecd901cc7ce66feea0319b9158743dd27a2899962ab214dac1"
            ],
            "index": "pypi",
            "version": "==0.12.2"
        }
    },
    "develop": {}
}

```
</details>

**Comment by josh-gree** [comment] 2018-03-21 18:09
@techalchemy Just in response to;

> Wait you wrote the first pipfile by hand and it has no dev-packages section. When you actually let pipenv generate it for you it worked fine. This is not a bug. Closing.

You are correct that if I start from an empty directory (no virtual env in existance) and run `pipenv install flask` everything works I get Flask with its dependencies. However if I then remove the venv (`pipenv --rm`) and then use `pipenv install` from the generated `Pipfile` the dependencies are not installed...

**Comment by uranusjr** [comment] 2018-03-21 18:10
Try clearing resolver caches and run `install` again. Pipenv “remembers” the resolver result, and if it was faulty previously it would keep going back to the old results unless something stops it.

```
pipenv-resolver --clear
```

should usually do it. If it does not, try deleting the cache directory (`~/Library/Caches/pipenv` IIRC) completely.

**Comment by josh-gree** [comment] 2018-03-21 18:11
This is occurring on circle and dockerhub builds...

**Comment by josh-gree** [comment] 2018-03-21 18:13
This doesn't fix the issue locally either :-(

**Comment by josh-gree** [comment] 2018-03-21 18:16
Could this be an issue with Flask itself? Is `pipenv` looking for dependencies differently if you use a Pipfile and if you use `pipenv install blah`?

**Comment by uranusjr** [comment] 2018-03-21 18:27
No because I can’t reproduce this. This is my run (I’m on Windows, but that shouldn’t make a difference):

```bat
C:\Users\uranusjr\Downloads\gh-1805                                                                    
λ dir /w                                                                                               
 Volume in drive C is Local Disk                                                                       
 Volume Serial Number is C034-A84E                                                                     
                                                                                                       
 Directory of C:\Users\uranusjr\Downloads\gh-1805                                                      
                                                                                                       
[.]       [..]      Pipfile                                                                            
               1 File(s)            151 bytes                                                          
               2 Dir(s)  784,689,541,120 bytes free                                                    
                                                                                                       
C:\Users\uranusjr\Downloads\gh-1805                                                                    
λ type Pipfile                                                                                         
[[source]]                                                                                             
url = "https://pypi.python.org/simple"                                                                 
verify_ssl = true                                                                                      
name = "pypi"                                                                                          
                                                                                                       
[packages]                                                                                             
flask = "*"                                                                                            
                                                                                                       
[requires]                                                                                             
python_version = "3.6"                                                                                 
                                                                                                       
C:\Users\uranusjr\Downloads\gh-1805                                                                    
λ pipenv install                                                                                       
Creating a virtualenv for this project…                                                                
Using C:\Users\uranusjr\AppData\Local\Programs\Python\Python36\python.exe (3.6.4) to create virtualenv…
Running virtualenv with interpreter C:\Users\uranusjr\AppData\Local\Programs\Python\Python36\python.exe
Using base prefix 'C:\\Users\\uranusjr\\AppData\\Local\\Programs\\Python\\Python36'                    
New python executable in C:\Users\uranusjr\Downloads\gh-1805\.venv\Scripts\python.exe                  
Installing setuptools, pip, wheel...done.                                                              
                                                                                                       
Virtualenv location: C:\Users\uranusjr\Downloads\gh-1805\.venv                                         
Pipfile.lock not found, creating…                                                                      
Locking [dev-packages] dependencies…                                                                   
Locking [packages] dependencies…                                                                       
Updated Pipfile.lock (011179)!                                                                         
Installing dependencies from Pipfile.lock (011179)…                                                    
  ================================ 6/6 - 00:00:06                                                      
To activate this project's virtualenv, run the following:                                              
 $ pipenv shell                                                                                        
                                                                                                       
C:\Users\uranusjr\Downloads\gh-1805                                                                    
λ pipenv run python -c "import flask"                                                                  
                                                                                                       
C:\Users\uranusjr\Downloads\gh-1805                                                                    
λ                                                                                                      
```

Everything works. This must be something wrong with your environment, I just don’t know what it is.

**Comment by josh-gree** [comment] 2018-03-21 18:29
Ok thanks for your help!

**Comment by uranusjr** [comment] 2018-03-21 18:31
Sorry for the experience. Hopefully we’ll be able to find out what’s going on in the future somehow.

**Comment by techalchemy** [comment] 2018-03-21 18:39
@josh-gree you _should_ have an empty dev-packages section, that is specified in the pipfile spec.  You must have all of the sections even if they are empty.

I'd be curious to see the output of `pipenv install flask && pipenv --rm && rm -rf Pipfile.lock && pipenv install` directly with allowing pipenv to generate the lockfile for you

**Comment by uranusjr** [comment] 2018-03-21 19:46
@josh-gree Yes. In most situations the lock file is the target Pipenv tries to sync your environment to. Pipfile generates the lock file; the lock file generates the environment. If the lock file exists (and is not oudated, judged from a hash coded inside it), Pipenv will simply use it without consulting the Pipfile.
