### ISSUE TITLE
Version not matching - typed-ast

### ISSUE THREAD

**Issue by superdev810** [pypa/pipenv#3569] opened 2019-02-28 15:00 UTC
**Describe the bug**

I installed typed-ast 1.3.1 a few days without any issue, from today when installing it says typed-ast version not matching like following screenshot.
![image](https://user-images.githubusercontent.com/20223963/53574349-2a882780-3bbb-11e9-942f-0595b3b61a0e.png)

**Expected behavior**

pipenv install should be installed correctly without issue.

**To Reproduce**

pipenv install typed-ast
**My Platform**

Ubuntu 18.04
Python3.6.7
Pi 19.0.3
SSL/TLS implemented

**Additional context**

My Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[dev-packages]
"autopep8" = "*"
"gprof2dot" = "*"
"pep8" = "*"
"pyprof2calltree" = "*"
"urllib3" = "*"
asynctest = "*"
autoflake = "*"
awscli = "*"
certifi = "*"
crayons = "*"
cython = "*"
ipython = "*"
isort = "*"
jsonschema = "*"
jupyter = "*"
line-profiler = "*"
mypy = "*"
pre-commit = "*"
progress = "*"
pydevd = "*"
pylint = "*"
pytest = "==3.10.0"
pytest-asyncio = "==0.9.0"
pytest-console-scripts = "==0.1.7"
pytest-cov = "==2.6.0"
pytest-docker = "==0.6.1"
pytest-mock = "==1.10.0"
pytest-profiling = "*"
pytest-pylint = "*"
pytest-sanic = "*"
pytest-timeout = "*"
python-rapidjson = "*"
requests = "*"
yapf = "*"
funcy = "*"
vprof = "*"

[packages]
aiodns = "*"
aiohttp = "*"
aredis = "*"
cchardet = "*"
configargparse = "*"
cytoolz = "*"
hiredis = "*"
pipenv = "*"
pygtrie = "*"
python-json-logger = "*"
python-rapidjson = "*"
sanic = "*"
structlog = "*"
ujson = "*"
uvloop = "*"
websockets = "*"
async-timeout = "*"
typed-ast = "*"

[requires]
python_version = "3.6"

```

**Comment by jonathanverner** [comment] 2019-02-28 15:32
Possibly a duplicate of #3568

**Closed** 2019-03-01 00:59 UTC
