### ISSUE TITLE
Dependencies in setup.py extras_require are not 'locked' during VCS install

### ISSUE THREAD

**Issue by bjmc** [pypa/pipenv#2128] opened 2018-05-03 05:00 UTC
When I install a package from a VCS (i.e. git) and specify I want an extra feature for it, the dependencies that package has laid out in `extras_require` in its `setup.py` do not get included in my `Pipfile.lock` and they are omitted during future installs from the lockfile. 

    $ pipenv --version
    pipenv, version 11.1.7

------------

##### Expected result

I expected that running `pipenv install -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]` would result in a Pipfile.lock containing Twisted, because [pybeanstalk lists it under extras_require in setup.py](https://github.com/beanstalkd/pybeanstalk/blob/master/setup.py#L50).

##### Actual result
```bash
$ pipenv install -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted] --verbose
Creating a Pipfile for this project…
Installing -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]…
⠋Installing '-e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]'
$ "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/pip" install  --src "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src" --verbose    -e "git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]" -i https://pypi.python.org/simple --exists-action w
Created temporary directory: /tmp/pip-ephem-wheel-cache-r__lhp_v
Created temporary directory: /tmp/pip-install-honeit3h
Looking in indexes: https://pypi.python.org/simple
Obtaining pybeanstalk[twisted] from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]
  Running command git config --get-regexp remote\..*\.url
  remote.origin.url ssh://git@github.com/beanstalkd/pybeanstalk.git
  Clone in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk exists, and has correct URL (ssh://git@github.com/beanstalkd/pybeanstalk.git)
  Running command git rev-parse HEAD
  d5e372158c202adca4e1d1ddd9a6b063c6085137
  Updating /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk clone (to revision 1.0rc1)
  Running command git version
  git version 2.7.4
  Running command git fetch -q --tags
  Running command git show-ref 1.0rc1
  159e3478f0c806cf8b06aca98ec36db8732c31da refs/tags/1.0rc1
  Running command git reset --hard -q 159e3478f0c806cf8b06aca98ec36db8732c31da
  Running setup.py (path:/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk/setup.py) egg_info for package pybeanstalk
    Running command python setup.py egg_info
    running egg_info
    writing pybeanstalk.egg-info/PKG-INFO
    writing requirements to pybeanstalk.egg-info/requires.txt
    writing top-level names to pybeanstalk.egg-info/top_level.txt
    writing dependency_links to pybeanstalk.egg-info/dependency_links.txt
    reading manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    writing manifest file 'pybeanstalk.egg-info/SOURCES.txt'
  Source in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk has version 1.0rc1, which satisfies requirement pybeanstalk[twisted] from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]
  Installing extra requirements: 'twisted'
Requirement already satisfied: pyaml in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (17.12.1)
Requirement already satisfied: zope.interface in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (4.5.0)
Requirement already satisfied: Twisted>=15.2.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (18.4.0)
Requirement already satisfied: PyYAML in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pyaml->pybeanstalk[twisted]) (3.12)
Requirement already satisfied: setuptools in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from zope.interface->pybeanstalk[twisted]) (39.1.0)
Requirement already satisfied: constantly>=15.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (15.1.0)
Requirement already satisfied: incremental>=16.10.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (17.5.0)
Requirement already satisfied: hyperlink>=17.1.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (18.0.0)
Requirement already satisfied: Automat>=0.3.0 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (0.6.0)
Requirement already satisfied: idna>=2.5 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from hyperlink>=17.1.1->Twisted>=15.2.1->pybeanstalk[twisted]) (2.6)
Requirement already satisfied: six in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Automat>=0.3.0->Twisted>=15.2.1->pybeanstalk[twisted]) (1.11.0)
Requirement already satisfied: attrs in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Automat>=0.3.0->Twisted>=15.2.1->pybeanstalk[twisted]) (17.4.0)
Installing collected packages: pybeanstalk
  Found existing installation: pybeanstalk 1.0rc1
    Uninstalling pybeanstalk-1.0rc1:
      Created temporary directory: /tmp/pip-uninstall-b4l3kflc
      Removing file or directory /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/pybeanstalk.egg-link
      Removing pth entries from /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/easy-install.pth:
      Removing entry: /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk
      Successfully uninstalled pybeanstalk-1.0rc1
  Running setup.py develop for pybeanstalk
    Running command /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/python3 -c "import setuptools, tokenize;__file__='/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running egg_info
    writing top-level names to pybeanstalk.egg-info/top_level.txt
    writing dependency_links to pybeanstalk.egg-info/dependency_links.txt
    writing requirements to pybeanstalk.egg-info/requires.txt
    writing pybeanstalk.egg-info/PKG-INFO
    reading manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    writing manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/pybeanstalk.egg-link (link to .)
    Adding pybeanstalk 1.0rc1 to easy-install.pth file

    Installed /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk
Successfully installed pybeanstalk
Cleaning up...

Adding -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted] to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  pybeanstalk from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk

Finding the best candidates:
  found candidate -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk (constraint was <any>)

Finding secondary dependencies:

New dependencies found in this round:
  adding ['pyaml', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  pyaml
  pybeanstalk from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk

Finding the best candidates:
  found candidate pyaml==17.12.1 (constraint was <any>)
  found candidate -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk (constraint was <any>)

Finding secondary dependencies:
  pyaml==17.12.1            requires PyYAML

New dependencies found in this round:
  adding ['pyyaml', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  pyaml
  pybeanstalk from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk
  PyYAML

Finding the best candidates:
  found candidate pyaml==17.12.1 (constraint was <any>)
  found candidate -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk (constraint was <any>)
  found candidate pyyaml==3.12 (constraint was <any>)

Finding secondary dependencies:
  pyaml==17.12.1            requires PyYAML
  pyyaml==3.12              requires -
------------------------------------------------------------
Result of round 3: stable, done

Updated Pipfile.lock (b54d0d)!
Installing dependencies from Pipfile.lock (b54d0d)…
Installing '-e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@d5e372158c202adca4e1d1ddd9a6b063c6085137#egg=pybeanstalk'
$ "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/pip" install  --src "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src" --verbose    -e "git+ssh://git@github.com/beanstalkd/pybeanstalk.git@d5e372158c202adca4e1d1ddd9a6b063c6085137#egg=pybeanstalk" -i https://pypi.python.org/simple --exists-action w
Installing 'pyyaml==3.12 --hash=sha256:0c507b7f74b3d2dd4d1322ec8a94794927305ab4cebbe89cc47fe5e81541e6e8  --hash=sha256:16b20e970597e051997d90dc2cddc713a2876c47e3d92d59ee198700c5427736  --hash=sha256:3262c96a1ca437e7e4763e2843746588a965426550f3797a79fca9c6199c431f  --hash=sha256:326420cbb492172dec84b0f65c80942de6cedb5233c413dd824483989c000608  --hash=sha256:4474f8ea030b5127225b8894d626bb66c01cda098d47a2b0d3429b6700af9fd8  --hash=sha256:592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab  --hash=sha256:5ac82e411044fb129bae5cfbeb3ba626acb2af31a8d17d175004b70862a741a7  --hash=sha256:5f84523c076ad14ff5e6c037fe1c89a7f73a3e04cf0377cb4d017014976433f3  --hash=sha256:827dc04b8fa7d07c44de11fabbc888e627fa8293b695e0f99cb544fdfa1bf0d1  --hash=sha256:b4c423ab23291d3945ac61346feeb9a0dc4184999ede5e7c43e1ffb975130ae6  --hash=sha256:bc6bced57f826ca7cb5125a10b23fd0f2fff3b7c4701d64c439a300ce665fff8  --hash=sha256:c01b880ec30b5a6e6aa67b09a2fe3fb30473008c85cd6a67359a1b15ed6d83a4  --hash=sha256:ca233c64c6e40eaa6c66ef97058cdc80e8d0157a443655baa1b2966e812807ca  --hash=sha256:e863072cdf4c72eebf179342c94e6989c67185842d9997960b3e69290b2fa269'
$ "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/pip" install   --verbose  --no-deps  -r /tmp/pipenv-knh27j8z-requirements/pipenv-p8r7vqtg-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Installing 'pyaml==17.12.1 --hash=sha256:66623c52f34d83a2c0fc963e08e8b9d0c13d88404e3b43b1852ef71eda19afa3  --hash=sha256:f83fc302c52c6b83a15345792693ae0b5bc07ad19f59e318b7617d7123d62990'
$ "/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/pip" install   --verbose  --no-deps  -r /tmp/pipenv-knh27j8z-requirements/pipenv-jilwljf2-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Created temporary directory: /tmp/pip-ephem-wheel-cache-hujz4yfu
Created temporary directory: /tmp/pip-install-nys4uu19
Looking in indexes: https://pypi.python.org/simple
Obtaining pybeanstalk from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@d5e372158c202adca4e1d1ddd9a6b063c6085137#egg=pybeanstalk
  Running command git config --get-regexp remote\..*\.url
  remote.origin.url ssh://git@github.com/beanstalkd/pybeanstalk.git
  Clone in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk exists, and has correct URL (ssh://git@github.com/beanstalkd/pybeanstalk.git)
  Running command git rev-parse HEAD
  d5e372158c202adca4e1d1ddd9a6b063c6085137
  Skipping because already up-to-date.
  Running setup.py (path:/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk/setup.py) egg_info for package pybeanstalk
    Running command python setup.py egg_info
    running egg_info
    writing dependency_links to pybeanstalk.egg-info/dependency_links.txt
    writing pybeanstalk.egg-info/PKG-INFO
    writing top-level names to pybeanstalk.egg-info/top_level.txt
    writing requirements to pybeanstalk.egg-info/requires.txt
    reading manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    writing manifest file 'pybeanstalk.egg-info/SOURCES.txt'
  Source in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk has version 1.0rc1, which satisfies requirement pybeanstalk from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@d5e372158c202adca4e1d1ddd9a6b063c6085137#egg=pybeanstalk
Requirement already satisfied: pyaml in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk) (17.12.1)
Requirement already satisfied: PyYAML in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pyaml->pybeanstalk) (3.12)
Installing collected packages: pybeanstalk
  Found existing installation: pybeanstalk 1.0rc1
    Uninstalling pybeanstalk-1.0rc1:
      Created temporary directory: /tmp/pip-uninstall-cdgu0sj7
      Removing file or directory /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/pybeanstalk.egg-link
      Removing pth entries from /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/easy-install.pth:
      Removing entry: /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk
      Successfully uninstalled pybeanstalk-1.0rc1
  Running setup.py develop for pybeanstalk
    Running command /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/python3 -c "import setuptools, tokenize;__file__='/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running egg_info
    writing pybeanstalk.egg-info/PKG-INFO
    writing top-level names to pybeanstalk.egg-info/top_level.txt
    writing requirements to pybeanstalk.egg-info/requires.txt
    writing dependency_links to pybeanstalk.egg-info/dependency_links.txt
    reading manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    writing manifest file 'pybeanstalk.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages/pybeanstalk.egg-link (link to .)
    Adding pybeanstalk 1.0rc1 to easy-install.pth file

    Installed /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk
Successfully installed pybeanstalk
Cleaning up...

Created temporary directory: /tmp/pip-ephem-wheel-cache-x0ail1dg
Created temporary directory: /tmp/pip-install-46yhminu
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: pyyaml==3.12 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from -r /tmp/pipenv-knh27j8z-requirements/pipenv-p8r7vqtg-requirement.txt (line 1)) (3.12)
  Since it is already installed, we are trusting this package without checking its hash. To ensure a completely repeatable environment, install into an empty virtualenv.
Cleaning up...

Created temporary directory: /tmp/pip-ephem-wheel-cache-ty1ohhnn
Created temporary directory: /tmp/pip-install-at04ap6x
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: pyaml==17.12.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from -r /tmp/pipenv-knh27j8z-requirements/pipenv-jilwljf2-requirement.txt (line 1)) (17.12.1)
  Since it is already installed, we are trusting this package without checking its hash. To ensure a completely repeatable environment, install into an empty virtualenv.
Cleaning up...

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:01
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

##### Steps to replicate

In a new directory, run `pipenv install -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]`

Pipfile:

```yaml
[[source]]

verify_ssl = true
url = "https://pypi.python.org/simple"
name = "pypi"


[dev-packages]



[packages]

pybeanstalk = {extras = ["twisted"], ref = "1.0rc1", git = "ssh://git@github.com/beanstalkd/pybeanstalk.git", editable = true}


[requires]

python_version = "3.5"
```

Pipfile.lock:

```json
{
    "_meta": {
        "hash": {
            "sha256": "aa1d2cf1f90296352cc1a71904a82dbe2d355fb300a1f0cbbb20582c83b54d0d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyaml": {
            "hashes": [
                "sha256:66623c52f34d83a2c0fc963e08e8b9d0c13d88404e3b43b1852ef71eda19afa3",
                "sha256:f83fc302c52c6b83a15345792693ae0b5bc07ad19f59e318b7617d7123d62990"
            ],
            "version": "==17.12.1"
        },
        "pybeanstalk": {
            "editable": true,
            "git": "ssh://git@github.com/beanstalkd/pybeanstalk.git",
            "ref": "d5e372158c202adca4e1d1ddd9a6b063c6085137"
        },
        "pyyaml": {
            "hashes": [
                "sha256:0c507b7f74b3d2dd4d1322ec8a94794927305ab4cebbe89cc47fe5e81541e6e8",
                "sha256:16b20e970597e051997d90dc2cddc713a2876c47e3d92d59ee198700c5427736",
                "sha256:3262c96a1ca437e7e4763e2843746588a965426550f3797a79fca9c6199c431f",
                "sha256:326420cbb492172dec84b0f65c80942de6cedb5233c413dd824483989c000608",
                "sha256:4474f8ea030b5127225b8894d626bb66c01cda098d47a2b0d3429b6700af9fd8",
                "sha256:592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab",
                "sha256:5ac82e411044fb129bae5cfbeb3ba626acb2af31a8d17d175004b70862a741a7",
                "sha256:5f84523c076ad14ff5e6c037fe1c89a7f73a3e04cf0377cb4d017014976433f3",
                "sha256:827dc04b8fa7d07c44de11fabbc888e627fa8293b695e0f99cb544fdfa1bf0d1",
                "sha256:b4c423ab23291d3945ac61346feeb9a0dc4184999ede5e7c43e1ffb975130ae6",
                "sha256:bc6bced57f826ca7cb5125a10b23fd0f2fff3b7c4701d64c439a300ce665fff8",
                "sha256:c01b880ec30b5a6e6aa67b09a2fe3fb30473008c85cd6a67359a1b15ed6d83a4",
                "sha256:ca233c64c6e40eaa6c66ef97058cdc80e8d0157a443655baa1b2966e812807ca",
                "sha256:e863072cdf4c72eebf179342c94e6989c67185842d9997960b3e69290b2fa269"
            ],
            "version": "==3.12"
        }
    },
    "develop": {}
}
```

**Comment by erinxocon** [comment] 2018-05-03 05:06
Hi @bjmc! Thanks for using pipenv!  I believe this issue is a duplicate of #1997, even though you are doing an editable install, I think the egg fragment isn't being parsed correctly.  I'm going to close this issue in favor of the other one, but these logs files and lock files will help!

**Comment by bjmc** [comment] 2018-05-03 05:07
Note that it *does* get installed correctly initially:

```bash
bjmc@xps:~/Sandbox/pipenvtest$ pipenv install -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]
Creating a Pipfile for this project…
Installing -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]…
Looking in indexes: https://pypi.python.org/simple
Obtaining pybeanstalk[twisted] from git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted]
  Updating /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/src/pybeanstalk clone (to revision 1.0rc1)
Requirement already satisfied: pyaml in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (17.12.1)
Requirement already satisfied: zope.interface in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (4.5.0)
Requirement already satisfied: Twisted>=15.2.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pybeanstalk[twisted]) (18.4.0)
Requirement already satisfied: PyYAML in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from pyaml->pybeanstalk[twisted]) (3.12)
Requirement already satisfied: setuptools in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from zope.interface->pybeanstalk[twisted]) (39.1.0)
Requirement already satisfied: constantly>=15.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (15.1.0)
Requirement already satisfied: Automat>=0.3.0 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (0.6.0)
Requirement already satisfied: hyperlink>=17.1.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (18.0.0)
Requirement already satisfied: incremental>=16.10.1 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Twisted>=15.2.1->pybeanstalk[twisted]) (17.5.0)
Requirement already satisfied: attrs in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Automat>=0.3.0->Twisted>=15.2.1->pybeanstalk[twisted]) (17.4.0)
Requirement already satisfied: six in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from Automat>=0.3.0->Twisted>=15.2.1->pybeanstalk[twisted]) (1.11.0)
Requirement already satisfied: idna>=2.5 in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/lib/python3.5/site-packages (from hyperlink>=17.1.1->Twisted>=15.2.1->pybeanstalk[twisted]) (2.6)
Installing collected packages: pybeanstalk
  Found existing installation: pybeanstalk 1.0rc1
    Uninstalling pybeanstalk-1.0rc1:
      Successfully uninstalled pybeanstalk-1.0rc1
  Running setup.py develop for pybeanstalk
Successfully installed pybeanstalk

Adding -e git+ssh://git@github.com/beanstalkd/pybeanstalk.git@1.0rc1#egg=pybeanstalk[twisted] to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (b54d0d)!
Installing dependencies from Pipfile.lock (b54d0d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:01
To activate this project's virtualenv, run the following:
 $ pipenv shell
bjmc@xps:~/Sandbox/pipenvtest$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bjmc@xps:~/Sandbox/pipenvtest$ . /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/activate

(pipenvtest-TFNZ8u_e) bjmc@xps:~/Sandbox/pipenvtest$ pip freeze | grep Twisted
Twisted==18.4.0
```

But then, because it's not in `Pipfile.lock`, future installs based on that lockfile will fail:

```bash
bjmc@xps:~/Sandbox/pipenvtest$ pipenv --rm
Removing virtualenv (/home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e)…
bjmc@xps:~/Sandbox/pipenvtest$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python3.5m to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.5m
Using base prefix '/usr'
New python executable in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/python3.5m
Also creating executable in /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e
Installing dependencies from Pipfile.lock (b54d0d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:03
To activate this project's virtualenv, run the following:
 $ pipenv shell
bjmc@xps:~/Sandbox/pipenvtest$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bjmc@xps:~/Sandbox/pipenvtest$ . /home/bjmc/.local/share/virtualenvs/pipenvtest-TFNZ8u_e/bin/activate
(pipenvtest-TFNZ8u_e) bjmc@xps:~/Sandbox/pipenvtest$ pip freeze | grep Twisted
```

**Comment by bjmc** [comment] 2018-05-03 05:09
Sounds good! I wasn't sure if it was a duplicate or not, because the docs suggest that without `-e`, it won't pull in dependencies for VCS installs.

**Comment by erinxocon** [comment] 2018-05-03 05:14
Hmm this might not be a duplicate after all just related, I'll have to investigate tomorrow.  @techalchemy any thoughts?  Trying to get back into the code base.

**Comment by bjmc** [comment] 2018-05-03 05:18
Please let me know if there's anything else I can provide to help work through this issue. Thanks to all the contributors for your work on Pipenv. I'm a new user, and it feels like a big improvement to the Python packaging world.

**Comment by techalchemy** [comment] 2018-05-03 06:29
It's the same issue it's just more clearly articulated, it's just an issue with the parser.

I did a complete refactor of the parser but the PyPA has likely uses for it outside of our codebase so I haven't merged it yet, waiting until I have time to break it out into a library

**Comment by erinxocon** [comment] 2018-05-03 15:11
@techalchemy want me to tackle that today?  I have some time.

**Comment by techalchemy** [comment] 2018-05-07 20:07
`11.10.2` is out, take it for a spin

**Closed by techalchemy** 2018-05-07 20:07 UTC
