### ISSUE TITLE
pipenv fails to find venv unless parent python in path

### ISSUE THREAD

**Issue by hwine** [pypa/pipenv#2289] opened 2018-06-02 00:07 UTC
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

``pipenv`` can't find the virtualenv it built unless the version of python the virtual env was created from is in the current path.

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/usr/local/lib/python3.5/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-17134-Microsoft',
 'platform_system': 'Linux',
 'platform_version': '#81-Microsoft Sun May 20 01:14:00 PST 2018',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `LANG`
  - `TMUX_PANE`
  - `MOZ_USER`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_DATA_DIRS`
  - `PWD`
  - `PATH`
  - `SHLVL`
  - `LESSCLOSE`
  - `NAME`
  - `LOGNAME`
  - `TMUX`
  - `DISPLAY`
  - `LESSOPEN`
  - `HISTCONTROL`
  - `SHELL`
  - `_`
  - `TMUX_PLUGIN_MANAGER_PATH`
  - `BASH_FUNC_tmux%%`
  - `EDITOR`
  - `PYTHONUNBUFFERED`
  - `USER`
  - `TERM`
  - `HOME`
  - `HOSTTYPE`
  - `PASTEBIN_NAME`
  - `SSH_AUTH_SOCK`
  - `SSH_AGENT_PID`
  - `GOPATH`
  - `PIP_PYTHON_PATH`
  - `VISUAL`
  - `PIP_REQUIRE_VIRTUALENV`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/hwine/.cargo/bin:/home/hwine/bin:/home/hwine/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/Hal Wine/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Hal Wine/AppData/Local/Keybase:/mnt/c/Program Files/Microsoft VS Code/bin:/usr/local/bin:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/hwine`

---------------------------

</details>

------------

##### Expected result

``pipenv shell`` should work regardless of which python is in the path.

##### Actual result

E.g: after a pipenv environment has been created, and a fresh shell (login) initiated, the virtualenv can not be found:
```
$ pipenv shell
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
1 [hwine@hwine-surface MY_PROJECT]
$ pipenv --venv
No virtualenv has been created for this project yet!
1 [hwine@hwine-surface MY_PROJECT]
```
In fact, the virtualenv is exactly where it should be:
```
$ ~/.ve/MY_PROJECT-j72jD_YQ/bin/python --version
Python 3.6.4
```
But it can't be found until the parent python is available in the path (I use pyenv, but only activate it when I need a non-system python in my path)
```
$ use Pyenv
source /home/hwine/bin/usePyenv
0 [hwine@hwine-surface MY_PROJECT]
$ pipenv --venv
/home/hwine/.ve/MY_PROJECT-j72jD_YQ
0 [hwine@hwine-surface MY_PROJECT]
$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
. /home/hwine/.ve/MY_PROJECT-j72jD_YQ/bin/activate
```

My expectation when I use a virtualenv is that only the virtualenv need be in my path, which is usually accomplished by sourcing the activate script (as ``pipenv shell`` does above). Requiring the parent python to be in the path just to activate the virtualenv is a new hurdle I'd prefer not to climb.

##### Steps to replicate

1. create a pipenv environment using a non-system python (called the "parent python" below)
2. start a new shell (login)
3. ensure the path does not contain the parent python
4. attempt to run ``pipenv shell``

**Comment by uranusjr** [comment] 2018-06-02 01:05
Hmm, I personally does not have Pipenv’s parent Python in my path, but never ran into any problems. But I don’t usually `pipenv shell` often either, so it’s hard to say.

To clarify:

* What platform are you on? (I’m guessing it is WSL on Windows? What distribution?)
* How do you install Pipenv’s parent Python and Pipenv itself?
* Do things other than `shell` work?

**Comment by techalchemy** [comment] 2018-06-02 04:14
Pipenv uses pew on the backend to enter a virtualenv. As a step during the process of entering a shell session pipenv ensures that the project and the virtualenv exist. Part of this involves Pipfile validation, but if it can’t find the python version specified I guess it gets stuck.

I’m not totally sure what the implications of changing this behavior would be, but I’m guessing they are probably more significant than it seems at first glance. I’d recommend keeping pyenv on your path even if it’s at the back while we untangle this. 

As an FYI you can use pyenv all the time and tell it to globally prefer the system python

**Comment by A3880036** [comment] 2018-06-03 08:09
Accept

**Comment by techalchemy** [comment] 2018-06-03 20:58
I actually can't reproduce this, and I noticed you are on a outdated version of pipenv.  I saw version 11.10 mentioned, so you probably should upgrade that.  Closing for now but let us know if this persists

**Closed by techalchemy** 2018-06-03 20:58 UTC

**Comment by hwine** [comment] 2018-06-07 18:26
ftr: after upgrade to pipenv, version 2018.05.18, I could not reproduce. \o/
