### ISSUE TITLE
2024.3.0 --skip-lock --dev install regression

### ISSUE THREAD

**Issue by danilodesolesonar** [pypa/pipenv#6301] opened 2024-10-30 15:55 UTC
### Issue description

hello, we also use `pipenv` to manage our python dependencies. We noticed that `pipenv install --dev --skip-lock` no longer install dependencies. We do not have and use the lock file. Before, up to version 2024.0.1. the same command resulted in successful dependencies installation.

### Expected result

Running `pipenv install --dev --skip-lock` with version 2023.0.1

```
pipenv --version
pipenv, version 2024.0.1
pip freeze
certifi==2024.8.30
distlib==0.3.9
filelock==3.16.1
pipenv==2024.0.1
platformdirs==4.3.6
virtualenv==20.27.1
echo ciao
ciao
pipenv run pip freeze
attrs==24.2.0
aws-cdk-lib==2.1[64](https://github.com/.../.../actions/runs/.../job/...#step:6:66).1
aws-cdk.asset-awscli-v1==2.2.209
aws-cdk.asset-kubectl-v20==2.1.3
aws-cdk.asset-node-proxy-agent-v6==2.1.0
aws-cdk.cloud-assembly-schema==38.0.1
black==24.10.0
boto3==1.35.51
botocore==1.35.51
cattrs==24.1.2
cdklabs.cdk-validator-cfnguard==0.0.60
certifi==2024.8.30
charset-normalizer==3.4.0
click==8.1.7
constructs==10.4.2
coverage==7.6.4
idna==3.10
importlib_resources==6.4.5
iniconfig==2.0.0
jmespath==1.0.1
jsii==1.104.0
mypy-extensions==1.0.0
packaging==24.1
pathspec==0.12.1
platformdirs==4.3.6
pluggy==1.5.0
publication==0.0.3
pytest==8.3.3
pytest-cov==6.0.0
python-dateutil==2.9.0.post0
PyYAML==6.0.2
requests==2.32.3
requests-toolbelt==1.0.0
s3transfer==0.10.3
six==1.16.0
ss_cdk==1.11.7
typeguard==2.13.3
typing_extensions==4.12.2
urllib3==2.2.3
```

### Actual result

Running `pipenv install --dev --skip-lock` with version 2024.3.0

```
pipenv --version
pipenv, version 2024.3.0
pip freeze
certifi==2024.8.30
distlib==0.3.9
filelock==3.16.1
packaging==24.1
pipenv==2024.3.0
platformdirs==4.3.6
virtualenv==20.27.1
echo ciao
ciao
pipenv run pip freeze
```

### Steps to replicate
1. Install latest pipenv 2023.0.3
2. Run pipenv install --dev --skip-lock (with any pipfile)
3. Run pipenv run pip freeze

**Comment by matteius** [comment] 2024-10-30 20:31
@danilodesolesonar I checked and it didn't seem this should be an issue on `2024.3.0` and latest pipenv  is not `2023.0.3` -- could you double check?

**Comment by matteius** [comment] 2024-10-31 03:19
`2024.3.1` has been released.

**Comment by danilodesolesonar** [comment] 2024-10-31 09:32
Hi @matteius, I confirm we initially detect this issue in version `2024.3.0`, not sure why I confused with 2024.0.3, my mind tricks me sometimes... Also the latest `2024.3.1` is affected. To reproduce the error: 
1. check if the version you have installed is `2024.3.0` or major
2. create a simple pipfile as mentioned below (2)
3. run `pipenv install --dev --skip-lock`
4. run `pipenv run pip freeze`, you will see an empty output (3)

(2) the pipfile I used
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
aws-cdk-lib = "*"

[dev-packages]
pytest = "*"

[requires]
python_version = "3.11"
```

(3) the output 
```
[panilo@fedora testpipenv]$ pipenv --version
pipenv, version 2024.3.1
[panilo@fedora testpipenv]$ pipenv install --dev --skip-lock
The flag --skip-lock has been reintroduced (but is not recommended).  Without the lock resolver it is difficult to manage multiple package indexes, and hash checking is not provided.  
However it can help manage installs with current deficiencies in locking across platforms.
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile...
Installing dependencies from Pipfile...
[panilo@fedora testpipenv]$ pipenv run pip freeze
```

Removing the `--skip-lock` flag seems to solve the issue momentarily, though this should not affect the install behaviour.

**Comment by matteius** [comment] 2024-10-31 10:09
Ok, you're right.   If anyone has spare cycles to help patch it with tests, I would be grateful.  Otherwise we'll see if I have time over the weekend, but I might not.

**Comment by matteius** [comment] 2024-10-31 10:19
Actually, I just found the issue -- it should be trivial to fix.

**Comment by matteius** [comment] 2024-10-31 10:40
PR is up for review with test -- your reproduction example (the second one) was perfect for a test case.

**Comment by danilodesolesonar** [comment] 2024-10-31 10:42
Thank you very much @matteius for the quick response. I apologise for the initial confusion.

**Comment by awilson-adsk** [comment] 2024-11-04 11:31
Hi @matteius, unsure if this is the same issue but we're still seeing a problem with the command `pipenv install --dev --skip-lock` not installing dependencies of editable packages since 2024.3.0.
For example, this in our Pipfile
```
[dev-packages]
package-xyz = {editable = true, extras = ["dev"], path = "."}
```
And this (simplified) setup.py
```
from setuptools import setup

extras_require = {"dev": ["autopep8", "flake8", "sphinx"]}

setup(
    name="package-xyz",
    extras_require=extras_require,
)
```
Will install the dependencies on 2024.2.0 but will not on 2024.3.0 or 2024.3.1.
Are you able to reproduce this and check? We're running on python 3.12.
I can open a new issue if required.

**Comment by matteius** [comment] 2024-11-05 16:09
Could this be rechecked on `2024.4.0` -- the PR got merged which closed the issue but hadn't been released until today.

**Closed** 2024-11-05 16:36 UTC
Labels: Type: Regression, triage, Contributor Candidate
