### ISSUE TITLE
Provide argument which specifies the subname of the virtual environment folder instead of automatic hashname

### ISSUE THREAD

**Issue by rishatsharafiev** [pypa/pipenv#1292] opened 2018-01-12 13:35 UTC
Hello.
It's my proposal. Assume that we in folder `~/dev/project/dummy`. let's create virtual environment with command and argument `pipenv shell --name=subname`. It should create path `~/.local/share/virtualenvs/dummy-subname`. Else it just uses old mechanism.
Thank you.

**Comment by cjw296** [comment] 2018-01-16 08:03
@rishatsharafiev - any chance you could close this as it looks do be a dupe of #1049?

**Comment by rishatsharafiev** [comment] 2018-01-16 08:53
@cjw296  that's great, thank you.

**Closed** 2018-01-23 16:53 UTC
