### ISSUE TITLE
Duplicate entries in Pipfile.lock in packages and dev-packages section

### ISSUE THREAD

**Issue by jnoortheen** [pypa/pipenv#1196] opened 2017-12-12 14:44 UTC
After generating lock file, it contains two different versions of the same package under packages and dev-packages respectively. 

The file looks like this. I see duplicates of Django, cffi and some other packages. I've updated the dependency graph and lock file here. 
```
{
    "_meta": {
        "hash": {
            "sha256": "29e23f605b6b09d829b5815037e683fbbf9edcc01e9fbb8c1dbc85be93984c3b"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "3.6.3",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "4.14.3-1-MANJARO",
            "platform_system": "Linux",
            "platform_version": "#1 SMP PREEMPT Thu Nov 30 14:22:30 UTC 2017",
            "python_full_version": "3.6.3",
            "python_version": "3.6",
            "sys_platform": "linux"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:75ce405d60f092f6adf904058d023eeea0e6d380f8d9c36134bac73da736023d",
                "sha256:8918e392530d8fc6965a56af6504229e7924c27265893f3949aa0529cd1d4b99"
            ],
            "version": "==1.11.7"
        },
    },
    "develop": {
        "django": {
            "hashes": [
                "sha256:af18618ce3291be5092893d8522fe3919661bf3a1fb60e3858ae74865a4f07c2",
                "sha256:9614851d4a7ff8cbd32b73c6076441f377c45a5bbff7e771798fb02c43c31f47"
            ],
            "version": "==2.0"
        },
    }
}
```

##### Describe your environment

1. Linux x64
1. Python version: `3.6.3`
1. Pipenv version: `9.0.0`

##### Expected result

See only one version of a package in the lock file. So we can be sure which version is installed.

##### Actual result

multiple version locked for the same library in default and develop sections
[graph.txt](https://github.com/pypa/pipenv/files/1551975/graph.txt)

[Pipfile.lock.txt](https://github.com/pypa/pipenv/files/1551976/Pipfile.lock.txt)

**Comment by sobolevn** [comment] 2017-12-12 16:33
This is a duplicate of https://github.com/pypa/pipenv/issues/1177

**Comment by techalchemy** [comment] 2017-12-13 04:06
hey @jnoortheen sorry you ran into this, as @sobolevn mentioned this is a duplicate of #1177 so I'm going to go ahead and close this out so we can keep tracking it over there.

Thanks for using pipenv and taking the time to report this!

**Closed by techalchemy** 2017-12-13 04:06 UTC
