### ISSUE TITLE
Peer dependencies of git package not downloaded

### ISSUE THREAD

**Issue by yoshivda** [pypa/pipenv#4291] opened 2020-05-29 13:33 UTC
### Issue description

Dependencies from a dependency from a git source are no longer automatically installed after the 2020 update.

### Expected result

Install all required packages, including the requirements of dependencies

### Actual result

Peer dependencies are not resolved

### Steps to replicate

Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pycodestyle = {git = "https://github.com/PyCQA/pycodestyle.git"}
generator_python = {git = "https://gitlab.ewi.tudelft.nl/weblab/generator-python.git"}
mock = "*"

[requires]
python_version = "3.8"

[scripts]
all = "sh -c 'pipenv run codestyle && pipenv run generator && pipenv run tests'"
codestyle = "pycodestyle --exclude output,.venv ."
generator = "sh -c 'python -m generator assignments'"
tests = "sh run-tests.sh"
```

After `pipenv install`, running `pipenv run generator` will result in errors due to missing packages. These packages are listed in this repo's setup.py, but are not installed. With `pipenv==2018.11.26` these packages are downloaded and everything works.

**Comment by frostming** [comment] 2020-05-29 13:56
Can't reproduce here, can you try to minimize the case?
At least `pipenv install git+https://github.com/pallets/flask.git#egg=flask` works fine.

Also can you provide the output of `env|grep -i PIPENV`?

**Comment by yoshivda** [comment] 2020-05-29 14:05
The case for me: the dependency generator_python requires some packages, these are not installed. The minimal pipfile would just contain that one, and to test it the `generator` script.

The command you list gives no output for me 😕

**Comment by yoshivda** [comment] 2020-05-29 14:15
An open source repo using the same dependency is [this one](https://gitlab.ewi.tudelft.nl/ads-maths/course-material), see [this job log](https://gitlab.ewi.tudelft.nl/ads-maths/course-material/-/jobs/1313643) to see the failure. This job is a manual rerun, so there were no changes since the last build (which passed)

**Comment by frostming** [comment] 2020-05-31 09:08
@yoshivda The Pipfile.lock lacks peer dependencies, can you try `pipenv lock --clear` and see whether the file is fixed?

**Comment by techalchemy** [comment] 2020-06-01 16:04
sorry for asking the dumb question here, but why invoke `python` via `sh`? Does this work if you just change your Pipfile to say:

```toml
[scripts]
all = "pipenv run codestyle && pipenv run generator && pipenv run tests"
codestyle = "pycodestyle --exclude output,.venv ."
generator = "python -m generator implementation --output output/implementation"
generatoranalysis = "python -m non_programming_generator analysis/exercises"
tests = "sh run-tests.sh"
```

You also may want to consider using the full path to `sh`, e.g. `/usr/bin/sh`

**Comment by yoshivda** [comment] 2020-06-02 06:40
@frostming That indeed solved it, thanks a lot! I was unable to find this behaviour change in the changelog though, and I want to stress that this exact lockfile worked fine before the update. Did I miss an entry in the changelog, or if not, could this be added?

**Comment by yoshivda** [comment] 2020-06-02 07:00
@techalchemy Just tried and that works too, thanks!

**Comment by frostming** [comment] 2020-06-02 09:01
@yoshivda That was a bug in previous releases -- Installing dependencies of editable packages even they are not specified in the lock file.

It is no longer an issue with the latest release, I'm going to close it.

**Closed by frostming** 2020-06-02 09:01 UTC
Labels: Status: Awaiting Update :hourglass_flowing_sand:, Status: Needs More Information

**Comment by yoshivda** [comment] 2020-06-02 09:12
@frostming Thanks for the explanation, that helps 🙂 I still can't find it in the changelog, but that might be my bad
