### ISSUE TITLE
pipenv install --verbose is not verbose

### ISSUE THREAD

**Issue by remram44** [pypa/pipenv#1198] opened 2017-12-12 23:05 UTC
##### Describe your environment

1. OS Type: macOS
1. Python version: 2.7.14
1. Pipenv version: 9.0.0

##### Expected result

`pipenv install --verbose` to print the name of packages being built/installed as that happen, so that I can link a pip exception to a specific package.

At least, something more being printed when I pass in `--verbose`.

##### Actual result

```
$ pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
...
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/fq/1chpjqw56lv8zq8n14cbn4k40000gn/T/tmpqZz4fybuild/functools32/
```

```
$ pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
...
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/fq/1chpjqw56lv8zq8n14cbn4k40000gn/T/tmpaHHhN0build/functools32/
```

On a related note, functools32 doesn't really work with pipenv, but that's their fault.

**Comment by techalchemy** [comment] 2017-12-13 01:38
@remram44 sorry you ran into this issue.  I see you omitted the actual traceback. Would you mind including the text of the traceback and the contents of your `Pipfile`?

**Comment by remram44** [comment] 2017-12-13 02:14
Actually it seems that passing `--verbose` multiple times actually results in more messages being printed. This is pretty weird and should probably be mentioned on the --help screen. How many do I need to see every message?

**Comment by nateprewitt** [comment] 2017-12-13 02:48
@remram44 I don't think that makes sense. It's a boolean flag so it either prints messages or it doesn't.

**Comment by remram44** [comment] 2017-12-13 03:19
Quite. It seems that this is unrelated to me passing `--verbose` multiple times.

Basically, what I would want to know is, when pipenv fails, what is the chain of packages that led to the package that fails to build (usually functools32 or subprocess32, because lots of packages depend on those, and their setup.py don't work).

**Comment by techalchemy** [comment] 2017-12-13 04:04
@remram44 if you are having an issue with pipenv you are going to need to provide us with more information, including the full output, tracebacks, Pipfile, etc.

I'm going to close this issue for now unless there is a full output you can provide showing us what the problem is that you're encountering. In any event this is almost certainly not a problem with the CLI flag, but an argument can be made for better exception handling.

**Closed** 2017-12-13 04:04 UTC

**Comment by rodmaz** [comment] 2019-03-07 21:25
I am having exactly the same problem when using `pipenv` to install h3. I do have however the compiler tools in my `$PATH`:

```
- which cc
/usr/bin/cc
- which make
/Applications/Xcode.app/Contents/Developer/usr/bin/make
- which cmake
/usr/local/bin/cmake
```

When I install h3 from my project (pipenv) environment, it does install it successfully but `/out` directory is empty and obviously the needed `libh3.1.dylib` is not available.

```
OSError: dlopen(/Users/rodrigo/.local/share/virtualenvs/myproject--NqKkPOW/lib/python3.7/site-packages/h3/out/libh3.1.dylib, 6): image not found
```

Any ideas?
